// ─── Allergies Clean Picks ────────────────────────────────
// 8 verified clean picks across oral, nasal, and eye relief.
// Editorial backbone: Zyrtec/Claritin/Allegra tablets rejected (titanium
// dioxide); "dye-free" kids' cetirizine syrups rejected (parabens +
// propylene glycol). Clean oral options are homeopathic or sedating; the
// clean effective conventional option lives in eye drops.

import type { Pick } from './painFeverPicks';

export const ALLERGY_PICKS: Pick[] = [
  {
    name: 'Genexa Allergy Care',
    activeIngredient: 'Homeopathic allergy & decongestant blend',
    classKey: 'homeopathic',
    classTag: 'HOMEOPATHIC',
    form: 'oral',
    topPick: 'oral',
    subline: 'Adult · runny nose · sneezing · itchy nose & throat · congestion',
    why: 'Drug-free, non-drowsy chewable with all-organic inactives: organic acai flavor, carnauba wax, maltodextrin, rice bran extract, tapioca dextrose. No artificial dyes, sweeteners, preservatives, or common allergens. Certified organic and vegan.',
    honestNote: 'Homeopathic preparation per FDA framework; claims are based on traditional homeopathic practice, not accepted medical evidence. Evidence base discussed in Carlston M (ed), Classical Homeopathy (Churchill Livingstone, 2003).',
    retailers: ['CVS', 'Target', 'Walmart', 'Whole Foods', 'Sprouts'],
    priceTier: '$$ premium',
  },
  {
    name: "Genexa Kids' Allergy",
    activeIngredient: 'Diphenhydramine HCl 12.5mg / 5mL',
    classKey: 'antihistamine',
    classTag: 'ANTIHISTAMINE',
    form: 'oral',
    topPick: 'kids',
    ageBadge: '👶 Ages 6+',
    subline: 'Kids · runny nose · sneezing · itchy nose & throat · watery eyes',
    why: "Same active ingredient as Children's Benadryl, but the only inactive ingredients are organic agave syrup, natural citrus extract, and purified water — no artificial dyes, parabens, or common allergens. The cleanest kids' oral antihistamine we found.",
    honestNote: 'Diphenhydramine is a first-generation (sedating) antihistamine and lasts only 4–6 hours. Best for occasional or nighttime relief — not a daily-control option, and not ideal for older adults due to drowsiness. For gentle daily relief, the homeopathic picks are a better fit.',
    retailers: ['Walmart', 'CVS', 'Target', 'Whole Foods'],
    priceTier: '$$ premium',
  },
  {
    name: 'Boiron AllergyCalm',
    activeIngredient: 'Homeopathic blend (Allium cepa, Euphrasia, Sabadilla)',
    classKey: 'homeopathic',
    classTag: 'HOMEOPATHIC',
    form: 'oral',
    subline: 'Adult & kids 2+ · sneezing · runny nose · itchy, watery eyes',
    why: 'Non-drowsy meltaway tablets that dissolve under the tongue — no water needed. Three clean inactives: croscarmellose sodium, lactose, magnesium stearate. No artificial sweeteners, flavors, colors, or preservatives. No known drug interactions or rebound effect. A Kids version is available.',
    honestNote: 'Homeopathic preparation per FDA framework; claims based on traditional homeopathic practice, not accepted medical evidence. See Carlston M (ed), Classical Homeopathy (Churchill Livingstone, 2003). Contains lactose.',
    retailers: ['CVS', 'Walgreens', 'Whole Foods', 'Sprouts'],
    priceTier: 'Standard',
  },
  {
    name: 'Xlear Nasal Spray',
    activeIngredient: 'Xylitol + saline',
    classKey: 'salineNasal',
    classTag: 'SALINE · DRUG-FREE',
    form: 'nasal',
    topPick: 'nasal',
    subline: 'Daily rinse for pollen, congestion, dryness — use as often as needed',
    why: 'Four ingredients: purified water, xylitol, sodium chloride, and grapefruit seed extract. Drug-free and non-addictive — no rebound congestion. Physically rinses pollen and irritants out of the nasal passages instead of masking symptoms.',
    retailers: ['CVS', 'Walgreens', 'Target', 'Walmart', 'Whole Foods', 'Sprouts'],
    priceTier: 'Standard',
  },
  {
    name: 'NeilMed Sinus Rinse',
    activeIngredient: 'Sodium chloride + sodium bicarbonate',
    classKey: 'salineNasal',
    classTag: 'SALINE RINSE · DRUG-FREE',
    form: 'nasal',
    subline: 'Flushes pollen & mucus from the sinuses — drug-free irrigation',
    why: 'Preservative-free, iodine-free USP-grade saline. Just sodium chloride and sodium bicarbonate in premixed packets. The most thorough drug-free way to physically clear allergens and mucus from the nasal passages.',
    honestNote: 'Use only distilled, sterile, or previously boiled-and-cooled water — never untreated tap water (FDA guidance, to avoid a rare infection risk).',
    retailers: ['CVS', 'Walgreens', 'Walmart', 'Target', 'Whole Foods'],
    priceTier: 'Standard',
  },
  {
    name: "Beekeeper's Naturals Nasal Spray",
    activeIngredient: 'Propolis + xylitol + saline',
    classKey: 'propolis',
    classTag: 'PROPOLIS · DRUG-FREE',
    form: 'nasal',
    subline: 'Cleanses & soothes nasal passages — propolis-powered saline',
    why: 'A drug-free, non-habit-forming saline base with bee propolis and xylitol (the Max version adds eucalyptus and oregano oil). Natural preservatives only — citric acid, nisin, poly-lysine. Soothes and moisturizes while clearing congestion.',
    honestNote: 'Bee-product allergy disclaimer: avoid if allergic to bees, bee products, or propolis. Formulated for adults (18+); ask your pediatrician before use in children.',
    retailers: ['CVS', 'Whole Foods', 'Sprouts'],
    priceTier: '$$ premium',
  },
  {
    name: 'Similasan Allergy Eye Relief',
    activeIngredient: 'Homeopathic blend (Eyebright, Sabadilla, Apis)',
    classKey: 'homeopathic',
    classTag: 'HOMEOPATHIC · EYE',
    form: 'eye',
    subline: 'Itchy, burning, watering eyes from allergies',
    why: 'Drug-free homeopathic eye drops — no vasoconstrictors that can cause rebound redness. Botanical extracts in a purified-water and phosphate-buffer base. A single-use, preservative-free version is available for sensitive eyes. Eye-doctor recommended, 40+ year Swiss brand.',
    honestNote: 'Homeopathic preparation per FDA framework; claims based on traditional homeopathic practice, not accepted medical evidence. See Carlston M (ed), Classical Homeopathy (Churchill Livingstone, 2003). The multi-dose bottle uses a mild preservative — choose the single-use vials to avoid it entirely.',
    retailers: ['CVS', 'Walgreens', 'Walmart', 'Target', 'Sprouts'],
    priceTier: 'Standard',
  },
  {
    name: 'Alaway Preservative Free',
    activeIngredient: 'Ketotifen 0.025%',
    classKey: 'antihistamine',
    classTag: 'ANTIHISTAMINE · EYE',
    form: 'eye',
    subline: 'Fast relief for itchy allergy eyes — up to 12 hours',
    why: 'An FDA-approved antihistamine eye drop with no preservative — just glycerin, water, and pH adjusters. Works in minutes right at the source of eye itch, and is non-drowsy because it acts topically. The only conventional drug in this lineup that meets the clean standard. Ages 3+.',
    honestNote: 'Buy the Preservative Free single-dose version specifically — the regular Alaway bottle contains benzalkonium chloride. Remove contact lenses before use.',
    retailers: ['CVS', 'Walgreens', 'Walmart', 'Target', 'Grocery'],
    priceTier: '$$ premium',
  },
];