// ─── Cold & Flu Clean Picks ───────────────────────────────
// 13 verified clean picks across oral, topical, sublingual forms.

import type { Pick } from './painFeverPicks';

export const COLD_FLU_PICKS: Pick[] = [
  {
    name: 'Umcka Cold Relief Syrup',
    activeIngredient: 'Pelargonium sidoides 1X',
    classKey: 'homeopathicLow',
    classTag: 'HOMEOPATHIC · LOW DILUTION',
    form: 'oral',
    topPick: 'oral',
    subline: 'Cold symptoms, cough, congestion, sore throat — at first sign',
    why: 'Real South African geranium root extract at 1X dilution — measurable active plant compound still present. Cochrane has reviewed Pelargonium sidoides multiple times with positive findings for upper respiratory symptoms. Inactive ingredients are clean: aronia juice, citric acid, glycerin, fructose, purified water.',
    honestNote: 'Syrup form contains ethyl alcohol. Chewable tablets and hot drink mix versions are alcohol-free if preferred. Labeled homeopathic per FDA framework but contains real plant extract.',
    retailers: ['CVS', 'Walgreens', 'Walmart', 'Sprouts', 'Whole Foods'],
    priceTier: 'Standard',
  },
  {
    name: "Genexa Kids' Multi-Symptom Cold & Flu",
    activeIngredient: 'Acetaminophen 320mg + Guaifenesin 100mg + Dextromethorphan 5mg per 10mL',
    classKey: 'pediatricCombo',
    classTag: 'PEDIATRIC · CLEAN COMBO',
    form: 'oral',
    topPick: 'kids',
    ageBadge: '👶 Ages 4+',
    subline: 'Kids · fever · cough · sore throat · chest congestion',
    why: 'The cleanest pediatric multi-symptom cold formula available. Same active ingredients as conventional brands but without artificial dyes, sweeteners, parabens, or phenylephrine. Organic agave syrup as the sweetener base. Non-drowsy formula.',
    honestNote: 'Combo product with 3 active ingredients — only use when child has all 3 symptoms (fever + cough + congestion). For single-symptom relief, choose single-active products instead.',
    retailers: ['Walmart', 'Whole Foods', 'CVS', 'Walgreens', 'Target'],
    priceTier: '$$ premium',
  },
  {
    name: 'Badger Aromatic Chest Rub',
    activeIngredient: 'Organic eucalyptus, rosemary, ravintsara, tea tree oils',
    classKey: 'topicalChestRub',
    classTag: 'TOPICAL · HERBAL',
    form: 'topical',
    topPick: 'topical',
    subline: 'Chest congestion, blocked sinuses, easier breathing',
    why: 'Petroleum-free alternative to Vicks VapoRub. USDA Certified Organic with olive oil and castor oil base (no seed oils). Eucalyptus and rosemary essential oils provide the decongestant effect without synthetic camphor or petrolatum.',
    honestNote: 'Premium price ($13-20 per 2oz tin). Essential-oil based — patch test first. Safe for the whole family per Badger guidance.',
    retailers: ['Walmart', 'Whole Foods', 'Sprouts'],
    priceTier: '$$ premium',
  },
  {
    name: 'Equate Mucus ER (Walmart Generic)',
    activeIngredient: 'Guaifenesin 600mg',
    classKey: 'expectorant',
    classTag: 'EXPECTORANT',
    form: 'oral',
    subline: 'Chest congestion, productive cough, thinning mucus',
    why: 'Walmart\'s generic equivalent of Mucinex — same 600mg guaifenesin active ingredient but without the FD&C Blue No. 1 dye found in name-brand Mucinex. 5 clean inactive ingredients. Half the price of the brand.',
    honestNote: 'Drink plenty of water — guaifenesin works by thinning mucus, which requires hydration. Brand-name Mucinex has artificial dye; this generic does not.',
    retailers: ['Walmart'],
    priceTier: 'Standard',
  },
  {
    name: 'Tylenol Extra Strength Dye-Free',
    activeIngredient: 'Acetaminophen 500mg',
    classKey: 'acetaminophen',
    classTag: 'ACETAMINOPHEN',
    form: 'oral',
    subline: 'Cold-related fever, headache, body aches, sore throat pain',
    why: 'Single active ingredient, no artificial dyes. The cleanest mainstream adult acetaminophen widely available. Useful during a cold for fever and body aches without adding decongestants or cough suppressants you may not need.',
    honestNote: 'Stay under 4g/day total. Many multi-symptom cold products also contain acetaminophen — check all labels to avoid double-dosing.',
    retailers: ['CVS', 'Walgreens', 'Target', 'Grocery'],
    priceTier: 'Standard',
  },
  {
    name: 'Source Naturals Wellness Formula',
    activeIngredient: '30+ herbs, vitamins, minerals (Vitamin C, garlic, propolis, echinacea, elderberry)',
    classKey: 'immuneHerbal',
    classTag: 'IMMUNE BLEND',
    form: 'oral',
    subline: 'Immune support at first sign of illness, prevention during cold season',
    why: '35-year-old award-winning immune blend with high-potency Vitamin C, garlic, propolis, echinacea, elderberry, olive leaf, andrographis, and astragalus. Clean inactive ingredients: gelatin capsule, silica, magnesium stearate, dibasic calcium phosphate. Best taken at first sign of imbalance, not for active symptom treatment.',
    honestNote: 'Pregnancy warning — do not use if pregnant, may become pregnant, or breastfeeding. Contains iron — keep away from young children. Has soy from capsule.',
    retailers: ['Whole Foods', 'Sprouts', 'Walmart', 'Kroger'],
    priceTier: '$$ premium',
  },
  {
    name: "Beekeeper's Naturals Propolis Throat Spray",
    activeIngredient: 'Bee propolis extract 85mg',
    classKey: 'propolis',
    classTag: 'PROPOLIS',
    form: 'oral',
    subline: 'Sore throat, daily immune support, scratchy throat from talking or singing',
    why: 'Four ingredients: bee propolis extract, vegetable glycerin, purified water, wildflower honey. Genuinely one of the cleanest mainstream-available throat products. Propolis delivers over 300 bioactive compounds with antioxidant and immune-supporting properties.',
    honestNote: 'Bee allergy disclaimer: avoid if allergic to bees, bee products, poplar tree products, or balsam of Peru. Kids version available with slightly less propolis.',
    retailers: ['CVS', 'Whole Foods', 'Walmart', 'Sprouts'],
    priceTier: '$$ premium',
  },
  {
    name: 'Sambucol Black Elderberry Original Syrup',
    activeIngredient: 'Black elderberry extract (16,720mg per max serving)',
    classKey: 'elderberry',
    classTag: 'ELDERBERRY',
    form: 'oral',
    subline: 'Immune support, daily wellness, cold symptom relief',
    why: 'The original elderberry brand, scientifically studied since 1991. Premium European Haschberg black elderberries with proprietary extraction process. Just 5 ingredients: elderberry extract, glucose syrup, purified water, citric acid, potassium sorbate. Vegan, kosher, gluten-free.',
    honestNote: 'Contains glucose syrup as sweetener. Sugar-free version available with stevia for those avoiding sugar. Gummies version contains vegetable oil and is NOT recommended — stick with the syrup.',
    retailers: ['CVS', 'Walgreens', 'Walmart', 'Whole Foods', 'Sprouts'],
    priceTier: 'Standard',
  },
  {
    name: 'Boiron Coldcalm',
    activeIngredient: 'Multi-herb homeopathic blend (Allium cepa, Belladonna, Nux vomica, etc.)',
    classKey: 'homeopathic',
    classTag: 'HOMEOPATHIC',
    form: 'sublingual',
    subline: 'Sneezing, runny nose, nasal congestion, minor sore throat at cold onset',
    why: 'Meltaway tablets that dissolve under the tongue — no water needed. Gluten-free, no artificial sweeteners, flavors, colors, or preservatives. Phenylephrine-free. Non-drowsy and no known drug interactions. Recommended for ages 4+.',
    honestNote: 'Homeopathic preparation per FDA framework. Evidence base discussed in Carlston M (ed), Classical Homeopathy (Churchill Livingstone, 2003). Decide based on your own framework.',
    retailers: ['CVS', 'Walgreens', 'Whole Foods', 'Sprouts'],
    priceTier: 'Standard',
  },
  {
    name: "Boiron Chestal Honey Cough Syrup (Children's)",
    activeIngredient: 'Multi-herb homeopathic blend in honey base',
    classKey: 'homeopathic',
    classTag: 'HOMEOPATHIC · HONEY',
    form: 'oral',
    ageBadge: '👶 Ages 2+',
    subline: 'Kids · cough · chest congestion · throat irritation',
    why: 'Combines homeopathic cough remedies with real Acacia honey to soothe the throat. Dye-free, 99.9% alcohol-free children\'s version. Five clean inactive ingredients: citric acid, honey, purified water, sodium benzoate, sucrose. Won\'t mask symptoms of a more serious condition.',
    honestNote: 'Children\'s version is essentially alcohol-free. Adult version contains alcohol if you prefer to avoid it. Not recommended for children under 2 due to honey content.',
    retailers: ['CVS', 'Walgreens', 'Walmart'],
    priceTier: 'Standard',
  },
  {
    name: 'Boiron Oscillococcinum',
    activeIngredient: 'Anas barbariae 200CK HPUS',
    classKey: 'homeopathic',
    classTag: 'HOMEOPATHIC · 200CK',
    form: 'sublingual',
    subline: 'Flu-like symptoms — body aches, chills, fatigue, headache, fever',
    why: 'Drug-free pellets that melt under the tongue. Recommended at first sign of flu symptoms. Non-drowsy, no known drug interactions, recommended for ages 2+. Widely available at major drugstores.',
    honestNote: 'CRITICAL HONESTY: This is a 200CK dilution — far beyond Avogadro\'s number, meaning no measurable active ingredient remains. CVS\'s own product page notes "has not been proven safe or effective for these uses." Cochrane reviews have found insufficient evidence. Included here per our homeopathic-eligibility policy (Carlston, Classical Homeopathy, 2003), but users should know the dilution level before deciding.',
    retailers: ['CVS', 'Walgreens', 'Walmart', 'Whole Foods'],
    priceTier: 'Standard',
  },
  {
    name: 'Wedderspoon Organic Manuka Honey Drops',
    activeIngredient: 'Manuka honey + echinacea or propolis (varies by flavor)',
    classKey: 'propolis',
    classTag: 'HONEY LOZENGE',
    form: 'oral',
    subline: 'Dry throat, scratchy throat, mild cough — soothing lozenge',
    why: 'Real New Zealand Manuka honey with FernMark license for authenticity. Five organic ingredients per drop: cane sugar, manuka honey, brown rice syrup, ground ginger, echinacea. No artificial colors, flavors, or preservatives. USDA Organic and non-GMO.',
    honestNote: 'Each drop contains real cane sugar — moderate intake if you\'re managing blood sugar. Honey-based — not for kids under 12 months.',
    retailers: ['CVS', 'Whole Foods', 'Walmart', 'Walgreens', 'Kroger'],
    priceTier: '$$ premium',
  },
  {
    name: "Zarbee's Children's Cough Syrup + Immune",
    activeIngredient: 'Dark honey + ivy leaf + elderberry + zinc + chamomile',
    classKey: 'pediatricCombo',
    classTag: 'KIDS · HONEY-BASED',
    form: 'oral',
    ageBadge: '👶 Ages 2+',
    subline: 'Kids · cough · immune support · throat soothing',
    why: '#1 pediatrician-recommended children\'s cough brand. Drug-free formula uses dark honey to soothe coughs and ivy leaf extract to help clear mucus. Only 3 inactives: water, natural flavor, citric acid. No drugs, alcohol, dyes, gluten, artificial sweeteners, or high-fructose corn syrup.',
    honestNote: 'Honey-based — not for kids under 12 months. Daytime and nighttime versions available (nighttime adds chamomile for sleep support).',
    retailers: ['CVS', 'Walgreens', 'Target', 'Walmart', 'Grocery'],
    priceTier: 'Standard',
  },
];