// DRAFT / not verified / batch 127 KYR6-b Solaray Calcium Ascorbate close.
// Methodology v1.6. Sept 28, 2026 founder alias. Calcium Ascorbate is the ascorbic acid / vitamin C salt class. Cleared. Not a new grade.
// CoQ-10 Ubiquinol 30ct stays Avoid on Caramel Liquid and is not restamped.
// Parsley, bare vegetable/vegetarian capsule, and 3x/6x salts stay refused.
// batch70-batch126 were not edited. Solaray only. UPC stays empty. Liposomal Universal 076280830385 stays no_OI.
//
// TALLY: 1 row — Clean 1 / Caution 0 / Avoid 0.
// NEW 1 / REUSE 0 / SKIPPED no_OI leftover 1 / SKIPPED OUT 0 / REFUSED 111.

import type {
  IngredientFlag,
  RatingRecord,
} from '../ratingRecord';

const UNVERIFIED = 'unverified' as const;
const ADULT = 'adult' as const;
const SUPPLEMENT = 'Supplement' as const;
const UNVERIFIED_NOTE = 'draft, not verified';
const BRAND = 'Solaray';
const RETAILERS = ['Amazon', 'solaray.com'] as const;
const LIMITED_STACK =
  'Limited-only stack stays Caution (no 3-pt Avoid). Limited-only never Avoid. Avoid needs High.';
const UPC_BLANK =
  'No GTIN-12 was printed under the bars on the panel opened for Other Ingredients, so UPC is blank. Shopify barcodes that echo the SKU are not UPCs.';

const METH = {
  vegcap: "Methodology §5 Cleared (capsule cellulose / labeled veg cap).",
  ascorbic: "Methodology §5 Cleared (ascorbic acid / vitamin C salt). Calcium Ascorbate maps here (Sept 28, 2026). Not a new grade.",
} as const;

function flag(name: string, riskLevel: IngredientFlag['riskLevel'], source: string): IngredientFlag {
  return { name, riskLevel, source };
}
function labelCite(label: string, meth: string): string {
  return `${label}; ${meth}`;
}
function row(opts: Omit<RatingRecord, 'recordStatus'> & { recordStatus?: RatingRecord['recordStatus'] }): RatingRecord {
  return { ...opts, recordStatus: opts.recordStatus ?? UNVERIFIED };
}
type Compact = {
  id: string;
  productName: string;
  formulaId: string;
  form: string;
  actives: RatingRecord['activeIngredients'];
  flags: [string, IngredientFlag['riskLevel'], keyof typeof METH][];
  verdict: RatingRecord['verdict'];
  note: string;
  cite: string;
};
function expand(d: Compact): RatingRecord {
  return row({
    id: d.id,
    productName: d.productName,
    brand: BRAND,
    category: 'Vitamins',
    formulaId: d.formulaId,
    audience: ADULT,
    minAge: 18,
    form: d.form,
    productType: SUPPLEMENT,
    activeIngredients: d.actives,
    inactiveIngredients: d.flags.map(([n, risk, meth]) => flag(n, risk, labelCite(d.cite, METH[meth]))),
    verdict: d.verdict,
    honestNote: `${d.note} ${LIMITED_STACK} Pack sizes share formulaId \`${d.formulaId}\` when this OI list holds. Adults. No dosing or medical advice. Draft, not verified.`,
    retailers: [...RETAILERS],
    sourcesGeneral: [`${d.cite} — ${UNVERIFIED_NOTE}; no DailyMed drug SPL`],
  });
}

const COMPACT: Compact[] = [
  {
    id: "solaray-b127-076280282467",
    productName: "Solaray Activated Broccoli Seed Extract 350mg (30ct)",
    formulaId: "solaray-b127-076280282467",
    form: "capsule",
    actives: [
      { name: "Broccoli (Brassica oleracea italica) (seed extract)", strength: "350 mg" },
      { name: "Myrosinase Enzyme (Brassica oleracea italica)", strength: "13 mg" },
      { name: "Organic Freeze-Dried Broccoli Sprouts (Brassica oleracea italica)", strength: "50 mg" },
    ],
    flags: [
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Calcium Ascorbate", "cleared", "ascorbic"],
    ],
    verdict: "clean",
    note: "FOUNDER-LOCK DRAFT: Clean. Calcium Ascorbate is the ascorbic acid / vitamin C salt class. Every other ingredient on this panel maps to a Cleared family.",
    cite: "solaray.com supplement-facts image https://www.solaray.com/products/activated-broccoli-seed-extract other-ingredients: Vegetable Cellulose Capsule and Calcium Ascorbate. Token map: Vegetable Cellulose Capsule = Cleared. Calcium Ascorbate = Cleared Exact pack Solaray Activated Broccoli Seed Extract 350mg (30ct). SKU 076280282467. " + UPC_BLANK,
  },
];

export const BATCH127_KYR6B_SOLARAY_CA_ASCORBATE: RatingRecord[] = COMPACT.map(expand);

export const BATCH127_SKIPPED_NO_OI: { sku: string; name: string; count: string; why: string }[] = [
  {
    sku: '076280830385',
    name: 'Liposomal Multivitamin Universal',
    count: '60ct',
    why: 'Stays no_OI. This pass did not hunt it.',
  },
];

export const BATCH127_SKIPPED_OUT: { sku: string; name: string; why: string }[] = [];

export const BATCH127_HUNT_POUR: { name: string; url: string }[] = [
  { name: "Solaray D-Mannose With Cranactin Cranberry Extract Liquid", url: "https://www.solaray.com/products/d-mannose-with-cranactin-cranberry-extract-liquid" },
  { name: "Solaray Liquid Cranactin Cranberry Extract 315mg", url: "https://www.solaray.com/products/liquid-cranactin-cranberry-extract-bacterial-antiadherence-formula" },
  { name: "Solaray Turmeric Liquid Extract", url: "https://www.solaray.com/products/turmeric-liquid-extract" },
  { name: "Solaray Grapefruit Seed Extract 100mng", url: "https://www.solaray.com/products/copy-of-grapefruit-seed-extract-250mng" },
];

export const BATCH127_REFUSED: { sku: string; name: string; count: string; form: string; url: string; oi: string; blockers: string[] }[] = [
  {
    sku: "076280002607",
    name: "Kidney Blend SP-6",
    count: "100ct",
    form: "capsule",
    url: "https://www.solaray.com/products/kidney-blend-sp-6",
    oi: "Vegetable Cellulose Capsule and Trace Mineral Complex.",
    blockers: ["Parsley"],
  },
  {
    sku: "076280002775",
    name: "Menopause Blend SP-7D",
    count: "100 ct",
    form: "capsule",
    url: "https://www.solaray.com/products/menopause-blend-sp-7d",
    oi: "Vegetable Cellulose Capsule, Organic Rice Extract Blend, Calcium Phosphate 3x, Potassium Phosphate 3x, Silica 6x and Silica",
    blockers: ["Calcium Phosphate 3x", "Potassium Phosphate 3x", "Silica 6x"],
  },
  {
    sku: "076280002805",
    name: "Heart Blend SP-8",
    count: "100ct",
    form: "capsule",
    url: "https://www.solaray.com/products/heart-blend-sp-8",
    oi: "Vegetable Cellulose Capsule, Rice Flour, Calcium Fluoride 6x and Magnesium Phosphate 3x.",
    blockers: ["Calcium Fluoride 6x", "Magnesium Phosphate 3x"],
  },
  {
    sku: "076280008029",
    name: "Flaxseed Oil 1000mg",
    count: "100 ct",
    form: "",
    url: "https://www.solaray.com/products/flax",
    oi: "",
    blockers: ["no SKU-specific supplement-facts image that fully maps"],
  },
  {
    sku: "076280008074",
    name: "Flaxseed Oil 1000mg",
    count: "140 ct",
    form: "softgel",
    url: "https://www.solaray.com/products/flax",
    oi: "Gelatin (Bovine), Glycerin, Water, Carob, Rosemary Extract, Ascorbic Acid.",
    blockers: ["count conflict: Shopify variant title is 140 ct, but the SKU 076280008074 supplement-facts image is named 240ct and prints 80 servings x 3 softgels"],
  },
  {
    sku: "076280012101",
    name: "Dandelion Root 1040mg",
    count: "100ct",
    form: "capsule",
    url: "https://www.solaray.com/products/dandelion-root",
    oi: "Vegetable Cellulose Capsule, Magensium Stearate, and Rice Extract Blend.",
    blockers: ["OCR:Magensium Stearate"],
  },
  {
    sku: "076280012118",
    name: "Dandelion Root 1040mg",
    count: "180ct",
    form: "",
    url: "https://www.solaray.com/products/dandelion-root",
    oi: "",
    blockers: ["no SKU-specific supplement-facts image that fully maps"],
  },
  {
    sku: "076280021301",
    name: "Liver Blend Sp-13",
    count: "100ct",
    form: "",
    url: "https://www.solaray.com/products/liver-blend-sp-13",
    oi: "",
    blockers: ["no SKU-specific supplement-facts image that fully maps"],
  },
  {
    sku: "076280021608",
    name: "Prostate Blend Sp-16",
    count: "100ct",
    form: "capsule",
    url: "https://www.solaray.com/products/prostate-blend-sp-16",
    oi: "Vegetable Cellulose Capsule and Trace Mineral Complex.",
    blockers: ["Parsley"],
  },
  {
    sku: "076280023305",
    name: "Histamine Blend SP-33",
    count: "100ct",
    form: "capsule",
    url: "https://www.solaray.com/products/histamine-blend-sp-33",
    oi: "Magenesium Stereate, Vegetable Cellulose Capsule, Organic Rice Extract Blend, and Trace Mineral Complex.",
    blockers: ["Magenesium Stereate"],
  },
  {
    sku: "076280034202",
    name: "Feverfew Leaf Extract 400mg",
    count: "60ct",
    form: "capsule",
    url: "https://www.solaray.com/products/feverfew-leaf-extract",
    oi: "Vegetable Cellulose Capsule, Maltodextrin (from Non-GMO Corn) and Oraanic Rice Extract Blend.",
    blockers: ["OCR:Oraanic Rice Extract Blend"],
  },
  {
    sku: "076280036008",
    name: "Ginkgo Biloba Leaf Extract 60mg",
    count: "60ct",
    form: "",
    url: "https://www.solaray.com/products/ginkgo-biloba-leaf-extract",
    oi: "",
    blockers: ["no SKU-specific supplement-facts image that fully maps"],
  },
  {
    sku: "076280036039",
    name: "Ginkgo Biloba Extract, One Daily 120mg",
    count: "30ct",
    form: "",
    url: "https://www.solaray.com/products/ginkgo-biloba-extract-one-daily",
    oi: "",
    blockers: ["no SKU-specific supplement-facts image that fully maps"],
  },
  {
    sku: "076280037661",
    name: "Saw Palmetto & Pygeum with Zinc & Vitamin E",
    count: "30 ct",
    form: "",
    url: "https://www.solaray.com/products/pygeum-bark-saw-palmetto-ext",
    oi: "",
    blockers: ["no SKU-specific supplement-facts image that fully maps"],
  },
  {
    sku: "076280039054",
    name: "Valerian Root Extract 300mg",
    count: "30ct",
    form: "",
    url: "https://www.solaray.com/products/valerian-root-extract-one-daily",
    oi: "",
    blockers: ["no SKU-specific supplement-facts image that fully maps"],
  },
  {
    sku: "076280041026",
    name: "Astaxanthin",
    count: "Small (1 mg), Medium (4 mg) / Softgel",
    form: "",
    url: "https://www.solaray.com/products/astaxanthin",
    oi: "",
    blockers: ["no SKU-specific supplement-facts image that fully maps"],
  },
  {
    sku: "076280042405",
    name: "Mega Vitamin B-Stress, Timed-Release",
    count: "60ct",
    form: "capsule",
    url: "https://www.solaray.com/products/mega-vitamin-b-stress-timed-release",
    oi: "Cellulose, Vegetable Cellulose Capsule, Whole Food Base (Whole Rice Concentrate including the Bran, Polishings and Germ, and Pure Aloe Vera Gel), Magnesium Steartae, Silica, and Stearic Acid.",
    blockers: ["Magnesium Steartae"],
  },
  {
    sku: "076280042702",
    name: "Vitamin B-Complex 50mg",
    count: "50ct",
    form: "",
    url: "https://www.solaray.com/products/vitamin-b-complex-50",
    oi: "",
    blockers: ["no SKU-specific supplement-facts image that fully maps"],
  },
  {
    sku: "076280042726",
    name: "Vitamin B-Complex 50mg",
    count: "250ct",
    form: "",
    url: "https://www.solaray.com/products/vitamin-b-complex-50",
    oi: "",
    blockers: ["no SKU-specific supplement-facts image that fully maps"],
  },
  {
    sku: "076280043006",
    name: "Vitamin B-Complex 100",
    count: "50ct",
    form: "",
    url: "https://www.solaray.com/products/vitamin-b-complex-100",
    oi: "",
    blockers: ["no SKU-specific supplement-facts image that fully maps"],
  },
  {
    sku: "076280043013",
    name: "Vitamin B-Complex 100",
    count: "100ct",
    form: "",
    url: "https://www.solaray.com/products/vitamin-b-complex-100",
    oi: "",
    blockers: ["no SKU-specific supplement-facts image that fully maps"],
  },
  {
    sku: "076280043525",
    name: "Folic Acid (Vitamin B-9)",
    count: "",
    form: "capsule",
    url: "https://www.solaray.com/products/folic-acid-vitamin-b-9",
    oi: "Whole Rice Concentrate, Vegetable Cellulose Capsule and Aloe Vera Gel (200x dry concentrate).",
    blockers: ["no pack count or weight on the label opened for this SKU"],
  },
  {
    sku: "076280043594",
    name: "Niacin 100mg",
    count: "",
    form: "capsule",
    url: "https://www.solaray.com/products/niacin",
    oi: "Whole Rice Concentrate (Including Bran, Polishings, and Germ) Vegetable Cellulose Capsule and Aloe Vera Gel.",
    blockers: ["no pack count or weight on the label opened for this SKU"],
  },
  {
    sku: "076280043709",
    name: "Pantothenic Acid",
    count: "",
    form: "capsule",
    url: "https://www.solaray.com/products/pantothenic-acid-1",
    oi: "Gelatin Capsule, Whole Food Base (Whole Rice Concentrate including the Kernel, Polishings, and Hull, and Aloe Vera Gel) and Magnesium Stearate.",
    blockers: ["no pack count or weight on the label opened for this SKU"],
  },
  {
    sku: "076280045109",
    name: "Mega Multi Mineral",
    count: "100ct",
    form: "capsule",
    url: "https://www.solaray.com/products/multi-mineral",
    oi: "Gelatin Capsule, Cellulose, Magnesium Stearate, Parsley, Alfalfa Leaf, Horsetail, Watercress, Dandelion Root, Yellow Dock Root and Chamomile.",
    blockers: ["Parsley"],
  },
  {
    sku: "076280045116",
    name: "Mega Multi Mineral",
    count: "200ct",
    form: "capsule",
    url: "https://www.solaray.com/products/mega-multi-mineral",
    oi: "Gelatin Capsule, Cellulose, Magnesium Stearate, Parsley, Alfalfa Leaf,  Horsetail, Watercress, Dandelion Root, Yellow Dock Root and Chamomile.",
    blockers: ["Parsley"],
  },
  {
    sku: "076280045130",
    name: "Mega Multi Mineral, Iron-Free",
    count: "100ct",
    form: "capsule",
    url: "https://www.solaray.com/products/mega-multi-mineral-iron-free",
    oi: "Gelatin Capsule, Rice Protein, Citric Acid (from Non-GMO Tapioca),  Cellulose, Magnesium Stearate, Parsley Leaf, Alfalfa Leaf, Horsetail,  Watercress, Dandelion Root, Yellow Dock Root, Chamomile and Kelp.",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280045147",
    name: "Mega Multi Mineral, Iron-Free",
    count: "200ct",
    form: "capsule",
    url: "https://www.solaray.com/products/mega-multi-mineral-iron-free",
    oi: "Gelatin Capsule, Rice Protein, Citric Acid (from Non-GMO Tapioca), Cellulose, Magnesium Stearate, Parsley Leaf, Alfalfa Leaf, Horsetail, Watercress, Dandelion Root, Yellow Dock Root, Chamomile and Kelp.",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280045239",
    name: "Calcium & Magnesium Citrate With Vitamin D-2, 1:1",
    count: "90ct",
    form: "capsule",
    url: "https://www.solaray.com/products/calcium-magnesium-citrate-with-vitamin-d-2-1-1-ratio",
    oi: "Vegetable Cellulose Capsule, Magnesium Stearate, Parsley Leaf, Watercress, Alfalfa Leaf and Dandelion Root.",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280045246",
    name: "Calcium & Magnesium Citrate, 1:1 Ratio",
    count: "90ct",
    form: "capsule",
    url: "https://www.solaray.com/products/calcium-magnesium-citrate-1-1-ratio",
    oi: "Vegetable Cellulose Capsule, Magnesium Stearate, Parsley Leaf, Watercress Leaf, Alfalfa Leaf and Dandelion Root.",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280045253",
    name: "Calcium & Magnesium Citrate",
    count: "180ct",
    form: "capsule",
    url: "https://www.solaray.com/products/calcium-magnesium-citrate",
    oi: "Vegetable Cellulose Capsule, Magnesium Stearate, Parsley Leaf, Watercress Leaf, Alfalfa Leaf and Dandelion Root.",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280045260",
    name: "Calcium & Magnesium Citrate, With Vitamin D-2, 2:1 Ratio",
    count: "90ct",
    form: "capsule",
    url: "https://www.solaray.com/products/calcium-magnesium-citrate-with-vitamin-d-2-2-1-ratio",
    oi: "Vegetable Cellulose Capsule, Cellulose, Magnesium Stearate. Parslev Leaf. Alfalfa Leaf. Watercress Leaf and Dandelion Root.",
    blockers: ["OCR:Parslev Leaf"],
  },
  {
    sku: "076280045277",
    name: "Cal-Mag Citrate w/D-2, 2:1 Ratio",
    count: "180ct",
    form: "capsule",
    url: "https://www.solaray.com/products/cal-mag-citrate-w-d-2-2-1-ratio",
    oi: "Vegetable Cellulose Capsule, Cellulose, Magnesium Stearate, Parsley Leaf, Alfalfa Leaf, Watercress Leaf and Dandelion Root.",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280045291",
    name: "Calcium Citrate Supreme, Bone",
    count: "180ct",
    form: "capsule",
    url: "https://www.solaray.com/products/calcium-citrate-supreme-bone",
    oi: "Gelatin Capsule, Magnesium Stearate, Whole Rice Concentrate (including Kernel, Polishings, and Hull), Cellulose, Citric Acid, Lysine, Aspartic Acid, Glycine, Alfalfa Leaf, Watercress, Dandelion Root and Parsley Leaf.",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280045307",
    name: "Calcium & Magnesium, AAC 2:1",
    count: "90ct",
    form: "",
    url: "https://www.solaray.com/products/calcium-magnesium-amino-acid-chelate-2-1-ratio",
    oi: "",
    blockers: ["Parsley Aerial"],
  },
  {
    sku: "076280045314",
    name: "Calcium & Magnesium, AAC 2:1",
    count: "180ct",
    form: "capsule",
    url: "https://www.solaray.com/products/calcium-magnesium-amino-acid-chelate-2-1-ratio",
    oi: "Vegetable Cellulose Capsule, Cellulose, Citric Acid (from Non-GMO Tapioca), L-Aspartic Acid, Magnesium Stearate, Whole Rice Concentrate, Rice Protein, Alfalfa Aerial, Dandelion Root, Watercress Leaf and Parsley Aerial.",
    blockers: ["Parsley Aerial"],
  },
  {
    sku: "076280045345",
    name: "Calcium & Magnesium Amino Acid",
    count: "90ct",
    form: "capsule",
    url: "https://www.solaray.com/products/calcium-magnesium-amino-acid",
    oi: "Gelatin Capsule, Cellulose, Whole Rice Concentrate, Rice Protein, Magnesium Stearate, Silica, Alfalfa Leaf, Watercress Leaf, Dandelion Root and Parsley Herb.",
    blockers: ["Parsley Herb"],
  },
  {
    sku: "076280045604",
    name: "Calcium, Magnesium, Zinc",
    count: "100ct",
    form: "capsule",
    url: "https://www.solaray.com/products/calcium-magnesium-zinc",
    oi: "Vegetable Cellulose Capsule, Magnesium Stearate, Whole Rice Concentrate (including the Bran, Polishings and Germ), Alfalfa Leaf, Watercress, Dandelion Root and Parsley Leaf.",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280045611",
    name: "Calcium, Magnesium, Zinc",
    count: "250ct",
    form: "capsule",
    url: "https://www.solaray.com/products/calcium-magnesium-zinc",
    oi: "Vegetable Cellulose Capsule, Magnesium Stearate, Whole Rice Concentrate (including the Bran, Polishings and Germ), Alfalfa leaf, Watercress, Dandelion Root and Parsley Leaf.",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280045772",
    name: "Boron Citrate 3mg",
    count: "60ct",
    form: "",
    url: "https://www.solaray.com/products/boron-citrate",
    oi: "",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280045833",
    name: "Calcium Citrate With Vitamin D-3 1000mg",
    count: "90ct",
    form: "capsule",
    url: "https://www.solaray.com/products/calcium-citrate-with-vitamin-d-3",
    oi: "Gelatin Capsule, Magnesium Stearate, Watercress Leaf, Dandelion Root and Parsley Leaf.",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280045857",
    name: "Calcium Citrate 1000mg",
    count: "120ct",
    form: "capsule",
    url: "https://www.solaray.com/products/calcium-citrate",
    oi: "Vegetable Cellulose Capsule, Magnesium Stearate, Watercress Leaf, Dandelion Root and Parsley Leaf.",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280045918",
    name: "GTF Chromium 200mcg",
    count: "200ct",
    form: "",
    url: "https://www.solaray.com/products/gtf-chromium",
    oi: "",
    blockers: ["Brewer"],
  },
  {
    sku: "076280046007",
    name: "Iron Asporotate 18mg",
    count: "100ct",
    form: "capsule",
    url: "https://www.solaray.com/products/iron-asporotate",
    oi: "Yellowdock Root, Parsley Herb, Gelatin Capsule, Whole Rice Concentrate, Magnesium Oxide and Magnesium Stearate.",
    blockers: ["Parsley Herb"],
  },
  {
    sku: "076280046205",
    name: "Magnesium Asporotate 400mg",
    count: "60ct",
    form: "capsule",
    url: "https://www.solaray.com/products/magnesium-asporotate",
    oi: "Vegetable Cellulose Capsule, Magnesium Stearate, Rice Flour and Herb Base (Parsley Leaf, Alfalfa Leaf)",
    blockers: ["Herb Base (Parsley Leaf, Alfalfa Leaf)"],
  },
  {
    sku: "076280046212",
    name: "Magnesium Asporotate 400mg",
    count: "120ct",
    form: "capsule",
    url: "https://www.solaray.com/products/magnesium-asporotate",
    oi: "Vegetable Cellulose Capsule, Magnesium Stearate, Rice Flour and Herb Base (Parsley Leaf, Organic Alfalfa Leaf).",
    blockers: ["Herb Base (Parsley Leaf, Organic Alfalfa Leaf)"],
  },
  {
    sku: "076280046304",
    name: "Magnesium, Amino Acid Chelate 200mg",
    count: "100ct",
    form: "capsule",
    url: "https://www.solaray.com/products/magnesium-amino-acid-chelate",
    oi: "Vegetable Cellulose Capsule, Magnesium Stearate, Organic Alfalfa, Parsley, and Citric Acid.",
    blockers: ["Parsley"],
  },
  {
    sku: "076280046502",
    name: "Manganese 50mg",
    count: "100ct",
    form: "capsule",
    url: "https://www.solaray.com/products/manganese",
    oi: "Whole Food Base (Whole Rice Concentrate including Bran, Germ and Polishings), Vegetable Cellulose Capsule, Magnesium Stearate, Rice Flour, Watercress and Parsley Leaf.",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280046601",
    name: "Potassium Asporotate 99mg",
    count: "100ct",
    form: "capsule",
    url: "https://www.solaray.com/products/potassium-asporotate",
    oi: "Gelatin Capsule, Herb Base (Parsley Leaf, Chamomile, Watercress) and Magnesium Stearate.",
    blockers: ["Herb Base (Parsley Leaf, Chamomile, Watercress)"],
  },
  {
    sku: "076280046618",
    name: "Potassium Asporotate 99mg",
    count: "200ct",
    form: "",
    url: "https://www.solaray.com/products/potassium-asporotate",
    oi: "",
    blockers: ["Herb Base (Parsley Leaf, Chamomile, Watercress)"],
  },
  {
    sku: "076280046700",
    name: "Potassium 99mg",
    count: "100ct",
    form: "capsule",
    url: "https://www.solaray.com/products/potassium-99",
    oi: "Vegetable Cellulose Capsule, Rice Flour, Citric Acid, Magnesium Stearate, Parsley, Chamomile and Watercress.",
    blockers: ["Parsley"],
  },
  {
    sku: "076280046717",
    name: "Potassium 99mg",
    count: "200ct",
    form: "",
    url: "https://www.solaray.com/products/potassium-99",
    oi: "",
    blockers: ["Parsley"],
  },
  {
    sku: "076280047073",
    name: "OptiZinc 30mg",
    count: "60 ct",
    form: "capsule",
    url: "https://www.solaray.com/products/optizinc",
    oi: "Whole Rice Concentrate (including bran, polishing and germ), Vegetable Cellulose Capsule, Kelp and Magnesium Stearate. ony — ae OptiZinc OptiZinc® is a Lonza trademark, registered in the USA.",
    blockers: ["ony — ae OptiZinc OptiZinc is a Lonza trademark", "registered in the USA"],
  },
  {
    sku: "076280047455",
    name: "Twice Daily Multi Vitamin",
    count: "",
    form: "capsule",
    url: "https://www.solaray.com/products/twice-daily-multi-vitamin",
    oi: "Gelatin Capsule, Eleuthero Root, Cellulose, Magnesium Stearate, Sodium Alginate, Silica, Whole Rice Concentrate (including Bran, Polishings and Germ), Carrot Juice Powder and oybean Oil.",
    blockers: ["Carrot Juice Powder", "oybean Oil"],
  },
  {
    sku: "076280047813",
    name: "Spectro Multivitamin",
    count: "100ct",
    form: "capsule",
    url: "https://www.solaray.com/products/spectro-multi-vitamin",
    oi: "Gelatin Capsule, Eleuthero Root, Magnesium Stearate, Stearic Acid, Cellulose, Maltodextrin, Whole Rice Concentrate, Alfalfa Leaf, Montmorillonite Clay, Rose Hips and Acerola Cherry.",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280047820",
    name: "Spectro Multivitamin",
    count: "250ct",
    form: "capsule",
    url: "https://www.solaray.com/products/spectro-multi-vitamin",
    oi: "Gelatin Capsule, Eleuthero Root, Magnesium Stearate, Stearic Acid, Cellulose, Maltodextrin, Whole Rice Concentrate, Alfalfa Leaf, Montmorillonite Clay, Rose Hips and Acerola Cherry.",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280047837",
    name: "Spectro Multivitamin",
    count: "360ct",
    form: "capsule",
    url: "https://www.solaray.com/products/spectro-multi-vitamin",
    oi: "Gelatin Capsule, Eleuthero Root, Magnesium Stearate, Stearic Acid, Cellulose, Maltodextrin, Whole Rice Concentrate, Alfalfa Leaf, Montmorillonite Clay, Rose Hips and Acerola Cherry.",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280047851",
    name: "Spectro Multivitamin, Iron-Free",
    count: "250ct",
    form: "capsule",
    url: "https://www.solaray.com/products/spectro-multi-vitamin-iron-free",
    oi: "Gelatin Capsule, Eleuthero Root, Magnesium Stearate, Cellulose, Stearic Acid, Maltodextrin, Whole Rice Concentrate, Alfalfa Leaf, Montmorillonite Clay, Rose Hips and Acerola Cherry.",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280047905",
    name: "Hair Nutrients",
    count: "60ct",
    form: "capsule",
    url: "https://www.solaray.com/products/hair-nutrients",
    oi: "Vegetable Cellulose Capsule, Rice Flour, Cellulose, Croscarmellose Sodium, Silica, Magnesium Stearate, Alfalfa Leaf, Parsley Leaf and Watercress Leaf.",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280047912",
    name: "Hair Nutrients",
    count: "120ct",
    form: "",
    url: "https://www.solaray.com/products/hair-nutrients",
    oi: "",
    blockers: ["Rice Flours Magnesium Stearate", "Parsley Leaf"],
  },
  {
    sku: "076280047967",
    name: "Children",
    count: "60ct",
    form: "chewable",
    url: "https://www.solaray.com/products/childrens-multi-vitamin",
    oi: "Sorbitol, Fructose, Natural Cherry Flavor with Other Natural Calories 5 Flavors, Hydrogenated Soybean Oil, Magnesium Stearate, Silica, Glucono Delta TotalCarbohydrate=00SO—~=~<“—=s~—i—‘“s—s~sSQS*é<‘(‘OS™CSOCSC‘tESOC*«sG Lactone, Mono- and Diglycerides, Stearic Acid, Rose Hips, and Acerola Cherry. eee Vitamin A (as Beta Carotene) 1,500 mcg 167% 500% Vitamin C (as Ascorbic Acid) 150 mg 167% 1,000% Vitamin D (as Cholecalciferol) (D-3) 25 mcg 125% 167%  (Supplying 1,000 IU of Vitamin D) Vitamin E (as d-Alpha Tocopheryl Acetate) 20mg 133% 333%  (Supplying 30 IU of Vitamin E) Thiamine (from Thiamine Mononitrate) (B-1) 5 mg 417% 1,000% Riboflavin (Vitamin B-2) 5mg 385% 1,000% Niacin (as Niacinamide) 16 mg 100% 267% Vitamin B-6 (from Pyridoxine HCl) 5 mg 294% 1,000% Folate 680 mcg DFE 170% 453%  (400 mcg Folic Acid)  Vitamin B-12 (as Cyanocobalamin) 10 meg 417% 1,111% Biotin 100 mcg 333% 1,250% Pantothenic Acid (as Calcium d-Pantothenate) 16 mg 320% 800% Choline (from Choline Bitartrate) 2mg <1% 1% Calcium (from Oyster Shell) 30 mg 2% 4% Iron (from Ferrous Fumate) 6 mg 33% 86% lodine (from Kelp) 100 mcg 67% 111% Magnesium (from Magnesium Oxide) 15 mg 4% 19% Zinc (from Zinc Carbonate) 2mg 18% 67% Manganese (from Manganese Carbonate) 2mg 87% 167%",
    blockers: ["Glucono Delta TotalCarbohydrate=00SO—~=~<“—=s~—i—'“s—s~sSQS*é<'('OSCSOCSC'tESOC*«sG Lactone, Monoand Diglycerides, Stearic Acid, Rose Hips, and Acerola Cherry. eee Vitamin A (as Beta Carotene) 1,500 mcg 167% 500% Vitamin C (as Ascorbic Acid) 150 mg 167% 1,000% Vitamin D (as Cholecalciferol) (D-3) 25 mcg 125% 167% (Supplying 1,000 IU of Vitamin D) Vitamin E (as d-Alpha Tocopheryl Acetate) 20mg 133% 333% (Supplying 30 IU of Vitamin E) Thiamine (from Thiamine Mononitrate) (B-1) 5 mg 417% 1,000% Riboflavin (Vitamin B-2) 5mg 385% 1,000% Niacin (as Niacinamide) 16 mg 100% 267% Vitamin B-6 (from Pyridoxine HCl) 5 mg 294% 1,000% Folate 680 mcg DFE 170% 453% (400 mcg Folic Acid) Vitamin B-12 (as Cyanocobalamin) 10 meg 417% 1,111% Biotin 100 mcg 333% 1,250% Pantothenic Acid (as Calcium d-Pantothenate) 16 mg 320% 800% Choline (from Choline Bitartrate) 2mg <1% 1% Calcium (from Oyster Shell) 30 mg 2% 4% Iron (from Ferrous Fumate) 6 mg 33% 86% lodine (from Kelp) 100 mcg 67% 111% Magnesium (from Magnesium Oxide) 15 mg 4% 19% Zinc (from Zinc Carbonate) 2mg 18% 67% Manganese (from Manganese Carbonate) 2mg 87% 167%"],
  },
  {
    sku: "076280051001",
    name: "Adrenal Caps",
    count: "60 ct",
    form: "capsule",
    url: "https://www.solaray.com/products/adrenal-caps-freeze-dried-raw-gland-concentrate",
    oi: "Vegetable Cellulose Capsule, Calcium Phosphate 3x, Iron Pyrophosphate, Potassium Phosphate 3x and Sodium Chloride 6x.",
    blockers: ["Calcium Phosphate 3x", "Potassium Phosphate 3x", "Sodium Chloride 6x"],
  },
  {
    sku: "076280082524",
    name: "Oil Of Oregano 150mg",
    count: "60ct",
    form: "softgel",
    url: "https://www.solaray.com/products/oil-of-oregano",
    oi: "Softgel (Non-GMO Tapioca Starch, Non-GMO Glycerin and Water) and live Oil.",
    blockers: ["OCR:live Oil"],
  },
  {
    sku: "076280083323",
    name: "MigraGard 400mg",
    count: "60ct",
    form: "capsule",
    url: "https://www.solaray.com/products/migragard",
    oi: "Vegetable Cellulose Capsule and Feverfew (Tanacetum 7 parthenium) (aerial), Maltodextrin (from Non-GMO Corn) and Organic Rice Extract Blend.",
    blockers: ["Feverfew (Tanacetum 7 parthenium) (aerial)"],
  },
  {
    sku: "076280084269",
    name: "Continence with Flowtrol",
    count: "60ct",
    form: "capsule",
    url: "https://www.solaray.com/products/continence-with-flowtrol",
    oi: "Vegetable Cellulose Capsule, Maltodextrin, Cellulose, Calcium Phosphate, Magensium Stearate, Silica and Magnesium Hydroxide.",
    blockers: ["OCR:Magensium Stearate"],
  },
  {
    sku: "076280088618",
    name: "Total Calm, Mood Support",
    count: "30ct",
    form: "capsule",
    url: "https://www.solaray.com/products/total-calm-mood-support",
    oi: "Modified Food and Corn Starch, Vegetable Cellulose Capsule, Cellulose, Silica and Magnesium Stearate.",
    blockers: ["OCR:Modified Food"],
  },
  {
    sku: "076280103489",
    name: "Resveratrol, Japanese Knotweed 75mg",
    count: "60ct",
    form: "capsule",
    url: "https://www.solaray.com/products/resveratrol-japanese-knotweed",
    oi: "Cellulose, Vegetable Cellulose Capsule, Organic Rice Extract Blend, Silica and Maltodex- trin (from Non-GMO Corn).",
    blockers: ["OCR:Maltodex- trin (from Non-GMO Corn)"],
  },
  {
    sku: "076280110098",
    name: "HMB + Vitamin D3",
    count: "Vanilla",
    form: "powder",
    url: "https://www.solaray.com/products/hmb-vitamin-d3",
    oi: "Natural Vanilla Flavor with Other Natural Flavors, Sea Salt, Steviol Glycoside, and Silica. myHMB? is a registered trademark of TSI Group Co., Ltd. US Patent #8,815,280 #9,539,224 #9,707,241",
    blockers: ["no pack count or weight on the label opened for this SKU"],
  },
  {
    sku: "076280121094",
    name: "Biocitrate Potassium 99mg",
    count: "60ct",
    form: "capsule",
    url: "https://www.solaray.com/products/biocitrate-potassium",
    oi: "Rice Flour, Vegetable Cellulose Capsule, Parsley Leaf, Celery Seed, Dandelion Root, Magnesium Stearate, Watercress Leaf and Oat Straw Stem.",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280127430",
    name: "Vitamin B-6, Timed-Release",
    count: "120ct / 100 mg",
    form: "",
    url: "https://www.solaray.com/products/vitamin-b-6-timed-release",
    oi: "",
    blockers: ["no SKU-specific supplement-facts image that fully maps"],
  },
  {
    sku: "076280130645",
    name: "Acetyl L-Carnitine 500mg",
    count: "30ct",
    form: "",
    url: "https://www.solaray.com/products/acetyl-l-carnitine",
    oi: "",
    blockers: ["no SKU-specific supplement-facts image that fully maps"],
  },
  {
    sku: "076280131758",
    name: "Cal-Mag Citrate w/D-2, 2:1 Ratio",
    count: "360ct",
    form: "capsule",
    url: "https://www.solaray.com/products/cal-mag-citrate-w-d-2-2-1-ratio",
    oi: "Vegetable Cellulose Capsule, Cellulose, Magnesium Stearate, Parsley  Leaf, Alfalfa Leaf, Watercress Leaf and Dandelion Root.",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280131765",
    name: "Calcium Citrate With Vitamin D-3 1000mg",
    count: "240ct",
    form: "capsule",
    url: "https://www.solaray.com/products/calcium-citrate-with-vitamin-d-3",
    oi: "Gelatin Capsule, Magnesium Stearate, Watercress Leaf, Dandelion Root and Parsley Leaf. Discussion: Calcium is intended to support healthy bones and teeth. A speical base of herbs has been included for additional nutritive support.*",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280132236",
    name: "Magnesium Asporotate 400mg",
    count: "180ct",
    form: "capsule",
    url: "https://www.solaray.com/products/magnesium-asporotate",
    oi: "Vegetable Cellulose Capsule, Magnesium Stearate, Rice Flour and Herb Base (Parsley Leaf, Organic Alfalfa Leaf).",
    blockers: ["Herb Base (Parsley Leaf, Organic Alfalfa Leaf)"],
  },
  {
    sku: "076280149074",
    name: "Vegan Collagen Booster",
    count: "",
    form: "powder",
    url: "https://www.solaray.com/products/vegan-collagen-booster",
    oi: "Natural Vanilla Flavor with Other Natural Flavors, Sea Salt, Gotu Kola (Centella asiatica) (extract), Steviol Glycoside, Silica, Ginseng (Panax ginseng) (root extract).",
    blockers: ["no pack count or weight on the label opened for this SKU"],
  },
  {
    sku: "076280223149",
    name: "Triple Strength Tart Cherry Fruit Extract",
    count: "90ct",
    form: "capsule",
    url: "https://www.solaray.com/products/triple-strength-tart-cherry-fruit-extract",
    oi: "Maltodextrin (from Non-GMO Corn), Cellulose, Vegetable Cellulose Capsule. Silica and Oraanic Rice Extract Blend.",
    blockers: ["OCR:Oraanic Rice Extract Blend"],
  },
  {
    sku: "076280228786",
    name: "Cal-Mag Citrate Vitamin with D-2, 1:3",
    count: "180ct",
    form: "capsule",
    url: "https://www.solaray.com/products/cal-mag-citrate-with-d-2-1-3",
    oi: "Vegetable Cellulose Capsule, Magnesium Stearate, Parsley Leaf, Watercress Leaf, Alfalfa Leaf and Dandelion Root.",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280229639",
    name: "ProSorb Turmeric 29x 500mg",
    count: "30 ct",
    form: "capsule",
    url: "https://www.solaray.com/products/prosorb-turmeric-29x-500mg",
    oi: "Cellulose, Sunflower Lecithin, Vegetable Capsule, Magnesium Stearate, Silica.",
    blockers: ["Vegetable Capsule"],
  },
  {
    sku: "076280329568",
    name: "Plant Melatonin",
    count: "",
    form: "capsule",
    url: "https://www.solaray.com/products/plant-melatonin",
    oi: "Cellulose, Vegetable Cellulose Capsule, Tapioca Dextrin, Stearic Acid, and Silica.  SOMATO® is a trademark of Nutraland USA, Inc.",
    blockers: ["no pack count or weight on the label opened for this SKU"],
  },
  {
    sku: "076280342987",
    name: "Methyl B-12 - Cherry",
    count: "60ct / Natural Cherry",
    form: "lozenge",
    url: "https://www.solaray.com/products/methyl-b-14",
    oi: "Xylitol Organic Inulin, Citric Acid (from Non-GMO Tapioca), Silica, Natural Cherry Flavor with other Natural Flavors and Stearic Acid.",
    blockers: ["Xylitol Organic Inulin"],
  },
  {
    sku: "076280360448",
    name: "Her Life Stages Libido",
    count: "60 ct",
    form: "capsule",
    url: "https://www.solaray.com/products/her-life-stages-libido",
    oi: "Cellulose, Vegetable Capsule, Stearic Acid, and Silica.  KSM-66 Ashwagandha? is a registered trademark of Ixoreal Biomed Inc.",
    blockers: ["Vegetable Capsule"],
  },
  {
    sku: "076280361537",
    name: "Vitamin K-2, MK-7 50mcg",
    count: "30ct",
    form: "capsule",
    url: "https://www.solaray.com/products/vitamin-k-2-mk-7",
    oi: "Cellulose, Vegetable Cellulose Capsule, Glycerol Monostearate, Magnesium stearate, Fermented Defatted Chickpea Flour Extract, Organic Rice Extract lend and Silica.",
    blockers: ["Organic Rice Extract lend"],
  },
  {
    sku: "076280374025",
    name: "Magnesium Citrate 400mg",
    count: "180ct",
    form: "",
    url: "https://www.solaray.com/products/magnesium-citrate",
    oi: "",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280458350",
    name: "Calcium Citrate With Vitamin D-3 1000mg",
    count: "180ct",
    form: "capsule",
    url: "https://www.solaray.com/products/calcium-citrate-with-vitamin-d-3",
    oi: "Gelatin Capsule, Magnesium Stearate, Watercress Leaf, Dandelion Root and Parsley Leaf.",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280458527",
    name: "Calcium Citrate 1000mg",
    count: "240ct",
    form: "capsule",
    url: "https://www.solaray.com/products/calcium-citrate",
    oi: "Vegetable Cellulose Capsule, Magnesium Stearate,  Watercress Leaf, Dandelion Root and Parsley Leaf.",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280461053",
    name: "Iron 50mg",
    count: "60ct",
    form: "capsule",
    url: "https://www.solaray.com/products/iron",
    oi: "Herbal Base (Parsley, Rice Flour, Yellow Dock Root), Vegetable Cellulose Capsule and Ascorbyl Palmitate.",
    blockers: ["Herbal Base (Parsley, Rice Flour, Yellow Dock Root)"],
  },
  {
    sku: "076280463019",
    name: "Magnesium Citrate 400mg",
    count: "90ct",
    form: "capsule",
    url: "https://www.solaray.com/products/magnesium-citrate",
    oi: "Vegetable Cellulose Capsule, Cellulose, Magnesium Stearate, Arabic  Gum, Watercress Leaf, Dandelion Root, Alfalfa Leaf and Parsley Leaf.  Aquamin® is a registered trademark of Marigot Ltd. of Cork Ireland.",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280469363",
    name: "Her Life Stages Menopause",
    count: "60 ct",
    form: "capsule",
    url: "https://www.solaray.com/products/her-life-stages-menopause",
    oi: "Cellulose, Vegetable Capsule, Stearic Acid, Silica.",
    blockers: ["Vegetable Capsule"],
  },
  {
    sku: "076280474848",
    name: "Biocitrate Strontium 250mg",
    count: "60 ct",
    form: "capsule",
    url: "https://www.solaray.com/products/biocitrate-strontium",
    oi: "Vegetable Cellulose Capsule, Alfalfa Leaf, Parsley Leaf, Magnesium Stearate and Kelp.",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280478556",
    name: "Spectro Multivitamin, Iron-Free",
    count: "360ct",
    form: "capsule",
    url: "https://www.solaray.com/products/spectro-multi-vitamin-iron-free-1",
    oi: "Gelatin Capsule, Eleuthero Root, Magnesium Stearate, Cellulose, Stearic Acid, Maltodextrin, Whole Rice Concentrate, Alfalfa Leaf, Montmorillonite Clay, Rose Hips and Acerola Cherry.",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280529586",
    name: "Colostrum+",
    count: "Unflavored",
    form: "powder",
    url: "https://www.solaray.com/products/colostrum",
    oi: "Acacia Gum and Sea Salt.  Contains: Milk.  Immunell™ is a trademark of Nexira.",
    blockers: ["no pack count or weight on the label opened for this SKU"],
  },
  {
    sku: "076280582505",
    name: "Colostrum+",
    count: "Peach Mango",
    form: "powder",
    url: "https://www.solaray.com/products/colostrum",
    oi: "Natural Peach and Mango Flavors with Other Natural Flavors, Citric  Acid, Acacia Gum, and Stevia (leaf extract).  Contains: Milk.  Immunell™ is a trademark of Nexira.",
    blockers: ["no pack count or weight on the label opened for this SKU"],
  },
  {
    sku: "076280595499",
    name: "NADH",
    count: "",
    form: "capsule",
    url: "https://www.solaray.com/products/nadh",
    oi: "Cellulose, Vegetable Cellulose Capsule, Fractionated Palm Oil, Beeswax, Chlorophyllin, Stearic Acid, and Silica. PANMOL?® is a registered trademark of vis vitalis gmbh.",
    blockers: ["no pack count or weight on the label opened for this SKU"],
  },
  {
    sku: "076280598933",
    name: "Aged Black Garlic",
    count: "",
    form: "capsule",
    url: "https://www.solaray.com/products/aged-black-garlic",
    oi: "Vegetable Cellulose Capsule, Acacia Gum, Cellulose, and Silica, Garlzac® is a registered trademark of Olene Life Sciences.",
    blockers: ["no pack count or weight on the label opened for this SKU"],
  },
  {
    sku: "076280600438",
    name: "Mushroom Herb Complex",
    count: "90ct",
    form: "capsule",
    url: "https://www.solaray.com/products/mushroom-complete-8",
    oi: "Vegetarian Capsule, Cellulose, Magnesium Stearate and Silica.",
    blockers: ["Vegetarian Capsule"],
  },
  {
    sku: "076280616903",
    name: "Liposomal Multivitamin Women",
    count: "60ct",
    form: "capsule",
    url: "https://www.solaray.com/products/liposomal-multivitamin-womens-50",
    oi: "Cellulose, Hpie Blend from Sunflower Oil and Sus- tainable Palm Oil, Vegetable Cellulose Capsule, Stearic Acid, Modified Tapioca Starch, Magnesium Stearate, Silica, Glycerol Monostearate, Sodium Alginate, Pea Starch, Tapioca Starch.",
    blockers: ["Hpie Blend from Sunflower Oil"],
  },
  {
    sku: "076280644753",
    name: "Super Forskohlii Root Extract 400mg",
    count: "60ct",
    form: "",
    url: "https://www.solaray.com/products/super-forskohlii-root-exract",
    oi: "",
    blockers: ["Vegetarian Capsule"],
  },
  {
    sku: "076280648843",
    name: "Cal-Mag Citrate w/D-3 & K-2, 2:1 Ratio",
    count: "180ct",
    form: "",
    url: "https://www.solaray.com/products/cal-mag-citrate-w-d-3-k-2",
    oi: "",
    blockers: ["no SKU-specific supplement-facts image that fully maps"],
  },
  {
    sku: "076280675559",
    name: "Her Life Stages Postmenopause",
    count: "60 ct",
    form: "capsule",
    url: "https://www.solaray.com/products/her-life-stages-postmenopause",
    oi: "Maltodextrin (from Non-GMO Corn), Cellulose, Vegetable Capsule, Stearic Acid, Silica.  Chromax® is a registered trademark of Nutrition 21, LLC. Chromax® is patent protected.  Morosil® is a trademark of BIONAP S.r.l.  Veri-te® is a registered trademark of Lallemand Group.  Affron® and Lepticrosalides® are registered trademarks of Pharmactive Biotech Products, $.L.U.",
    blockers: ["Vegetable Capsule"],
  },
  {
    sku: "076280728507",
    name: "Liposomal Glutathione",
    count: "",
    form: "capsule",
    url: "https://www.solaray.com/products/liposomal-glutathione",
    oi: "Cellulose, Vegetable Cellulose Capsule, Sunflower Phospholipids, Stearic Acid, and Silica.",
    blockers: ["no pack count or weight on the label opened for this SKU"],
  },
  {
    sku: "076280773279",
    name: "ProSorb Berberine 9x 550mg",
    count: "30 ct",
    form: "capsule",
    url: "https://www.solaray.com/products/prosorb-berberine-9x",
    oi: "Cellulose, Pea Protein Isolate, Vegetable Capsule, Sunflower Lecithin, Grape Seed Extract, Stearic Acid, Silica.",
    blockers: ["Vegetable Capsule"],
  },
  {
    sku: "076280788020",
    name: "Spermidine",
    count: "",
    form: "capsule",
    url: "https://www.solaray.com/products/spermidine",
    oi: "Tapioca Dextrin, Cellulose, Vegetable Cellulose Capsule, Citric Acid, and Silica. Miricell™ is a trademark of Nutraland USA, Inc.",
    blockers: ["no pack count or weight on the label opened for this SKU"],
  },
  {
    sku: "076280882896",
    name: "Liposomal Multivitamin Men's",
    count: "60ct",
    form: "capsule",
    url: "https://www.solaray.com/products/liposomal-multivitamin-mens",
    oi: "Cellulose, Lipid Blend from Sunflower Oil and Sustainable Palm Oil, Vegetable Cellulose Capsule, Magnesium Stearate, Modified Tapioca Starch, Silica, Sodium Alginate, Pea Starch and Gum rabic.",
    blockers: ["OCR:Gum rabic"],
  },
  {
    sku: "076280884500",
    name: "Calcium & Magnesium Citrate W/ Vitamin D-3, 2:1 Ratio",
    count: "180ct",
    form: "capsule",
    url: "https://www.solaray.com/products/calcium-magnesium-citrate-w-vitamin-d-3-2-1-ratio",
    oi: "Gelatin Capsule, Cellulose, Magnesium Stearate, Parsley Leaf, Alfalfa Leaf, Watercress Leaf and Dandelion Root.",
    blockers: ["Parsley Leaf"],
  },
  {
    sku: "076280886757",
    name: "Opti-5 Magnesium",
    count: "",
    form: "capsule",
    url: "https://www.solaray.com/products/opti-5-magnesium",
    oi: "Vegetable Cellulose Capsule, Arabic Gum, and Cellulose.  Aquamin® is a registered trademark of Marigot Ltd. of Cork Ireland,  GivoMag™ is a trademark of Isaltis.",
    blockers: ["no pack count or weight on the label opened for this SKU"],
  },
  {
    sku: "076280903522",
    name: "Curcumin Root Extract 250mg",
    count: "30 ct",
    form: "softgel",
    url: "https://www.solaray.com/products/curcumin-root-extract",
    oi: "Medium Chain tiobycendes (coconut), Softgel (Gelatin and Glycerin), Lecithin (soy), Yellow Beeswax and Sunflower Oil.",
    blockers: ["Medium Chain tiobycendes (coconut)"],
  },
  {
    sku: "076280937145",
    name: "Nattokinase and Serrapeptase",
    count: "",
    form: "capsule",
    url: "https://www.solaray.com/products/solaray-nattokinase-serrapeptase-supplement-3-000-fu-healthy-circulation-blood-flow-support-30-vegcaps",
    oi: "Cellulose, Vegetable Cellulose, Silica, Magnesium Stearate, Dextrin and  Enteric Coating.  Contains: Soy",
    blockers: ["no pack count or weight on the label opened for this SKU"],
  },
  {
    sku: "076280946123",
    name: "Her Life Stages PMS & Menstrual",
    count: "24 ct",
    form: "capsule",
    url: "https://www.solaray.com/products/her-life-stages-pms-menstrual",
    oi: "Cellulose, Vegetable Capsule, Stearic Acid, Silica, Acacia (Gum Arabic), Maltodextrin,  Potato Dextrin.",
    blockers: ["Vegetable Capsule"],
  },
  {
    sku: "076280955781",
    name: "Her Life Stages Perimenopause",
    count: "60 ct",
    form: "capsule",
    url: "https://www.solaray.com/products/her-life-stages-perimenopause",
    oi: "Cellulose, Vegetable Capsule, Dextrin, Stearic Acid, Silica.",
    blockers: ["Vegetable Capsule"],
  },
  {
    sku: "076280968682",
    name: "Liposomal Multivitamin Prenatal",
    count: "",
    form: "capsule",
    url: "https://www.solaray.com/products/liposomal-prenatal",
    oi: "Lipid Blend from Sunflower Oil and Sustainable Palm Oil, Vegetable Cellulose Capsule, Cellulose, Magnesium Stearate, Modified Tapioca Starch, Silica, Sodium Alginate, and Pea Starch.",
    blockers: ["no pack count or weight on the label opened for this SKU"],
  },
  {
    sku: "X0042AF2L7",
    name: "Oil Of Oregano 150mg",
    count: "120ct",
    form: "",
    url: "https://www.solaray.com/products/oil-of-oregano",
    oi: "",
    blockers: ["no SKU-specific supplement-facts image that fully maps"],
  },
];

export const BATCH127_LEFTOVER_REAL_TOKENS = [
  "Calcium Fluoride 6x",
  "Calcium Phosphate 3x",
  "Herb Base (Parsley Leaf, Alfalfa Leaf)",
  "Herb Base (Parsley Leaf, Chamomile, Watercress)",
  "Herb Base (Parsley Leaf, Organic Alfalfa Leaf)",
  "Herbal Base (Parsley, Rice Flour, Yellow Dock Root)",
  "Magnesium Phosphate 3x",
  "Parsley",
  "Parsley Aerial",
  "Parsley Herb",
  "Parsley Leaf",
  "Potassium Phosphate 3x",
  "Silica 6x",
  "Sodium Chloride 6x",
  "Vegetable Capsule",
  "Vegetarian Capsule",
];

const _ROWS = BATCH127_KYR6B_SOLARAY_CA_ASCORBATE;
if (_ROWS.length !== 1) throw new Error("batch127 tally drift");
if (_ROWS.filter((r) => r.verdict === "clean").length !== 1) throw new Error("batch127 Clean tally drift");
if (_ROWS.filter((r) => r.verdict === "caution").length !== 0) throw new Error("batch127 Caution tally drift");
if (_ROWS.filter((r) => r.verdict === "avoid").length !== 0) throw new Error("batch127 Avoid tally drift");
if (_ROWS.filter((r) => r.formulaId === r.id).length !== 1) throw new Error("batch127 NEW tally drift");
if (_ROWS.filter((r) => r.formulaId !== r.id).length !== 0) throw new Error("batch127 REUSE tally drift");
if (_ROWS.some((r) => r.recordStatus !== UNVERIFIED)) throw new Error("batch127 recordStatus");
if (_ROWS.some((r) => r.brand !== BRAND)) throw new Error("batch127 brand");
if (_ROWS.some((r) => r.barcode)) throw new Error("batch127 UPC must stay blank");
if (_ROWS.some((r) => r.form === "liquid")) throw new Error("batch127 must not grade pour bottles");
if (_ROWS.some((r) => !/\([^)]*\d/.test(r.productName))) throw new Error("batch127 row missing pack size");
if (_ROWS.some((r) => !r.form)) throw new Error("batch127 row missing form");
if (_ROWS[0].id !== "solaray-b127-076280282467") throw new Error("batch127 sku");
if (BATCH127_SKIPPED_NO_OI.length !== 1) throw new Error("batch127 no_OI");
if (BATCH127_SKIPPED_NO_OI[0].sku !== "076280830385") throw new Error("batch127 no_OI sku");
if (BATCH127_SKIPPED_OUT.length !== 0) throw new Error("batch127 OUT");
if (BATCH127_HUNT_POUR.length !== 4) throw new Error("batch127 hunt");
if (BATCH127_REFUSED.length !== 111) throw new Error("batch127 REFUSED");
if (BATCH127_REFUSED.some((r) => r.sku === "076280282467")) throw new Error("batch127 wrote SKU still refused");
if (BATCH127_LEFTOVER_REAL_TOKENS.length !== 16) throw new Error("batch127 leftover");
if (BATCH127_LEFTOVER_REAL_TOKENS.includes("Calcium Ascorbate")) throw new Error("Calcium Ascorbate still leftover");
if (_ROWS.some((r) => r.verdict === "clean" && r.inactiveIngredients.some((i) => i.riskLevel !== "cleared"))) throw new Error("batch127 Clean has a flag");
const _KEEP = ["Parsley Leaf","Parsley","Parsley Aerial","Parsley Herb","Vegetable Capsule","Vegetarian Capsule","Calcium Fluoride 6x","Silica 6x","Sodium Chloride 6x","Calcium Phosphate 3x","Magnesium Phosphate 3x","Potassium Phosphate 3x"];
if (_KEEP.some((t) => !BATCH127_LEFTOVER_REAL_TOKENS.includes(t))) throw new Error("required leftover missing");

