// DRAFT / not verified / batch 124 KYR6-b Solaray fat closeout.
// Methodology v1.6 + MAIN section 5. Harm-first. No invented grades.
// Sept 28, 2026 founder aliases only. Existing grades were not flipped.
// Sucrose stays the Sept 20 Limited sugar row. Multi Energy was not rewritten.
// Parsley Leaf was not stamped. No Italy, LLC, trademark, or OCR junk.
// batch70-batch123 were not edited. Solaray only. UPC stays empty.
//
// TALLY: 18 rows — Clean 6 / Caution 11 / Avoid 1.
// NEW 12 / REUSE 6 / SKIPPED no_OI leftover 1 / SKIPPED OUT 0 / REFUSED 166.
// Report REUSE also counts 2 twins already on MAIN (batch122) that are not rewritten.

import type {
  CleanAlternative,
  IngredientFlag,
  RatingRecord,
} from '../ratingRecord';

const UNVERIFIED = 'unverified' as const;
const ADULT = 'adult' as const;
const SUPPLEMENT = 'Supplement' as const;
const UNVERIFIED_NOTE = 'draft, not verified';
const BRAND = 'Solaray';
const RETAILERS = ['Amazon', 'solaray.com'] as const;
const LIMITED_STACK =
  'Limited-only stack stays Caution (no 3-pt Avoid). Limited-only never Avoid. Avoid needs High.';
const UPC_BLANK =
  'No GTIN-12 was printed under the bars on the panel opened for Other Ingredients, so UPC is blank. Shopify barcodes that echo the SKU are not UPCs.';

const METH = {
  alginate: 'Methodology §5 Cleared (sodium alginate).',
  beeswax: 'Methodology §5 Cleared (beeswax / yellow beeswax).',
  cane: 'Methodology §5 Cleared (cane sugar).',
  caphos: 'Methodology §5 Cleared (calcium phosphate). Dicalcium Phosphate maps here (Sept 28, 2026).',
  carnauba: 'Methodology §5 Caution (carnauba wax). Organic carnauba wax is the same row.',
  citrate: 'Methodology §5 Cleared (citrate salts / sodium citrate).',
  citric: 'Methodology §5 Cleared (citric acid). Bare citric acid stays here, including on a gummy.',
  flavor: 'Methodology §5 Caution (named flavor). Bare Natural Lemon, Natural Peach, and Natural Raspberry map here (Sept 28, 2026). Organic Natural Lemon is the Organic-prefix form. The Limited natural-flavors opacity row is not flipped.',
  gelatin: 'Methodology §5 Cleared (gelatin / gelatin capsule).',
  glycerin: 'Methodology §5 Cleared (glycerin).',
  glycine: 'Methodology §5 Cleared (glycine).',
  gum: 'Methodology §5 Cleared (guar / acacia / gum arabic / pectin). Gum Acacia is this row.',
  himalayan: 'Methodology §5 Cleared (Himalayan rock salt). Himalayan Pink Salt is the same salt.',
  maltodextrin: 'Methodology §5 Limited (maltodextrin). Parenthetical Non-GMO corn is the same row.',
  mcc: 'Methodology §5 Cleared (cellulose / MCC / croscarmellose sodium).',
  oilfill: 'Methodology §5 Cleared (named oil as non-gummy softgel / capsule fill). Soy Oil is soybean oil. Extra Virgin Olive Oil is olive-oil fill. Gummy and lozenge seed oils stay High.',
  oilhigh: 'Methodology §5 High (gummy / lozenge seed oil, including sunflower oil and soybean oil). Avoid.',
  peastarch: 'Methodology §5 Caution (pea starch). Not Avoid.',
  riceextract: 'Methodology §5 Limited (unspecified rice extract). Organic Rice Extract Blend maps here.',
  sio2: 'Methodology §5 Limited (silica / silicon dioxide). Not Avoid.',
  soy: 'Methodology §5 Limited (bare soy). Not soy lecithin. Not High.',
  stearate: 'Methodology §5 Cleared (magnesium stearate / stearic acid).',
  stevia: 'Methodology §5 Caution (stevia extract / stevia leaf extract).',
  sucrose: 'Methodology §5 Limited (sucrose = existing Limited sugar, Sept 20). Not High. Not flipped to Avoid.',
  tapiocasyrup: 'Methodology §5 Cleared (tapioca syrup). Organic tapioca syrup is the same row.',
  vegcap: 'Methodology §5 Cleared (capsule cellulose / labeled veg cap). Vegetable Celluose Capsule is the spelling of Vegetable Cellulose Capsule (Sept 28, 2026).',
  water: 'Methodology §5 Cleared (water / purified water).',
} as const;

function flag(name: string, riskLevel: IngredientFlag['riskLevel'], source: string): IngredientFlag {
  return { name, riskLevel, source };
}
function labelCite(label: string, meth: string): string {
  return `${label}; ${meth}`;
}
function alt(productId: string, rankReason: string): CleanAlternative {
  return { productId, rankReason };
}
function row(opts: Omit<RatingRecord, 'recordStatus'> & { recordStatus?: RatingRecord['recordStatus'] }): RatingRecord {
  return { ...opts, recordStatus: opts.recordStatus ?? UNVERIFIED };
}
type Compact = {
  id: string;
  productName: string;
  formulaId: string;
  form: string;
  actives: RatingRecord['activeIngredients'];
  flags: [string, IngredientFlag['riskLevel'], keyof typeof METH][];
  verdict: RatingRecord['verdict'];
  note: string;
  cite: string;
};
function expand(d: Compact): RatingRecord {
  const alts: CleanAlternative[] = [];
  if (d.verdict !== 'clean') {
    alts.push(alt('amazon-elements-vitamin-d3-5000-softgels', 'Independently Clean Amazon Elements Vitamin D3 5000 IU already on main. Form labeled, not a hard filter (§6).'));
  }
  return row({
    id: d.id,
    productName: d.productName,
    brand: BRAND,
    category: 'Vitamins',
    formulaId: d.formulaId,
    audience: ADULT,
    minAge: 18,
    form: d.form,
    productType: SUPPLEMENT,
    activeIngredients: d.actives,
    inactiveIngredients: d.flags.map(([n, risk, meth]) => flag(n, risk, labelCite(d.cite, METH[meth]))),
    verdict: d.verdict,
    honestNote: `${d.note} ${LIMITED_STACK} Pack sizes share formulaId \`${d.formulaId}\` when this OI list holds. Adults unless the name says kids. No dosing or medical advice. Draft, not verified.`,
    retailers: [...RETAILERS],
    cleanAlternatives: alts.length ? alts : undefined,
    sourcesGeneral: [`${d.cite} — ${UNVERIFIED_NOTE}; no DailyMed drug SPL`],
  });
}

const COMPACT: Compact[] = [

  {
    id: 'solaray-b124-076280041682',
    productName: 'Solaray Bio Vitamin E + Selenium 268mg (60ct)',
    formulaId: 'solaray-b124-076280041682',
    form: 'softgel',
    actives: [
      { name: 'Vitamin E (as d-Alpha Tocopherol)', strength: '268 mg' },
      { name: 'Selenium (as L-Selenomethionine)', strength: '100 mcg' },
      { name: 'Lecithin', strength: '1,600 mg' },
    ],
    flags: [
      ['gelatin', 'cleared', 'gelatin'],
      ['glycerin', 'cleared', 'glycerin'],
      ['Soy Oil', 'cleared', 'oilfill'],
      ['Yellow Beeswax', 'cleared', 'beeswax'],
    ],
    verdict: 'clean',
    note: 'FOUNDER-LOCK DRAFT: Clean. Soy Oil maps to soybean oil as non-gummy softgel fill (Cleared). Softgel gelatin and glycerin are Cleared. Yellow beeswax is Cleared. No High. No Limited.',
    cite: `solaray.com supplement-facts image https://solaray.com/products/bio-vitamin-e-with-selenium other-ingredients: Softgel (Gelatin and Glycerin), Soy Oil and Yellow Beeswax. Servings per container 30 x 2 softgels = 60ct. Exact pack Solaray Bio Vitamin E + Selenium 268mg (60ct). SKU 076280041682. ${UPC_BLANK}`,
  },
  {
    id: 'solaray-b124-076280041699',
    productName: 'Solaray Bio Vitamin E + Selenium 268mg (120ct)',
    formulaId: 'solaray-b124-076280041682',
    form: 'softgel',
    actives: [
      { name: 'Vitamin E (as d-Alpha Tocopherol)', strength: '268 mg' },
      { name: 'Selenium (as L-Selenomethionine)', strength: '100 mcg' },
      { name: 'Lecithin', strength: '1,600 mg' },
    ],
    flags: [
      ['gelatin', 'cleared', 'gelatin'],
      ['glycerin', 'cleared', 'glycerin'],
      ['Soy Oil', 'cleared', 'oilfill'],
      ['Yellow Beeswax', 'cleared', 'beeswax'],
    ],
    verdict: 'clean',
    note: 'FOUNDER-LOCK DRAFT: Clean. Same Other Ingredients as the 60ct. Soy Oil is non-gummy soybean-oil fill (Cleared). REUSE formula solaray-b124-076280041682.',
    cite: `solaray.com supplement-facts image https://solaray.com/products/bio-vitamin-e-with-selenium other-ingredients: Softgel (Gelatin and Glycerin), Soy Oil and Yellow Beeswax. Servings per container 60 x 2 softgels = 120ct. Exact pack Solaray Bio Vitamin E + Selenium 268mg (120ct). SKU 076280041699. ${UPC_BLANK}`,
  },
  {
    id: 'solaray-b124-076280047929',
    productName: 'Solaray Women\'s Golden Multivitamin (90 ct)',
    formulaId: 'solaray-b124-076280047929',
    form: 'capsule',
    actives: [
      { name: 'Vitamin C (as Ascorbic Acid)', strength: '400 mg' },
      { name: 'Vitamin D (as Cholecalciferol)', strength: '10 mcg' },
      { name: 'Vitamin E (as d-Alpha Tocopheryl Succinate)', strength: '268 mg' },
    ],
    flags: [
      ['Gelatin Capsule', 'cleared', 'gelatin'],
      ['Soy', 'limited', 'soy'],
      ['Cellulose', 'cleared', 'mcc'],
      ['Magnesium Stearate', 'cleared', 'stearate'],
      ['Sucrose', 'limited', 'sucrose'],
      ['Acacia', 'cleared', 'gum'],
      ['Silica', 'limited', 'sio2'],
    ],
    verdict: 'caution',
    note: 'FOUNDER-LOCK DRAFT: Caution. Bare Soy is the Sept 21 Limited bare-soy row, not soy lecithin. Sucrose stays the existing Limited sugar row. Not Avoid. Driver families: soy, sucrose, sio2.',
    cite: `solaray.com supplement-facts image https://solaray.com/products/womens-golden-multi-vitamin other-ingredients: Gelatin Capsule, Soy, Cellulose, Magnesium Stearate, Sucrose, Acacia and Silica. Servings per container 30 x 3 capsules = 90 ct. Exact pack Solaray Women's Golden Multivitamin (90 ct). SKU 076280047929. ${UPC_BLANK}`,
  },
  {
    id: 'solaray-b124-076280047943',
    productName: 'Solaray Men\'s Golden Multivitamin (90ct)',
    formulaId: 'solaray-b124-076280047943',
    form: 'capsule',
    actives: [
      { name: 'Vitamin C (as Ascorbic Acid)', strength: '400 mg' },
      { name: 'Vitamin D (as Cholecalciferol)', strength: '10 mcg' },
      { name: 'Vitamin E (as d-Alpha-Tocopheryl Succinate)', strength: '330 mg' },
    ],
    flags: [
      ['Gelatin Capsule', 'cleared', 'gelatin'],
      ['Soy', 'limited', 'soy'],
      ['Sucrose', 'limited', 'sucrose'],
      ['Cellulose', 'cleared', 'mcc'],
      ['Magnesium Stearate', 'cleared', 'stearate'],
      ['Silica', 'limited', 'sio2'],
    ],
    verdict: 'caution',
    note: 'FOUNDER-LOCK DRAFT: Caution. Bare Soy is the Sept 21 Limited bare-soy row. Sucrose stays Limited. Not Avoid. Driver families: soy, sucrose, sio2. Different formula from the women\'s golden (no acacia).',
    cite: `solaray.com supplement-facts image https://solaray.com/products/mens-golden-multi-vitamin other-ingredients: Gelatin Capsule, Soy, Sucrose, Cellulose, Magnesium Stearate, Silica. Servings per container 30 x 3 capsules = 90ct. Exact pack Solaray Men's Golden Multivitamin (90ct). SKU 076280047943. ${UPC_BLANK}`,
  },
  {
    id: 'solaray-b124-076280036640',
    productName: 'Solaray Hawthorn Aerial Ext, One Daily 600mg (30 ct)',
    formulaId: 'solaray-b124-076280036640',
    form: 'capsule',
    actives: [
      { name: 'Hawthorn (Crataegus oxyacantha) (leaf and flower extract)', strength: '600 mg' },
      { name: 'Hawthorn (Crataegus oxyacantha) (berry)', strength: '100 mg' },
    ],
    flags: [
      ['Maltodextrin (from Non-GMO Corn)', 'limited', 'maltodextrin'],
      ['Vegetable Celluose Capsule', 'cleared', 'vegcap'],
      ['Organic Rice Extract Blend', 'limited', 'riceextract'],
      ['Silica', 'limited', 'sio2'],
    ],
    verdict: 'caution',
    note: 'FOUNDER-LOCK DRAFT: Caution. Vegetable Celluose Capsule is the spelling of Vegetable Cellulose Capsule (Cleared). Driver families: maltodextrin, riceextract, sio2. No High.',
    cite: `solaray.com supplement-facts image https://solaray.com/products/hawthorn-aerial-ext-one-daily other-ingredients: Maltodextrin (from Non-GMO Corn), Vegetable Celluose Capsule, Organic Rice Extract Blend and Silica. Shopify variant title 30 ct for SKU 076280036640. Exact pack Solaray Hawthorn Aerial Ext, One Daily 600mg (30 ct). ${UPC_BLANK}`,
  },
  {
    id: 'solaray-b124-076280041408',
    productName: 'Solaray Vitamin D-3 - 10mcg (120ct)',
    formulaId: 'solaray-b124-076280041408',
    form: 'softgel',
    actives: [
      { name: 'Vitamin D-3 (as Cholecalciferol)', strength: '10 mcg' },
    ],
    flags: [
      ['Extra Virgin Olive Oil', 'cleared', 'oilfill'],
      ['Gelatin', 'cleared', 'gelatin'],
      ['Glycerin', 'cleared', 'glycerin'],
      ['Water', 'cleared', 'water'],
      ['Safflower Oil', 'cleared', 'oilfill'],
    ],
    verdict: 'clean',
    note: 'FOUNDER-LOCK DRAFT: Clean. Extra Virgin Olive Oil is pure olive oil as softgel fill (Cleared). Safflower oil as softgel fill is Cleared. Not a gummy. Not a pour bottle.',
    cite: `solaray.com supplement-facts image https://solaray.com/products/vitamin-d-3 other-ingredients: Extra Virgin Olive Oil, Gelatin, Glycerin, Water and Safflower Oil. Shopify variant title 120ct for SKU 076280041408. Exact pack Solaray Vitamin D-3 - 10mcg (120ct). ${UPC_BLANK}`,
  },
  {
    id: 'solaray-b124-076280222548',
    productName: 'Solaray Electrolyte Recovery, Pink Lemonade (249 g)',
    formulaId: 'solaray-b124-076280222548',
    form: 'powder',
    actives: [
      { name: 'Magnesium (Magnesium Glycinate)', strength: '60 mg' },
      { name: 'Sodium', strength: '350 mg' },
      { name: 'Potassium', strength: '700 mg' },
      { name: 'Chloride', strength: '430 mg' },
    ],
    flags: [
      ['Citric Acid', 'cleared', 'citric'],
      ['Glycine', 'cleared', 'glycine'],
      ['Natural Raspberry', 'limited', 'flavor'],
      ['Lemon Flavors with Other Natural Flavors', 'limited', 'flavor'],
      ['Silica', 'limited', 'sio2'],
      ['Stevia (leaf extract)', 'limited', 'stevia'],
    ],
    verdict: 'caution',
    note: 'FOUNDER-LOCK DRAFT: Caution. Natural Raspberry is the named-flavor family (Caution). Driver families: flavor, sio2, stevia. No High.',
    cite: `solaray.com supplement-facts image https://solaray.com/products/electrolyte-recovery other-ingredients: Citric Acid, Glycine, Natural Raspberry and Lemon Flavors with Other Natural Flavors, Silica, and Stevia (leaf extract). Serving size 1 scoop (8.3 g) x 30 servings = 249 g. Exact pack Solaray Electrolyte Recovery, Pink Lemonade. SKU 076280222548. ${UPC_BLANK}`,
  },
  {
    id: 'solaray-b124-076280739503',
    productName: 'Solaray Extra-Strength Magnesium Glycinate Powder 500 mg, Lemon Lime (279 g)',
    formulaId: 'solaray-b124-076280739503',
    form: 'powder',
    actives: [
      { name: 'Magnesium (Magnesium Bisglycinate)', strength: '500 mg' },
    ],
    flags: [
      ['Citric Acid', 'cleared', 'citric'],
      ['Natural Lemon', 'limited', 'flavor'],
      ['Lime Flavors with Other Natural Flavors', 'limited', 'flavor'],
      ['Silica', 'limited', 'sio2'],
      ['Stevia (leaf extract)', 'limited', 'stevia'],
    ],
    verdict: 'caution',
    note: 'FOUNDER-LOCK DRAFT: Caution. Natural Lemon is the named-flavor family (Caution). Driver families: flavor, sio2, stevia. No High.',
    cite: `solaray.com supplement-facts image https://solaray.com/products/extra-strength-magnesium-glycinate-powder-unflavored-500-mg other-ingredients: Citric Acid, Natural Lemon and Lime Flavors with Other Natural Flavors, Silica, and Stevia (leaf extract). Serving size 1 scoop (9.3 g) x 30 servings = 279 g. Brand facts-image filename also states 9.9 oz. Exact pack Solaray Extra-Strength Magnesium Glycinate Powder 500 mg, Lemon Lime. SKU 076280739503. ${UPC_BLANK}`,
  },
  {
    id: 'solaray-b124-076280635003',
    productName: 'Solaray Organic Elderberry Gummies (60ct)',
    formulaId: 'solaray-b124-076280635003',
    form: 'gummy',
    actives: [
      { name: 'Organic Elderberry (Sambucus nigra) Fruit Powder', strength: '150 mg' },
      { name: 'Vitamin C (as Ascorbic Acid)', strength: '45 mg' },
      { name: 'Zinc (as Zinc Citrate)', strength: '5 mg' },
    ],
    flags: [
      ['Organic Tapioca Syrup', 'cleared', 'tapiocasyrup'],
      ['Organic Cane Sugar', 'cleared', 'cane'],
      ['Water', 'cleared', 'water'],
      ['Citric Acid', 'cleared', 'citric'],
      ['Organic Natural Lemon', 'limited', 'flavor'],
      ['Raspberry Flavors with other Natural Flavors', 'limited', 'flavor'],
      ['Organic Sunflower Oil', 'high', 'oilhigh'],
      ['Organic Carnauba Wax', 'limited', 'carnauba'],
      ['Pectin', 'cleared', 'gum'],
      ['Sodium Citrate', 'cleared', 'citrate'],
    ],
    verdict: 'avoid',
    note: 'FOUNDER-LOCK DRAFT: Avoid. Organic sunflower oil in a gummy is the existing gummy seed-oil High row. Organic Natural Lemon is the named-flavor family (Caution). Organic carnauba wax is Caution. Bare citric acid stays Cleared.',
    cite: `solaray.com supplement-facts image https://solaray.com/products/organic-elderberry-gummies other-ingredients: Organic Tapioca Syrup, Organic Cane Sugar, Water, Contains Less than 2% of Citric Acid, Organic Natural Lemon & Raspberry Flavors with other Natural Flavors, Organic Sunflower Oil & Organic Carnauba Wax, Pectin and Sodium Citrate. Serving size 2 gummies x 30 servings = 60ct. Exact pack Solaray Organic Elderberry Gummies (60ct). SKU 076280635003. ${UPC_BLANK}`,
  },
  {
    id: 'solaray-b124-076280037821',
    productName: 'Solaray Saw Palmetto Berry Extract 160mg (60ct)',
    formulaId: 'solaray-b123-076280037814',
    form: 'softgel',
    actives: [
      { name: 'Saw Palmetto Berry Extract', strength: '160 mg' },
    ],
    flags: [
      ['gelatin', 'cleared', 'gelatin'],
      ['glycerin', 'cleared', 'glycerin'],
      ['Virgin Olive Oil', 'cleared', 'oilfill'],
    ],
    verdict: 'clean',
    note: 'FOUNDER-LOCK DRAFT: Clean. Count sibling of the 30ct already on MAIN. Virgin olive oil is softgel fill (Cleared). REUSE formula solaray-b123-076280037814.',
    cite: `solaray.com supplement-facts image https://solaray.com/products/saw-palmetto-berry-extract other-ingredients: Softgel (Gelatin and Glycerin) and Virgin Olive Oil. One facts image on the PDP (30ct tile). Shopify variant 60ct. Exact pack Solaray Saw Palmetto Berry Extract 160mg (60ct). SKU 076280037821. ${UPC_BLANK}`,
  },
  {
    id: 'solaray-b124-076280037838',
    productName: 'Solaray Saw Palmetto Berry Extract 160mg (120ct)',
    formulaId: 'solaray-b123-076280037814',
    form: 'softgel',
    actives: [
      { name: 'Saw Palmetto Berry Extract', strength: '160 mg' },
    ],
    flags: [
      ['gelatin', 'cleared', 'gelatin'],
      ['glycerin', 'cleared', 'glycerin'],
      ['Virgin Olive Oil', 'cleared', 'oilfill'],
    ],
    verdict: 'clean',
    note: 'FOUNDER-LOCK DRAFT: Clean. Count sibling of the 30ct already on MAIN. REUSE formula solaray-b123-076280037814.',
    cite: `solaray.com supplement-facts image https://solaray.com/products/saw-palmetto-berry-extract other-ingredients: Softgel (Gelatin and Glycerin) and Virgin Olive Oil. Shopify variant 120ct. Exact pack Solaray Saw Palmetto Berry Extract 160mg (120ct). SKU 076280037838. ${UPC_BLANK}`,
  },
  {
    id: 'solaray-b124-076280037845',
    productName: 'Solaray Saw Palmetto Berry Extract 160mg (240ct)',
    formulaId: 'solaray-b123-076280037814',
    form: 'softgel',
    actives: [
      { name: 'Saw Palmetto Berry Extract', strength: '160 mg' },
    ],
    flags: [
      ['gelatin', 'cleared', 'gelatin'],
      ['glycerin', 'cleared', 'glycerin'],
      ['Virgin Olive Oil', 'cleared', 'oilfill'],
    ],
    verdict: 'clean',
    note: 'FOUNDER-LOCK DRAFT: Clean. Count sibling of the 30ct already on MAIN. REUSE formula solaray-b123-076280037814.',
    cite: `solaray.com supplement-facts image https://solaray.com/products/saw-palmetto-berry-extract other-ingredients: Softgel (Gelatin and Glycerin) and Virgin Olive Oil. Shopify variant 240ct. Exact pack Solaray Saw Palmetto Berry Extract 160mg (240ct). SKU 076280037845. ${UPC_BLANK}`,
  },
  {
    id: 'solaray-b124-076280200553',
    productName: 'Solaray Once Daily Active Man Multivitamin (90ct)',
    formulaId: 'solaray-b124-076280200553',
    form: 'capsule',
    actives: [
      { name: 'Vitamin C (as Ascorbic Acid, from Rose Hips, Acerola Cherry)', strength: '100 mg' },
      { name: 'Vitamin D (as Cholecalciferol)', strength: '25 mcg' },
      { name: 'Vitamin E (as d-Alpha Tocopheryl Succinate)', strength: '40 mg' },
    ],
    flags: [
      ['Vegetable Cellulose Capsule', 'cleared', 'vegcap'],
      ['Cellulose', 'cleared', 'mcc'],
      ['Magnesium Stearate', 'cleared', 'stearate'],
      ['Silica', 'limited', 'sio2'],
      ['Sodium Alginate', 'cleared', 'alginate'],
      ['Pea Starch', 'limited', 'peastarch'],
      ['Dicalcium Phosphate', 'cleared', 'caphos'],
      ['Gum Acacia', 'cleared', 'gum'],
    ],
    verdict: 'caution',
    note: 'FOUNDER-LOCK DRAFT: Caution. Gum Acacia is acacia / gum arabic (Cleared). Dicalcium Phosphate is the calcium-phosphate row (Cleared). Driver families: sio2, peastarch. No High.',
    cite: `solaray.com supplement-facts image https://solaray.com/products/once-daily-active-man-multi-vitamin other-ingredients: Vegetable Cellulose Capsule, Cellulose, Magnesium Stearate, Silica, Sodium Alginate, Pea Starch, Dicalcium Phosphate, Gum Acacia. Exact pack Solaray Once Daily Active Man Multivitamin (90ct). SKU 076280200553. ${UPC_BLANK}`,
  },
  {
    id: 'solaray-b124-076280034004',
    productName: 'Solaray Echinacea Angustifolia Root Ext 125mg (60ct)',
    formulaId: 'solaray-b124-076280034004',
    form: 'capsule',
    actives: [
      { name: 'Echinacea (Echinacea angustifolia) (root extract)', strength: '125 mg' },
      { name: 'Echinacea (Echinacea angustifolia) (root)', strength: '43 mg' },
    ],
    flags: [
      ['Cellulose', 'cleared', 'mcc'],
      ['Vegetable Cellulose Capsule', 'cleared', 'vegcap'],
      ['Maltodextrin (from Non-GMO Corn)', 'limited', 'maltodextrin'],
    ],
    verdict: 'caution',
    note: 'FOUNDER-LOCK DRAFT: Caution. Maltodextrin (from Non-GMO Corn) is the existing Limited maltodextrin row. Driver family: maltodextrin. No High.',
    cite: `solaray.com supplement-facts image https://solaray.com/products/echinacea-angustifolia-root-ext other-ingredients: Cellulose, Vegetable Cellulose Capsule and Maltodextrin (from Non-GMO Corn). Shopify variant title 60ct. Exact pack Solaray Echinacea Angustifolia Root Ext 125mg (60ct). SKU 076280034004. ${UPC_BLANK}`,
  },
  {
    id: 'solaray-b124-076280048001',
    productName: 'Solaray Super Digestaway (60ct)',
    formulaId: 'solaray-b124-076280048001',
    form: 'capsule',
    actives: [
      { name: 'Pancreatin 4x', strength: '175 mg' },
      { name: 'Papain (from Papaya)', strength: '50 mg' },
      { name: 'Bromelain (from Pineapple stem)', strength: '20 mg' },
    ],
    flags: [
      ['Vegetable Cellulose Capsule', 'cleared', 'vegcap'],
      ['Cellulose', 'cleared', 'mcc'],
      ['Maltodextrin (from Non-GMO Corn)', 'limited', 'maltodextrin'],
      ['Magnesium Stearate', 'cleared', 'stearate'],
      ['Silica', 'limited', 'sio2'],
    ],
    verdict: 'caution',
    note: 'FOUNDER-LOCK DRAFT: Caution. The enzyme-unit footnote after Silica is not an ingredient. Driver families: maltodextrin, sio2. No High.',
    cite: `solaray.com supplement-facts image https://solaray.com/products/super-digestaway-digestive-enzyme-blend other-ingredients: Vegetable Cellulose Capsule, Cellulose, Maltodextrin (from Non-GMO Corn), Magnesium Stearate and Silica. Exact pack Solaray Super Digestaway (60ct). SKU 076280048001. ${UPC_BLANK}`,
  },
  {
    id: 'solaray-b124-076280048018',
    productName: 'Solaray Super Digestaway (90ct)',
    formulaId: 'solaray-b124-076280048001',
    form: 'capsule',
    actives: [
      { name: 'Pancreatin 4x', strength: '175 mg' },
      { name: 'Papain (from Papaya)', strength: '50 mg' },
      { name: 'Bromelain (from Pineapple stem)', strength: '20 mg' },
    ],
    flags: [
      ['Vegetable Cellulose Capsule', 'cleared', 'vegcap'],
      ['Cellulose', 'cleared', 'mcc'],
      ['Maltodextrin (from Non-GMO Corn)', 'limited', 'maltodextrin'],
      ['Magnesium Stearate', 'cleared', 'stearate'],
      ['Silica', 'limited', 'sio2'],
    ],
    verdict: 'caution',
    note: 'FOUNDER-LOCK DRAFT: Caution. Count sibling. The PDP has one supplement-facts image (60ct file) and batch121 recorded maltodextrin as the only unknown on this count. REUSE formula solaray-b124-076280048001.',
    cite: `solaray.com supplement-facts image https://solaray.com/products/super-digestaway-digestive-enzyme-blend other-ingredients: Vegetable Cellulose Capsule, Cellulose, Maltodextrin (from Non-GMO Corn), Magnesium Stearate and Silica. Shopify variant 90ct. Exact pack Solaray Super Digestaway (90ct). SKU 076280048018. ${UPC_BLANK}`,
  },
  {
    id: 'solaray-b124-076280048025',
    productName: 'Solaray Super Digestaway (180ct)',
    formulaId: 'solaray-b124-076280048001',
    form: 'capsule',
    actives: [
      { name: 'Pancreatin 4x', strength: '175 mg' },
      { name: 'Papain (from Papaya)', strength: '50 mg' },
      { name: 'Bromelain (from Pineapple stem)', strength: '20 mg' },
    ],
    flags: [
      ['Vegetable Cellulose Capsule', 'cleared', 'vegcap'],
      ['Cellulose', 'cleared', 'mcc'],
      ['Maltodextrin (from Non-GMO Corn)', 'limited', 'maltodextrin'],
      ['Magnesium Stearate', 'cleared', 'stearate'],
      ['Silica', 'limited', 'sio2'],
    ],
    verdict: 'caution',
    note: 'FOUNDER-LOCK DRAFT: Caution. Count sibling. REUSE formula solaray-b124-076280048001.',
    cite: `solaray.com supplement-facts image https://solaray.com/products/super-digestaway-digestive-enzyme-blend other-ingredients: Vegetable Cellulose Capsule, Cellulose, Maltodextrin (from Non-GMO Corn), Magnesium Stearate and Silica. Shopify variant 180ct. Exact pack Solaray Super Digestaway (180ct). SKU 076280048025. ${UPC_BLANK}`,
  },
  {
    id: 'solaray-b124-076280355307',
    productName: 'Solaray Mycrobiome Prebiotic, Citrus (5.64 oz / 160 g)',
    formulaId: 'solaray-b124-076280355307',
    form: 'powder',
    actives: [
      { name: 'POTATODAAT (Solanum tuberosum) (Resistant Starch)', strength: '5,000 mg' },
      { name: 'MICROBIOMEX Orange and Grapefruit Prebiotic Blend', strength: '250 mg' },
    ],
    flags: [
      ['Natural Mandarin Orange flavor with other natural flavors', 'limited', 'flavor'],
      ['Citric Acid', 'cleared', 'citric'],
      ['Himalayan Pink Salt', 'cleared', 'himalayan'],
    ],
    verdict: 'caution',
    note: 'FOUNDER-LOCK DRAFT: Caution. Natural Mandarin Orange flavor is the named-flavor family. Himalayan Pink Salt is Himalayan rock salt (Cleared). Driver family: flavor. No High.',
    cite: `solaray.com supplement-facts image https://solaray.com/products/mycrobiome-prebiotic other-ingredients: Natural Mandarin Orange flavor with other natural flavors, Citric Acid, and Himalayan Pink Salt. Serving size 1 scoop (8 g) x 20 servings = 160 g. Shopify variant title 5.64 oz (160 g). Exact pack Solaray Mycrobiome Prebiotic, Citrus. SKU 076280355307. ${UPC_BLANK}`,
  },

];

export const BATCH124_KYR6B_SOLARAY_FAT_CLOSEOUT: RatingRecord[] = COMPACT.map(expand);

export const BATCH124_SKIPPED_NO_OI: { sku: string; name: string; count: string; why: string }[] = [
  {
    sku: '076280830385',
    name: 'Liposomal Multivitamin Universal',
    count: '60ct',
    why: 'solaray.com variant 076280830385 has an empty barcode and the description has no Other Ingredients line. The only supplement-facts image on that PDP is lb_facts_076280640168.png, a different SKU, and was not copied. iHerb search returned 403. Vitacost search HTTP 200 was a robot/challenge page. Walmart redirected to /blocked (Robot or human?). Target HTTP 200 was a robot/captcha page. Amazon search did not return this SKU or an Other Ingredients line (two Garden of Life results; a later Amazon fetch returned 503). VitaNet, HiLife, and keepbodyhealth print an ingredients sentence and do not print 076280830385. Fullscript returned no product body for this SKU. CPSC recall names 076280830385 and does not print Other Ingredients. Web search synthesis is not OI.',
  },
];

export const BATCH124_SKIPPED_OUT: { sku: string; name: string; why: string }[] = [];

export const BATCH124_HUNT_POUR: { name: string; url: string }[] = [];

export const BATCH124_REFUSED: { sku: string; name: string; count: string; form: string; url: string; oi: string; blockers: string[] }[] = [
  { sku: '076280002102', name: 'Hormone Blend SP-1', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/hormone-blend-sp-1', oi: 'Vegetable Cellulose Capsule and Trace Mineral Complex.', blockers: ['Trace Mineral Complex'] },
  { sku: '076280002300', name: 'Respiration Blend SP-3', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/respiration-blend-sp-3', oi: 'Vegetable Cellulose Capsule and Trace Mineral Complex.', blockers: ['Trace Mineral Complex'] },
  { sku: '076280002409', name: 'Skin Blend SP-4', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/skin-blend-sp-4', oi: 'Vegetable Cellulose Capsule and Trace Mineral Complex.', blockers: ['Trace Mineral Complex'] },
  { sku: '076280002607', name: 'Kidney Blend SP-6', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/kidney-blend-sp-6', oi: 'Vegetable Cellulose Capsule and Trace Mineral Complex.', blockers: ['Trace Mineral Complex'] },
  { sku: '076280002768', name: 'Female Hormone Blend Sp-7c', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/female-hormone-blend-sp-7c', oi: 'Vegetable Cellulose Capsule and Trace Mineral Complex.', blockers: ['Trace Mineral Complex'] },
  { sku: '076280002775', name: 'Menopause Blend SP-7D', count: '100 ct', form: 'capsule', url: 'https://www.solaray.com/products/menopause-blend-sp-7d', oi: 'Vegetable Cellulose Capsule, Organic Rice Extract Blend, Calcium Phosphate 3x, Potassium Phosphate 3x, Silica 6x and Silica', blockers: ['Calcium Phosphate 3x', 'Potassium Phosphate 3x', 'Silica 6x'] },
  { sku: '076280002805', name: 'Heart Blend SP-8', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/heart-blend-sp-8', oi: 'Vegetable Cellulose Capsule, Rice Flour, Calcium Fluoride 6x and Magnesium Phosphate 3x.', blockers: ['Calcium Fluoride 6x', 'Magnesium Phosphate 3x'] },
  { sku: '076280008074', name: 'Flaxseed Oil 1000mg', count: '140 ct', form: 'softgel', url: 'https://www.solaray.com/products/flax', oi: 'Gelatin (Bovine), Glycerin, Water, Carob, Rosemary Extract, Ascorbic Acid.', blockers: ['count conflict: Shopify variant title is 140 ct, but the SKU 076280008074 supplement-facts image is named 240ct and prints 80 servings x 3 softgels'] },
  { sku: '076280008111', name: 'DHA Neuromins 100mg', count: '60ct', form: 'softgel', url: 'https://www.solaray.com/products/dha-neuromins', oi: 'Modified Corn Starch (Non-GMO), Glycerin, High Oleic Sunflower Oil, Water, Carrageenan, Sorbitol, Ascorbyl Palmitate (antioxidant), Tocopherols (antioxidant), Natural Flavor, Sunflower Lecithin, Beta Carotene (coloring) and Caramel (coloring).', blockers: ['Carrageenan', 'Caramel (coloring)'] },
  { sku: '076280008401', name: 'Cranactin Cranberry Extract 400mg', count: '60ct', form: 'capsule', url: 'https://www.solaray.com/products/cranactin-cranberry-extract-bacterial-antiadherence-formula-1', oi: 'Vegetable Cellulose Capsule, Maltodextrin (from Non-GMO Corn), Tricalcium Phosphate, Magnesium Hydroxide, Rice Bran Extract, Cellulose, Magnesium Oxide, Vegetable Juice Concentrate and Silica.', blockers: ['Magnesium Oxide', 'Vegetable Juice Concentrate'] },
  { sku: '076280012101', name: 'Dandelion Root 1040mg', count: '100ct', form: '', url: 'https://www.solaray.com/products/dandelion-root', oi: 'Vegetable Cellulose Capsule, Magensium Stearate, and Rice Extract Blend.', blockers: ['Magensium Stearate'] },
  { sku: '076280013405', name: 'Hawthorn Berry 1050mg', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/hawthorn-berry', oi: 'Vegetable Cellulose Capsule and Rice Bran Concentrate.', blockers: ['Rice Bran Concentrate'] },
  { sku: '076280013412', name: 'Hawthorn Berry 1050mg', count: '180ct', form: 'capsule', url: 'https://www.solaray.com/products/hawthorn-berry', oi: 'Vegetable Cellulose Capsule and Rice Bran Concentrate.', blockers: ['Rice Bran Concentrate'] },
  { sku: '076280021158', name: 'Circulation Blend SP-11B', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/circulation-blend-sp-11b', oi: 'Vegetable Cellulose Capsule and Trace Mineral Complex.', blockers: ['Trace Mineral Complex'] },
  { sku: '076280021400', name: 'Nerve Blend SP-14', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/nerve-blend-sp-14', oi: 'Vegetable Cellulose Capsule and Trace Mineral Complex.', blockers: ['Trace Mineral Complex'] },
  { sku: '076280021608', name: 'Prostate Blend Sp-16', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/prostate-blend-sp-16', oi: 'Vegetable Cellulose Capsule and Trace Mineral Complex.', blockers: ['Trace Mineral Complex'] },
  { sku: '076280021707', name: 'Sleep Blend Sp-17', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/sleep-blend-sp-17', oi: 'Vegetable Cellulose Capsule and Trace Mineral Complex.', blockers: ['Trace Mineral Complex'] },
  { sku: '076280022605', name: 'Thyroid Blend SP-31', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/thyroid-blend-sp-26', oi: 'Vegetable Cellulose Capsule and Trace Mineral Complex.', blockers: ['Trace Mineral Complex'] },
  { sku: '076280023008', name: 'Memory Blend SP-30', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/memory-blend-sp-30', oi: 'Vegetable Cellulose Capsule and Trace Mineral Complex.', blockers: ['Trace Mineral Complex'] },
  { sku: '076280030204', name: 'Arabinogalactan, Larch Tree Extract 300mg', count: '60ct', form: '', url: 'https://www.solaray.com/products/arabinogalactan-larch-tree-extract', oi: 'Vegetable Cellulose Capsule, Cassava Flour, Organic Rice Extract Blend and Silica.', blockers: ['Cassava Flour'] },
  { sku: '076280030693', name: 'Asparagus Rhizome Extract 175mg', count: '60ct', form: 'capsule', url: 'https://www.solaray.com/products/asparagus-rhizome-extract', oi: 'Vegetable Cellulose Capsule, Cassava Flour, Organic Rice Extract Blend and Maltodextrin (from Non-GMO Tapioca).', blockers: ['Cassava Flour'] },
  { sku: '076280031577', name: 'GlucoReg, Blood Glucose Support', count: '30ct', form: 'capsule', url: 'https://www.solaray.com/products/glucoreg-blood-glucose-support', oi: 'Fenugreek Seeds, Vegetable Cellulose Capsule, Stearic Acid and Silica.', blockers: ['Fenugreek Seeds'] },
  { sku: '076280034202', name: 'Feverfew Leaf Extract 400mg', count: '60ct', form: 'capsule', url: 'https://www.solaray.com/products/feverfew-leaf-extract', oi: 'Vegetable Cellulose Capsule, Maltodextrin (from Non-GMO Corn) and Oraanic Rice Extract Blend.', blockers: ['Oraanic Rice Extract Blend'] },
  { sku: '076280036879', name: 'Maca Root Extract 300 mg', count: '60ct', form: 'capsule', url: 'https://www.solaray.com/products/maca-root-extract', oi: 'Vegetable Cellulose Capsule, Dextrin (from Non-GMO Maca), Cellulose, Organic Rice Extract Blend and Silica.', blockers: ['Dextrin (from Non-GMO Maca)'] },
  { sku: '076280037586', name: 'Phytoestrogen', count: '120ct', form: '', url: 'https://www.solaray.com/products/phytoestrogen', oi: 'Vegetable Cellulose Capsule, Maltodextrin, Magnesium Stearate, Ginger Root, Licorice Root, Saw Palmetto Berry and Pygeum Bark Extract.', blockers: ['Ginger Root', 'Licorice Root', 'Saw Palmetto Berry', 'Pygeum Bark Extract'] },
  { sku: '076280037692', name: 'Pygeum & Saw Palmetto w/CranActin', count: '90ct', form: 'capsule', url: 'https://www.solaray.com/products/pygeum-saw-palmetto-w-cran', oi: 'Vegetable Cellulose Capsule, Pumpkin Seeds, Cellulose, Beet Root, Magnesium Hydroxide, TriCalcium Phosphate, Magnesium Stearate, Glycine, L-Alanine and Glutamic Acid HCl.', blockers: ['Pumpkin Seeds', 'L-Alanine', 'Glutamic Acid HCl'] },
  { sku: '076280041309', name: 'Vitamin A, Dry Form 7500mcg', count: '60ct', form: 'capsule', url: 'https://www.solaray.com/products/vitamin-a-dry-form', oi: 'Vegetable Cellulose Capsule, Sucrose, Starch, Carrot Juice (root), and Maltodextrin.', blockers: ['Carrot Juice (root)'] },
  { sku: '076280042153', name: 'Vitamin B-Stress', count: '100ct', form: '', url: 'https://www.solaray.com/products/vitamin-b-stress', oi: 'Vegetable Cellulose Capsule, Whole Food Base (Whole Rice Concentrate including Bran, Germ and Polishings, and Aloe Vera Gel), Silica and Magnesium Stearate.', blockers: ['Whole Food Base (Whole Rice Concentrate including Bran, Germ and Polishings, and Aloe Vera Gel)'] },
  { sku: '076280042214', name: 'Vitamin B-Stress AM, Timed-Release', count: '120 ct', form: '', url: 'https://www.solaray.com/products/vitamin-b-stress-am-timed-release', oi: 'Gelatin Capsule, Cellulose, Whole Food Base (Whole Rice Concentrate including the Bran, Polishings and Germ and Aloe Vera Gel), Stearic Acid, Silica and Magnesium Stearate', blockers: ['Whole Food Base (Whole Rice Concentrate including the Bran, Polishings and Germ and Aloe Vera Gel)'] },
  { sku: '076280042313', name: 'Vitamin B-Stress PM', count: '120ct', form: '', url: 'https://www.solaray.com/products/vitamin-b-stress-pm', oi: 'Gelatin Capsule, Silica, Magnesium Stearate, Cellulose, Chamomile (flowering tops), Peppermint Leaves, Bioflavonoid Concentrate and Whole Food Base (Whole Rice Concentrate including the bran, germ and polishings and Aloe Vera Gel).', blockers: ['Chamomile (flowering tops)', 'Peppermint Leaves', 'Bioflavonoid Concentrate', 'Whole Food Base (Whole Rice Concentrate including the bran, germ and polishings and Aloe Vera Gel)'] },
  { sku: '076280042429', name: 'Mega Vitamin B-Stress, Timed-Release', count: '240ct', form: '', url: 'https://www.solaray.com/products/mega-vitamin-b-stress-timed-release', oi: 'Cellulose, Vegetable Cellulose Capsule, Whole Food Base (Whole Rice Concentrate including the Bran, Polishings and Germ, Pure Aloe Vera Gel), Stearic Acid, Silica and Magnesium Stearate.', blockers: ['Whole Food Base (Whole Rice Concentrate including the Bran, Polishings and Germ, Pure Aloe Vera Gel)'] },
  { sku: '076280042719', name: 'Vitamin B-Complex 50mg', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/vitamin-b-complex-50', oi: 'Vegetable Cellulose Capsule, Whole Food Base (Whole Rice Concentrate and Aloe Vera Gel), Magnesium Stearate and Silica.', blockers: ['Whole Food Base (Whole Rice Concentrate and Aloe Vera Gel)'] },
  { sku: '076280042917', name: 'Vitamin B-Complex 75, Timed-Release', count: '100 ct', form: '', url: 'https://www.solaray.com/products/vitamin-b-complex-timed-release', oi: 'Vegetable Cellulose Capsule, Cellulose, Whole Food Base (Whole Rice Concentrate including the Bran, Polishings and Germ, Aloe Vera Gel), Silica, Magnesium Stearate, Stearic Acid and Magnesium Oxide.', blockers: ['Whole Food Base (Whole Rice Concentrate including the Bran, Polishings and Germ, Aloe Vera Gel)', 'Magnesium Oxide'] },
  { sku: '076280043037', name: 'Vitamin B-Complex 100', count: '250ct', form: '', url: 'https://www.solaray.com/products/vitamin-b-complex-100', oi: 'Vegetable Cellulose Capsule, Magnesium Stearate, Silica, and Whole Food Base (Aloe Vera Gel, Whole Rice Concentrate including Bran, Germ, and Polishings).', blockers: ['Whole Food Base (Aloe Vera Gel, Whole Rice Concentrate including Bran, Germ, and Polishings)'] },
  { sku: '076280043259', name: 'Vitamin B-1, 100mg', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/vitamin-b-1', oi: 'Whole Food Base (Whole Rice Concentrate including the Bran, Polishings and Germ), Vegetable Cellulose Capsule and Organic Rice Extract Blend.', blockers: ['Whole Food Base (Whole Rice Concentrate including the Bran, Polishings and Germ)'] },
  { sku: '076280043273', name: 'Vitamin B-2 (Riboflavin) 100mg', count: '100ct', form: '', url: 'https://www.solaray.com/products/vitamin-b-2', oi: 'Whole Food Base (Whole Rice Concentrate including the Bran, Polishings and Germ, and Pure Aloe Vera Gel), Vegetable Cellulose Capsule and Silica.', blockers: ['Whole Food Base (Whole Rice Concentrate including the Bran, Polishings and Germ, and Pure Aloe Vera Gel)'] },
  { sku: '076280043525', name: 'Folic Acid (Vitamin B-9)', count: '', form: 'capsule', url: 'https://www.solaray.com/products/folic-acid-vitamin-b-9', oi: 'Whole Rice Concentrate, Vegetable Cellulose Capsule and Aloe Vera Gel (200x dry concentrate).', blockers: ['Aloe Vera Gel (200x dry concentrate)'] },
  { sku: '076280043594', name: 'Niacin 100mg', count: '', form: 'capsule', url: 'https://www.solaray.com/products/niacin', oi: 'Whole Rice Concentrate (Including Bran, Polishings, and Germ) Vegetable Cellulose Capsule and Aloe Vera Gel.', blockers: ['Whole Rice Concentrate (Including Bran, Polishings, and Germ) Vegetable Cellulose Capsule'] },
  { sku: '076280043655', name: 'Niacinamide 500mg', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/niacinamide', oi: 'Vegetable Cellulose Capsule, Whole Rice Concentrate (Including Bran, Polishings, and Germ, and Aloe Vera Gel).', blockers: ['Whole Rice Concentrate (Including Bran, Polishings, and Germ, and Aloe Vera Gel)'] },
  { sku: '076280043709', name: 'Pantothenic Acid', count: '', form: '', url: 'https://www.solaray.com/products/pantothenic-acid-1', oi: 'Gelatin Capsule, Whole Food Base (Whole Rice Concentrate including the Kernel, Polishings, and Hull, and Aloe Vera Gel) and Magnesium Stearate.', blockers: ['Whole Food Base (Whole Rice Concentrate including the Kernel, Polishings, and Hull, and Aloe Vera Gel)'] },
  { sku: '076280043815', name: 'Pantothenic Acid 500mg', count: '250ct', form: 'capsule', url: 'https://www.solaray.com/products/pantothenic-acid', oi: 'Vegetable Cellulose Capsule, Magnesium Stearate, Rice Extract Blend, Rice Flour, Aloe Vera Gel. Discussion: Pantothenic acid, also known as vitamin B5, is an essential nutrient. It also supports cellular energy metabolism and nerve function.*', blockers: ['Aloe Vera Gel. Discussion: Pantothenic acid', 'also known as vitamin B5', 'is an essential nutrient. It also supports cellular energy metabolism', 'nerve function.*'] },
  { sku: '076280043853', name: 'Vitamin C 800mg, Buffered', count: '90 ct', form: 'capsule', url: 'https://www.solaray.com/products/vitamin-c-w-rose-hips-buffered', oi: 'Vegetable Cellulose Capsule, Magnesium Stearate, Whole Food Base (Rose Hips, Acerola Cherry and Bioflavonoid Concentrate).', blockers: ['Whole Food Base (Rose Hips, Acerola Cherry and Bioflavonoid Concentrate)'] },
  { sku: '076280044607', name: 'Super Bio Vitamin C 1000mg', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/super-bio-vitamin-c-buffered-two-stage-timed-release', oi: 'Vegetable Cellulose Capsule, Magnesium Stearate, Silica, Stearic Acid, Buffering Base (Calcium Carbonate and Magnesium Oxide).', blockers: ['Buffering Base (Calcium Carbonate and Magnesium Oxide)'] },
  { sku: '076280044614', name: 'Super Bio Vitamin C 1000mg', count: '250ct', form: 'capsule', url: 'https://www.solaray.com/products/super-bio-vitamin-c-buffered-two-stage-timed-release', oi: 'Vegetable Cellulose Capsule, Magnesium Stearate, Silica, Stearic Acid, Buffering Base  (Calcium Carbonate and Magnesium Oxide).  Discussion: Vitamin C is a powerful antioxidant and is intended to support a healthy immune system.t', blockers: ['Buffering Base (Calcium Carbonate and Magnesium Oxide). Discussion: Vitamin C is a powerful antioxidant', 'is intended to support a healthy immune system.t'] },
  { sku: '076280044621', name: 'Super Bio Vitamin C 1000mg', count: '360ct', form: 'capsule', url: 'https://www.solaray.com/products/super-bio-vitamin-c-buffered-two-stage-timed-release', oi: 'Vegetable Cellulose Capsule, Magnesium Stearate, Silica, Stearic Acid and Buffering Base (Calcium Carbonate and Magnesium Oxide).', blockers: ['Buffering Base (Calcium Carbonate and Magnesium Oxide)'] },
  { sku: '076280044904', name: 'Vitamin C 500mg', count: '100ct / Cherry', form: 'gummy', url: 'https://www.solaray.com/products/vitamin-c', oi: 'Sorbitol, Fructose, Xylitol, Cellulose, Natural Cherry Flavor with  other Natural Flavors, Stearic Acid, Beet Root Juice (for color), Acacia Gum, Stevia (leaf  extract), Magnesium Stearate, Silica, Rose Hips (fruit), Calcium Silicate, Acerola (fruit juice).', blockers: ['Rose Hips (fruit)', 'Acerola (fruit juice)'] },
  { sku: '076280045109', name: 'Mega Multi Mineral', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/multi-mineral', oi: 'Gelatin Capsule, Cellulose, Magnesium Stearate, Parsley, Alfalfa Leaf, Horsetail, Watercress, Dandelion Root, Yellow Dock Root and Chamomile.', blockers: ['Parsley', 'Alfalfa Leaf', 'Horsetail', 'Watercress', 'Dandelion Root', 'Yellow Dock Root', 'Chamomile'] },
  { sku: '076280045116', name: 'Mega Multi Mineral', count: '200ct', form: 'capsule', url: 'https://www.solaray.com/products/mega-multi-mineral', oi: 'Gelatin Capsule, Cellulose, Magnesium Stearate, Parsley, Alfalfa Leaf,  Horsetail, Watercress, Dandelion Root, Yellow Dock Root and Chamomile.', blockers: ['Parsley', 'Alfalfa Leaf', 'Horsetail', 'Watercress', 'Dandelion Root', 'Yellow Dock Root', 'Chamomile'] },
  { sku: '076280045130', name: 'Mega Multi Mineral, Iron-Free', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/mega-multi-mineral-iron-free', oi: 'Gelatin Capsule, Rice Protein, Citric Acid (from Non-GMO Tapioca),  Cellulose, Magnesium Stearate, Parsley Leaf, Alfalfa Leaf, Horsetail,  Watercress, Dandelion Root, Yellow Dock Root, Chamomile and Kelp.', blockers: ['Parsley Leaf', 'Alfalfa Leaf', 'Horsetail', 'Watercress', 'Dandelion Root', 'Yellow Dock Root', 'Chamomile', 'Kelp'] },
  { sku: '076280045147', name: 'Mega Multi Mineral, Iron-Free', count: '200ct', form: 'capsule', url: 'https://www.solaray.com/products/mega-multi-mineral-iron-free', oi: 'Gelatin Capsule, Rice Protein, Citric Acid (from Non-GMO Tapioca), Cellulose, Magnesium Stearate, Parsley Leaf, Alfalfa Leaf, Horsetail, Watercress, Dandelion Root, Yellow Dock Root, Chamomile and Kelp.', blockers: ['Parsley Leaf', 'Alfalfa Leaf', 'Horsetail', 'Watercress', 'Dandelion Root', 'Yellow Dock Root', 'Chamomile', 'Kelp'] },
  { sku: '076280045161', name: 'Magnesium Potassium Bromelain', count: '60ct', form: 'capsule', url: 'https://www.solaray.com/products/magnesium-potassium-asporotate', oi: 'Vegetable Cellulose Capsule, Arabic Gum, Magnesium Stearate, Maltodextrin,  Silica, and Cellulose.  Aquamin® is a registered trademark of Marigot Ltd. of Cork Ireland.', blockers: ['Cellulose. Aquamin is a registered trademark of Marigot Ltd. of Cork Ireland'] },
  { sku: '076280045178', name: 'Magnesium Potassium Bromelain', count: '120ct', form: 'capsule', url: 'https://www.solaray.com/products/magnesium-potassium-asporotate', oi: 'Vegetable Cellulose Capsule, Arabic Gum, Magnesium Stearate, Maltodextrin, Silica, and Cellulose. Aquamin® is a registered trademark of Marigot Ltd. of Cork Ireland.', blockers: ['Cellulose. Aquamin is a registered trademark of Marigot Ltd. of Cork Ireland'] },
  { sku: '076280045239', name: 'Calcium & Magnesium Citrate With Vitamin D-2, 1:1', count: '90ct', form: 'capsule', url: 'https://www.solaray.com/products/calcium-magnesium-citrate-with-vitamin-d-2-1-1-ratio', oi: 'Vegetable Cellulose Capsule, Magnesium Stearate, Parsley Leaf, Watercress, Alfalfa Leaf and Dandelion Root.', blockers: ['Parsley Leaf', 'Watercress', 'Alfalfa Leaf', 'Dandelion Root'] },
  { sku: '076280045246', name: 'Calcium & Magnesium Citrate, 1:1 Ratio', count: '90ct', form: 'capsule', url: 'https://www.solaray.com/products/calcium-magnesium-citrate-1-1-ratio', oi: 'Vegetable Cellulose Capsule, Magnesium Stearate, Parsley Leaf, Watercress Leaf, Alfalfa Leaf and Dandelion Root.', blockers: ['Parsley Leaf', 'Watercress Leaf', 'Alfalfa Leaf', 'Dandelion Root'] },
  { sku: '076280045253', name: 'Calcium & Magnesium Citrate', count: '180ct', form: 'capsule', url: 'https://www.solaray.com/products/calcium-magnesium-citrate', oi: 'Vegetable Cellulose Capsule, Magnesium Stearate, Parsley Leaf, Watercress Leaf, Alfalfa Leaf and Dandelion Root.', blockers: ['Parsley Leaf', 'Watercress Leaf', 'Alfalfa Leaf', 'Dandelion Root'] },
  { sku: '076280045260', name: 'Calcium & Magnesium Citrate, With Vitamin D-2, 2:1 Ratio', count: '90ct', form: 'capsule', url: 'https://www.solaray.com/products/calcium-magnesium-citrate-with-vitamin-d-2-2-1-ratio', oi: 'Vegetable Cellulose Capsule, Cellulose, Magnesium Stearate. Parslev Leaf. Alfalfa Leaf. Watercress Leaf and Dandelion Root.', blockers: ['Magnesium Stearate. Parslev Leaf. Alfalfa Leaf. Watercress Leaf', 'Dandelion Root'] },
  { sku: '076280045277', name: 'Cal-Mag Citrate w/D-2, 2:1 Ratio', count: '180ct', form: 'capsule', url: 'https://www.solaray.com/products/cal-mag-citrate-w-d-2-2-1-ratio', oi: 'Vegetable Cellulose Capsule, Cellulose, Magnesium Stearate, Parsley Leaf, Alfalfa Leaf, Watercress Leaf and Dandelion Root.', blockers: ['Parsley Leaf', 'Alfalfa Leaf', 'Watercress Leaf', 'Dandelion Root'] },
  { sku: '076280045291', name: 'Calcium Citrate Supreme, Bone', count: '180ct', form: 'capsule', url: 'https://www.solaray.com/products/calcium-citrate-supreme-bone', oi: 'Gelatin Capsule, Magnesium Stearate, Whole Rice Concentrate (including Kernel, Polishings, and Hull), Cellulose, Citric Acid, Lysine, Aspartic Acid, Glycine, Alfalfa Leaf, Watercress, Dandelion Root and Parsley Leaf.', blockers: ['Lysine', 'Aspartic Acid', 'Alfalfa Leaf', 'Watercress', 'Dandelion Root', 'Parsley Leaf'] },
  { sku: '076280045314', name: 'Calcium & Magnesium, AAC 2:1', count: '180ct', form: 'capsule', url: 'https://www.solaray.com/products/calcium-magnesium-amino-acid-chelate-2-1-ratio', oi: 'Vegetable Cellulose Capsule, Cellulose, Citric Acid (from Non-GMO Tapioca), L-Aspartic Acid, Magnesium Stearate, Whole Rice Concentrate, Rice Protein, Alfalfa Aerial, Dandelion Root, Watercress Leaf and Parsley Aerial.', blockers: ['L-Aspartic Acid', 'Alfalfa Aerial', 'Dandelion Root', 'Watercress Leaf', 'Parsley Aerial'] },
  { sku: '076280045345', name: 'Calcium & Magnesium Amino Acid', count: '90ct', form: 'capsule', url: 'https://www.solaray.com/products/calcium-magnesium-amino-acid', oi: 'Gelatin Capsule, Cellulose, Whole Rice Concentrate, Rice Protein, Magnesium Stearate, Silica, Alfalfa Leaf, Watercress Leaf, Dandelion Root and Parsley Herb.', blockers: ['Alfalfa Leaf', 'Watercress Leaf', 'Dandelion Root', 'Parsley Herb'] },
  { sku: '076280045604', name: 'Calcium, Magnesium, Zinc', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/calcium-magnesium-zinc', oi: 'Vegetable Cellulose Capsule, Magnesium Stearate, Whole Rice Concentrate (including the Bran, Polishings and Germ), Alfalfa Leaf, Watercress, Dandelion Root and Parsley Leaf.', blockers: ['Alfalfa Leaf', 'Watercress', 'Dandelion Root', 'Parsley Leaf'] },
  { sku: '076280045611', name: 'Calcium, Magnesium, Zinc', count: '250ct', form: 'capsule', url: 'https://www.solaray.com/products/calcium-magnesium-zinc', oi: 'Vegetable Cellulose Capsule, Magnesium Stearate, Whole Rice Concentrate (including the Bran, Polishings and Germ), Alfalfa leaf, Watercress, Dandelion Root and Parsley Leaf.', blockers: ['Alfalfa leaf', 'Watercress', 'Dandelion Root', 'Parsley Leaf'] },
  { sku: '076280045833', name: 'Calcium Citrate With Vitamin D-3 1000mg', count: '90ct', form: 'capsule', url: 'https://www.solaray.com/products/calcium-citrate-with-vitamin-d-3', oi: 'Gelatin Capsule, Magnesium Stearate, Watercress Leaf, Dandelion Root and Parsley Leaf.', blockers: ['Watercress Leaf', 'Dandelion Root', 'Parsley Leaf'] },
  { sku: '076280045840', name: 'Calcium Citrate Chewables - Orange 1000mg', count: 'Orange / 60ct', form: '', url: 'https://www.solaray.com/products/calcium-citrate-chewables-orange', oi: 'Sorbitol, Orange Juice Powder, Cellulose, Citric Acid, Guar Gum, Stearic Acid, Silica, Natural Orange Flavor with other Natural Flavors and Stevia.', blockers: ['Orange Juice Powder'] },
  { sku: '076280045857', name: 'Calcium Citrate 1000mg', count: '120ct', form: 'capsule', url: 'https://www.solaray.com/products/calcium-citrate', oi: 'Vegetable Cellulose Capsule, Magnesium Stearate, Watercress Leaf, Dandelion Root and Parsley Leaf.', blockers: ['Watercress Leaf', 'Dandelion Root', 'Parsley Leaf'] },
  { sku: '076280045901', name: 'GTF Chromium 200mcg', count: '100ct', form: '', url: 'https://www.solaray.com/products/gtf-chromium', oi: 'Brewer\'s Yeast, Vegetable Cellulose Capsule and Magnesium Stearate.', blockers: ['Brewer\'s Yeast'] },
  { sku: '076280045963', name: 'Copper Citrate 2mg', count: '60ct', form: 'capsule', url: 'https://www.solaray.com/products/copper-citrate', oi: 'Whole Rice Concentrate, Vegetable Cellulose Capsule, Dandelion Root, Watercress Leaf, Horsetail Herb, Yellow Dock Root, Rice Bran Extract and Silica.', blockers: ['Dandelion Root', 'Watercress Leaf', 'Horsetail Herb', 'Yellow Dock Root'] },
  { sku: '076280046007', name: 'Iron Asporotate 18mg', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/iron-asporotate', oi: 'Yellowdock Root, Parsley Herb, Gelatin Capsule, Whole Rice Concentrate, Magnesium Oxide and Magnesium Stearate.', blockers: ['Yellowdock Root', 'Parsley Herb', 'Magnesium Oxide'] },
  { sku: '076280046205', name: 'Magnesium Asporotate 400mg', count: '60ct', form: 'capsule', url: 'https://www.solaray.com/products/magnesium-asporotate', oi: 'Vegetable Cellulose Capsule, Magnesium Stearate, Rice Flour and Herb Base (Parsley Leaf, Alfalfa Leaf)', blockers: ['Herb Base (Parsley Leaf, Alfalfa Leaf)'] },
  { sku: '076280046212', name: 'Magnesium Asporotate 400mg', count: '120ct', form: 'capsule', url: 'https://www.solaray.com/products/magnesium-asporotate', oi: 'Vegetable Cellulose Capsule, Magnesium Stearate, Rice Flour and Herb Base (Parsley Leaf, Organic Alfalfa Leaf).', blockers: ['Herb Base (Parsley Leaf, Organic Alfalfa Leaf)'] },
  { sku: '076280046304', name: 'Magnesium, Amino Acid Chelate 200mg', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/magnesium-amino-acid-chelate', oi: 'Vegetable Cellulose Capsule, Magnesium Stearate, Organic Alfalfa, Parsley, and Citric Acid.', blockers: ['Organic Alfalfa', 'Parsley'] },
  { sku: '076280046502', name: 'Manganese 50mg', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/manganese', oi: 'Whole Food Base (Whole Rice Concentrate including Bran, Germ and Polishings), Vegetable Cellulose Capsule, Magnesium Stearate, Rice Flour, Watercress and Parsley Leaf.', blockers: ['Whole Food Base (Whole Rice Concentrate including Bran, Germ and Polishings)', 'Watercress', 'Parsley Leaf'] },
  { sku: '076280046601', name: 'Potassium Asporotate 99mg', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/potassium-asporotate', oi: 'Gelatin Capsule, Herb Base (Parsley Leaf, Chamomile, Watercress) and Magnesium Stearate.', blockers: ['Herb Base (Parsley Leaf, Chamomile, Watercress)'] },
  { sku: '076280046700', name: 'Potassium 99mg', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/potassium-99', oi: 'Vegetable Cellulose Capsule, Rice Flour, Citric Acid, Magnesium Stearate, Parsley, Chamomile and Watercress.', blockers: ['Parsley', 'Chamomile', 'Watercress'] },
  { sku: '076280046809', name: 'Selenium 50mcg', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/selenium-50', oi: 'Nutritional Yeast, Gelatin Capsule and Magnesium Stearate.', blockers: ['Nutritional Yeast'] },
  { sku: '076280046908', name: 'Selenium 100mcg', count: '100', form: 'capsule', url: 'https://www.solaray.com/products/selenium-100', oi: 'Nutritional Yeast, Vegetable Cellulose Capsule and Silica.', blockers: ['Nutritional Yeast'] },
  { sku: '076280046953', name: 'Selenium 200mcg', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/selenium-200', oi: 'Nutritional Yeast, Vegetable Cellulose Capsule and Magnesium Stearate.', blockers: ['Nutritional Yeast'] },
  { sku: '076280047004', name: 'Zinc Asporotate 15mg', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/zinc-asporotate', oi: 'Vegetable Cellulose Capsule, Cellulose, Rice Flour, Calcium Silicate, Rice Bran Extract and Magnesium Oxide.', blockers: ['Magnesium Oxide'] },
  { sku: '076280047721', name: 'Mega-Mineral Multivitamin', count: '120ct', form: 'capsule', url: 'https://www.solaray.com/products/mega-mineral-multi-vitamin', oi: 'Gelatin Capsule, Eleuthero Root, Cellulose, Magnesium Stearate, Whole Rice  Concentrate (including the Bran, Polishings and Germ), Silica, Carrot Juice.', blockers: ['Carrot Juice'] },
  { sku: '076280047813', name: 'Spectro Multivitamin', count: '100ct', form: '', url: 'https://www.solaray.com/products/spectro-multi-vitamin', oi: 'Gelatin Capsule, Eleuthero Root, Magnesium Stearate, Stearic Acid, Cellulose, Maltodextrin, Whole Rice Concentrate, Alfalfa Leaf, Montmorillonite Clay, Rose Hips and Acerola Cherry.', blockers: ['Alfalfa Leaf', 'Montmorillonite Clay', 'Rose Hips', 'Acerola Cherry'] },
  { sku: '076280047820', name: 'Spectro Multivitamin', count: '250ct', form: 'capsule', url: 'https://www.solaray.com/products/spectro-multi-vitamin', oi: 'Gelatin Capsule, Eleuthero Root, Magnesium Stearate, Stearic Acid, Cellulose, Maltodextrin, Whole Rice Concentrate, Alfalfa Leaf, Montmorillonite Clay, Rose Hips and Acerola Cherry.', blockers: ['Alfalfa Leaf', 'Montmorillonite Clay', 'Rose Hips', 'Acerola Cherry'] },
  { sku: '076280047837', name: 'Spectro Multivitamin', count: '360ct', form: 'capsule', url: 'https://www.solaray.com/products/spectro-multi-vitamin', oi: 'Gelatin Capsule, Eleuthero Root, Magnesium Stearate, Stearic Acid, Cellulose, Maltodextrin, Whole Rice Concentrate, Alfalfa Leaf, Montmorillonite Clay, Rose Hips and Acerola Cherry.', blockers: ['Alfalfa Leaf', 'Montmorillonite Clay', 'Rose Hips', 'Acerola Cherry'] },
  { sku: '076280047851', name: 'Spectro Multivitamin, Iron-Free', count: '250ct', form: 'capsule', url: 'https://www.solaray.com/products/spectro-multi-vitamin-iron-free', oi: 'Gelatin Capsule, Eleuthero Root, Magnesium Stearate, Cellulose, Stearic Acid, Maltodextrin, Whole Rice Concentrate, Alfalfa Leaf, Montmorillonite Clay, Rose Hips and Acerola Cherry.', blockers: ['Alfalfa Leaf', 'Montmorillonite Clay', 'Rose Hips', 'Acerola Cherry'] },
  { sku: '076280047875', name: 'Baby Me Now Prenatal Multivitamin', count: '150ct', form: 'tablet', url: 'https://www.solaray.com/products/baby-me-now-prenatal-multi-vitamin-original-formula', oi: 'Cellulose, Croscarmellose Sodium, Magnesium Stearate, Carrot Juice and Acerola Cherry.', blockers: ['Carrot Juice', 'Acerola Cherry'] },
  { sku: '076280047905', name: 'Hair Nutrients', count: '60ct', form: 'capsule', url: 'https://www.solaray.com/products/hair-nutrients', oi: 'Vegetable Cellulose Capsule, Rice Flour, Cellulose, Croscarmellose Sodium, Silica, Magnesium Stearate, Alfalfa Leaf, Parsley Leaf and Watercress Leaf.', blockers: ['Alfalfa Leaf', 'Parsley Leaf', 'Watercress Leaf'] },
  { sku: '076280048605', name: 'L-Lysine 1000mg', count: '90ct', form: 'tablet', url: 'https://www.solaray.com/products/l-lysine-1000mg', oi: 'Cellulose, Stearic Acid, Acerola Cherry, Rose Hips, Magnesium Stearate and Rice Concentrate.', blockers: ['Acerola Cherry', 'Rose Hips', 'Rice Concentrate'] },
  { sku: '076280051803', name: 'Pituitary Caps, Freeze-Dried', count: '60ct', form: 'capsule', url: 'https://www.solaray.com/products/pituitary-caps-freeze-dried', oi: 'Gelatin Capsule and Trace Mineral Complex.', blockers: ['Trace Mineral Complex'] },
  { sku: '076280081008', name: 'Cool Cayenne Pepper 40,000 Hu', count: '90ct', form: 'capsule', url: 'https://www.solaray.com/products/cool-cayenne-pepper-40-000-hu', oi: 'Cellulose, Vegetable Cellulose Capsule, Annatto (seed extract), Ginger (root) and Guar Gum.', blockers: ['Ginger (root)'] },
  { sku: '076280081015', name: 'Cool Cayenne Pepper 40,000 Hu', count: '180ct', form: 'capsule', url: 'https://www.solaray.com/products/cool-cayenne-pepper-40-000-hu', oi: 'Cellulose, Vegetable Cellulose Capsule, Annatto (seed extract), Ginger (root) and Guar Gum.', blockers: ['Ginger (root)'] },
  { sku: '076280081022', name: 'Extra Hot Cool Cayenne Pepper 100,000 Hu', count: '90ct', form: 'capsule', url: 'https://www.solaray.com/products/extra-hot-cool-cayenne-pepper-100-000-hu', oi: 'Cellulose, Vegetable Cellulose Capsule, Annatto (seed extract), Ginger Root and Guar Gum.', blockers: ['Ginger Root'] },
  { sku: '076280081039', name: 'Cool Cayenne Pepper 40,000 HU', count: '90ct', form: 'capsule', url: 'https://www.solaray.com/products/cool-cayenne-pepper-40000-hu', oi: 'Vegetable Cellulose Capsule, Cellulose, Annatto (seed extract), Ginger Root and Guar Gum.', blockers: ['Ginger Root'] },
  { sku: '076280081305', name: 'Capryl, Caprylic Acid Formula', count: '100ct', form: 'capsule', url: 'https://www.solaray.com/products/capryl-caprylic-acid-formula', oi: 'Vegetable Fiber, Vegetable Cellulose Capsule and Magnesium Stearate.', blockers: ['Vegetable Fiber'] },
  { sku: '076280081329', name: 'Yeast-Cleanse', count: '90ct', form: 'capsule', url: 'https://www.solaray.com/products/yeast-cleanse', oi: 'Vegetable Cellulose Capsule, Whole Rice Concentrate, Silica, Dong Quai Root, Fennel Seed, Neem Leaf, Glycerin, Magnesium Stearate.', blockers: ['Dong Quai Root', 'Fennel Seed', 'Neem Leaf'] },
  { sku: '076280081381', name: 'Yeast-Cleanse', count: '180ct', form: 'capsule', url: 'https://www.solaray.com/products/yeast-cleanse', oi: 'Vegetable Cellulose Capsule, Whole Rice Concentrate, Silica, Dong Quai Root, Fennel Seed, Neem Leaf, Glycerin, Magnesium Stearate.', blockers: ['Dong Quai Root', 'Fennel Seed', 'Neem Leaf'] },
  { sku: '076280082074', name: 'Ginger Trips', count: '60ct / Ginger Molasses', form: 'gummy', url: 'https://www.solaray.com/products/ginger-trips', oi: 'Molasses, Honey, Cellulose, Stearic Acid, Acacia Gum, Silica and Magnesium Stearate.', blockers: ['Molasses'] },
  { sku: '076280082524', name: 'Oil Of Oregano 150mg', count: '60ct', form: '', url: 'https://www.solaray.com/products/oil-of-oregano', oi: 'Softgel (Non-GMO Tapioca Starch, Non-GMO Glycerin and Water) and live Oil.', blockers: ['Softgel (Non-GMO Tapioca Starch, Non-GMO Glycerin and Water)', 'live Oil'] },
  { sku: '076280083620', name: 'Total Cleanse Colon', count: '60 ct / Veg Cap', form: 'capsule', url: 'https://www.solaray.com/products/total-cleanse-colon', oi: 'vegetable Cellulose Capsule, Croscarmellose Sodium, Cellulose, Magnesium Citrate and Silica.', blockers: ['Magnesium Citrate'] },
  { sku: '076280083866', name: 'Cardio Complete, Cardiovascular', count: '90ct', form: 'capsule', url: 'https://www.solaray.com/products/cardiocomplete-cardiovascular', oi: 'Vegetable Cellulose Capsule, Cellulose, Maltodextrin, Magnesium Carbonate, Magnesium Oxide, Magnesium Stearate, Corn Starch and Silica.', blockers: ['Magnesium Carbonate', 'Magnesium Oxide'] },
  { sku: '076280083996', name: 'CranActin Cranberry Extract 400mg', count: '30ct', form: 'capsule', url: 'https://www.solaray.com/products/cranactin-cranberry-extract', oi: 'Vegetable Cellulose Capsule, Maltodextrin (from Non-GMO Corn), Tricalcium Phosphate, Magnesium Hydroxide, Rice Bran Extract, Cellulose, Magnesium Oxide, Vegetable Juice Concentrate and Silica.', blockers: ['Magnesium Oxide', 'Vegetable Juice Concentrate'] },
  { sku: '076280088618', name: 'Total Calm, Mood Support', count: '30ct', form: 'capsule', url: 'https://www.solaray.com/products/total-calm-mood-support', oi: 'Modified Food and Corn Starch, Vegetable Cellulose Capsule, Cellulose, Silica and Magnesium Stearate.', blockers: ['Modified Food'] },
  { sku: '076280103489', name: 'Resveratrol, Japanese Knotweed 75mg', count: '60ct', form: 'capsule', url: 'https://www.solaray.com/products/resveratrol-japanese-knotweed', oi: 'Cellulose, Vegetable Cellulose Capsule, Organic Rice Extract Blend, Silica and Maltodex- trin (from Non-GMO Corn).', blockers: ['Maltodex- trin (from Non-GMO Corn)'] },
  { sku: '076280114836', name: 'Hyaluronic Acid 60mg', count: '30ct', form: 'capsule', url: 'https://www.solaray.com/products/3x-strength-hyaluronic-acid', oi: 'Cellulose, Vegetable Cellulose Capsule, Glycerol Triacetate, Silica and Magnesium Stearate.', blockers: ['Glycerol Triacetate'] },
  { sku: '076280121094', name: 'Biocitrate Potassium 99mg', count: '60ct', form: 'capsule', url: 'https://www.solaray.com/products/biocitrate-potassium', oi: 'Rice Flour, Vegetable Cellulose Capsule, Parsley Leaf, Celery Seed, Dandelion Root, Magnesium Stearate, Watercress Leaf and Oat Straw Stem.', blockers: ['Parsley Leaf', 'Celery Seed', 'Dandelion Root', 'Watercress Leaf', 'Oat Straw Stem'] },
  { sku: '076280131758', name: 'Cal-Mag Citrate w/D-2, 2:1 Ratio', count: '360ct', form: 'capsule', url: 'https://www.solaray.com/products/cal-mag-citrate-w-d-2-2-1-ratio', oi: 'Vegetable Cellulose Capsule, Cellulose, Magnesium Stearate, Parsley  Leaf, Alfalfa Leaf, Watercress Leaf and Dandelion Root.', blockers: ['Parsley Leaf', 'Alfalfa Leaf', 'Watercress Leaf', 'Dandelion Root'] },
  { sku: '076280131765', name: 'Calcium Citrate With Vitamin D-3 1000mg', count: '240ct', form: 'capsule', url: 'https://www.solaray.com/products/calcium-citrate-with-vitamin-d-3', oi: 'Gelatin Capsule, Magnesium Stearate, Watercress Leaf, Dandelion Root and Parsley Leaf. Discussion: Calcium is intended to support healthy bones and teeth. A speical base of herbs has been included for additional nutritive support.*', blockers: ['Watercress Leaf', 'Dandelion Root', 'Parsley Leaf. Discussion: Calcium is intended to support healthy bones', 'teeth. A speical base of herbs has been included for additional nutritive support.*'] },
  { sku: '076280132236', name: 'Magnesium Asporotate 400mg', count: '180ct', form: 'capsule', url: 'https://www.solaray.com/products/magnesium-asporotate', oi: 'Vegetable Cellulose Capsule, Magnesium Stearate, Rice Flour and Herb Base (Parsley Leaf, Organic Alfalfa Leaf).', blockers: ['Herb Base (Parsley Leaf, Organic Alfalfa Leaf)'] },
  { sku: '076280146714', name: 'Immufight Maximum Daily Defense', count: '90ct', form: 'capsule', url: 'https://www.solaray.com/products/immufight-maximum-daily-defense', oi: 'Vegetable Cellulose Capsule, Cellulose, Stearic Acid, Calcium Threonate, Silica and Tapioca Starch.', blockers: ['Calcium Threonate'] },
  { sku: '076280149074', name: 'Vegan Collagen Booster', count: '', form: 'powder', url: 'https://www.solaray.com/products/vegan-collagen-booster', oi: 'Natural Vanilla Flavor with Other Natural Flavors, Sea Salt, Gotu Kola (Centella asiatica) (extract), Steviol Glycoside, Silica, Ginseng (Panax ginseng) (root extract).', blockers: ['Sea Salt', 'Gotu Kola (Centella asiatica) (extract)', 'Ginseng (Panax ginseng) (root extract)'] },
  { sku: '076280166262', name: 'Reacta-C & Bioflavonoids 500mg', count: '180ct', form: 'capsule', url: 'https://www.solaray.com/products/reacta-c-bioflavonoids', oi: 'Vegetable Cellulose Capsule, Magnesium Stearate,  Calcium L-Threonate and Silica.', blockers: ['Calcium L-Threonate'] },
  { sku: '076280223149', name: 'Triple Strength Tart Cherry Fruit Extract', count: '90ct', form: '', url: 'https://www.solaray.com/products/triple-strength-tart-cherry-fruit-extract', oi: 'Maltodextrin (from Non-GMO Corn), Cellulose, Vegetable Cellulose Capsule. Silica and Oraanic Rice Extract Blend.', blockers: ['Vegetable Cellulose Capsule. Silica', 'Oraanic Rice Extract Blend'] },
  { sku: '076280228786', name: 'Cal-Mag Citrate Vitamin with D-2, 1:3', count: '180ct', form: 'capsule', url: 'https://www.solaray.com/products/cal-mag-citrate-with-d-2-1-3', oi: 'Vegetable Cellulose Capsule, Magnesium Stearate, Parsley Leaf, Watercress Leaf, Alfalfa Leaf and Dandelion Root.', blockers: ['Parsley Leaf', 'Watercress Leaf', 'Alfalfa Leaf', 'Dandelion Root'] },
  { sku: '076280229639', name: 'ProSorb Turmeric 29x 500mg', count: '30 ct', form: 'capsule', url: 'https://www.solaray.com/products/prosorb-turmeric-29x-500mg', oi: 'Cellulose, Sunflower Lecithin, Vegetable Capsule, Magnesium Stearate, Silica.', blockers: ['Vegetable Capsule'] },
  { sku: '076280238396', name: 'Triple Strength Sambuactin', count: '60ct', form: 'tablet', url: 'https://www.solaray.com/products/triple-strength-sambuactin', oi: 'Cellulose, Maltodextrin, Sodium Crosscarmellose, Silica, Magnesium Stearate, Stearic Acid, Bilberry (fruit) and Stevia (leaf).', blockers: ['Bilberry (fruit)'] },
  { sku: '076280262025', name: 'Spectro Energy Multivitamin', count: '120 ct', form: '', url: 'https://www.solaray.com/products/spectro-energy-multi-vitamin', oi: 'Vegetable Cellulose Capsule, Magnesium Stearate, Silica, Cellulose, Rice Flour and Soy Protein Isolate.', blockers: ['Soy Protein Isolate'] },
  { sku: '076280278774', name: 'Triple Strength Vitamin K-2, Mk-7', count: '30ct', form: 'capsule', url: 'https://www.solaray.com/products/triple-strength-vitamin-k-2-mk-7', oi: 'Cellulose, Vegetable Cellulose Capsule, Glycerol Monostearate, Magnesium Stearate, Fermented Defatted Chickpea Flour Extract and Silica.', blockers: ['Fermented Defatted Chickpea Flour Extract'] },
  { sku: '076280279771', name: 'Immufight Immune Response', count: '90ct', form: 'capsule', url: 'https://www.solaray.com/products/immufight-immune-response', oi: 'Cellulose, Vegetable Cellulose Capsule, Stearic Acid, Maltodextrin, Silica, Calcium Threonate and Tapioca Starch.', blockers: ['Calcium Threonate'] },
  { sku: '076280282467', name: 'Activated Broccoli Seed Extract 350mg', count: '30ct', form: 'capsule', url: 'https://www.solaray.com/products/activated-broccoli-seed-extract', oi: 'Vegetable Cellulose Capsule and Calcium Ascorbate.', blockers: ['Calcium Ascorbate'] },
  { sku: '076280321838', name: 'Methyl B-12, Mango Peach - 2500mcg', count: '60 ct / Natural Mango Peach', form: 'capsule', url: 'https://www.solaray.com/products/methyl-b-13', oi: 'Xylitol, Cellulose, Natural Mango and Peach Flavors with other Natural Flavors (Soy), Stearic Acid, Maltodextrin, Turmeric Root Extract, Citric Acid (from Non-GMO Tapioca) and Silica.', blockers: ['Natural Mango', 'Turmeric Root Extract'] },
  { sku: '076280329568', name: 'Plant Melatonin', count: '', form: 'capsule', url: 'https://www.solaray.com/products/plant-melatonin', oi: 'Cellulose, Vegetable Cellulose Capsule, Tapioca Dextrin, Stearic Acid, and Silica.  SOMATO® is a trademark of Nutraland USA, Inc.', blockers: ['Silica. SOMATO is a trademark of Nutraland USA', 'Inc'] },
  { sku: '076280329575', name: 'IbuActin, Comfort Formula', count: '60ct', form: 'capsule', url: 'https://www.solaray.com/products/ibuactin-comfort-formula', oi: 'Maltodextrin, Vegetable Cellulose Capsule, Food Starch, Magnesium Stearate and Silica.', blockers: ['Food Starch'] },
  { sku: '076280346688', name: 'Plant-Sourced GABA', count: '30 ct', form: '', url: 'https://www.solaray.com/products/plant-sourced-gaba', oi: 'Cellulose, Vegetable Cellulose Capsule, L-Glutamic Acid and Silica. ‘The GABA ingredient is sourced from Fermented Barley.', blockers: ['L-Glutamic Acid', 'Silica. ‘The GABA ingredient is sourced from Fermented Barley'] },
  { sku: '076280352740', name: 'Akkermansia', count: '30ct', form: 'capsule', url: 'https://www.solaray.com/products/akkermansia', oi: 'Resistant Potato Starch, Vegetable Cellulose Capsule, Silica.', blockers: ['Resistant Potato Starch'] },
  { sku: '076280360448', name: 'Her Life Stages Libido', count: '60 ct', form: '', url: 'https://www.solaray.com/products/her-life-stages-libido', oi: 'Cellulose, Vegetable Capsule, Stearic Acid, and Silica.  KSM-66 Ashwagandha? is a registered trademark of Ixoreal Biomed Inc.', blockers: ['Vegetable Capsule', 'Silica. KSM-66 Ashwagandha? is a registered trademark of Ixoreal Biomed Inc'] },
  { sku: '076280366693', name: 'L-5-hydroxyTryptophan, 5-HTP 50mg', count: '60ct', form: '', url: 'https://www.solaray.com/products/l-5-hydroxytryptophan-5-htp', oi: 'Cellulose, Vegetable Cellulose Capsule, Alpha Galactosidase and Magnesium Stearate.', blockers: ['Alpha Galactosidase'] },
  { sku: '076280370201', name: 'Immufight Daily Defense', count: '60ct', form: 'capsule', url: 'https://www.solaray.com/products/immufight-daily-defense', oi: 'Cellulose, Vegetable Cellulose Capsule, Stearic Acid, Calcium Threonate, Silica and Tapioca Starch.', blockers: ['Calcium Threonate'] },
  { sku: '076280375831', name: 'Phytoestrogen', count: '240ct', form: '', url: 'https://www.solaray.com/products/phytoestrogen', oi: 'Vegetable Cellulose Capsule, Maltodextrin, Magnesium Stearate, Ginger Root, Licorice Root, Saw Palmetto Berry and Pygeum Bark Extract.', blockers: ['Ginger Root', 'Licorice Root', 'Saw Palmetto Berry', 'Pygeum Bark Extract'] },
  { sku: '076280375862', name: 'PhytoEstrogen, One Daily', count: '30ct', form: 'capsule', url: 'https://www.solaray.com/products/phytoestrogen-one-daily', oi: 'Grapefruit Juice Concentrate, Vegetable Cellulose Capsule, Maltodextrin, Cellulose, Pygeum (bark extract), Silica, Magnesium Stearate, African Cherry (berry), Saw Palmetto (berry), Ginger (root), Licorice (root) and Alpha Galactosidase.', blockers: ['Grapefruit Juice Concentrate', 'Pygeum (bark extract)', 'African Cherry (berry)', 'Saw Palmetto (berry)', 'Ginger (root)', 'Licorice (root)', 'Alpha Galactosidase'] },
  { sku: '076280375923', name: 'PhytoEstrogen Plus EFA\'s', count: '60ct', form: 'softgel', url: 'https://www.solaray.com/products/phytoestrogen-plus-efas', oi: 'Gelatin Softgel (Gelatin, Glycerin, Carob), Lecithin (soy) and Yellow Beeswax.', blockers: ['Gelatin Softgel (Gelatin, Glycerin, Carob)'] },
  { sku: '076280376814', name: 'Pygeum & Saw Palmetto Extracts 420mg', count: '240ct', form: 'capsule', url: 'https://www.solaray.com/products/pygeum-saw-palmetto-extracts-1', oi: 'Saw Palmetto Berry Extract, Vegetable Cellulose Capsule, Cellulose, Pumpkin Seed, L-Alanine, Glutamic Acid HCI, and L-Glycine.', blockers: ['Saw Palmetto Berry Extract', 'Pumpkin Seed', 'L-Alanine', 'Glutamic Acid HCI'] },
  { sku: '076280418873', name: 'Chromium Picolinate 1000mcg', count: '100ct / Lemon-Raspberry', form: 'capsule', url: 'https://www.solaray.com/products/chromium-picolinate', oi: 'Xylitol, Cellulose, Natural Flavors (Lemon and Raspberry with other Natural Flavors), Magnesium Stearate, FOS Blend (fructooligosaccharides, sprouted mung bean extract), Citric Acid, Silica and Malic Acid.', blockers: ['FOS Blend (fructooligosaccharides, sprouted mung bean extract)'] },
  { sku: '076280435450', name: 'Biotin Lozenge 5000mcg', count: 'Tangy Fruit / 60 ct', form: 'capsule', url: 'https://www.solaray.com/products/biotin-lozenge-1000mcg-tangy-fruit', oi: 'Sorbitol, Xylitol, Natural Peach Flavor with Other Natural Flavors, Stearic Acid, Silica, Orange Juice Powder, Malic Acid and Citric Acid.', blockers: ['Orange Juice Powder'] },
  { sku: '076280449051', name: 'Vitamin C', count: '100ct / Orange', form: 'gummy', url: 'https://www.solaray.com/products/vitamin-c-buffered', oi: 'Fructose, Molasses, Orange Juice Concentrate, Natural Tangerine Flavor with other Natural Flavors, Honey, Silica, Stearic Acid, Maltodextrin, Sodium Citrate  and Cellulose.', blockers: ['Molasses', 'Orange Juice Concentrate'] },
  { sku: '076280458350', name: 'Calcium Citrate With Vitamin D-3 1000mg', count: '180ct', form: 'capsule', url: 'https://www.solaray.com/products/calcium-citrate-with-vitamin-d-3', oi: 'Gelatin Capsule, Magnesium Stearate, Watercress Leaf, Dandelion Root and Parsley Leaf.', blockers: ['Watercress Leaf', 'Dandelion Root', 'Parsley Leaf'] },
  { sku: '076280458527', name: 'Calcium Citrate 1000mg', count: '240ct', form: 'capsule', url: 'https://www.solaray.com/products/calcium-citrate', oi: 'Vegetable Cellulose Capsule, Magnesium Stearate,  Watercress Leaf, Dandelion Root and Parsley Leaf.', blockers: ['Watercress Leaf', 'Dandelion Root', 'Parsley Leaf'] },
  { sku: '076280461053', name: 'Iron 50mg', count: '60ct', form: 'capsule', url: 'https://www.solaray.com/products/iron', oi: 'Herbal Base (Parsley, Rice Flour, Yellow Dock Root), Vegetable Cellulose Capsule and Ascorbyl Palmitate.', blockers: ['Herbal Base (Parsley, Rice Flour, Yellow Dock Root)'] },
  { sku: '076280463019', name: 'Magnesium Citrate 400mg', count: '90ct', form: 'capsule', url: 'https://www.solaray.com/products/magnesium-citrate', oi: 'Vegetable Cellulose Capsule, Cellulose, Magnesium Stearate, Arabic  Gum, Watercress Leaf, Dandelion Root, Alfalfa Leaf and Parsley Leaf.  Aquamin® is a registered trademark of Marigot Ltd. of Cork Ireland.', blockers: ['Watercress Leaf', 'Dandelion Root', 'Alfalfa Leaf', 'Parsley Leaf. Aquamin is a registered trademark of Marigot Ltd. of Cork Ireland'] },
  { sku: '076280469363', name: 'Her Life Stages Menopause', count: '60 ct', form: 'capsule', url: 'https://www.solaray.com/products/her-life-stages-menopause', oi: 'Cellulose, Vegetable Capsule, Stearic Acid, Silica.', blockers: ['Vegetable Capsule'] },
  { sku: '076280474848', name: 'Biocitrate Strontium 250mg', count: '60 ct', form: 'capsule', url: 'https://www.solaray.com/products/biocitrate-strontium', oi: 'Vegetable Cellulose Capsule, Alfalfa Leaf, Parsley Leaf, Magnesium Stearate and Kelp.', blockers: ['Alfalfa Leaf', 'Parsley Leaf', 'Kelp'] },
  { sku: '076280478556', name: 'Spectro Multivitamin, Iron-Free', count: '360ct', form: 'capsule', url: 'https://www.solaray.com/products/spectro-multi-vitamin-iron-free-1', oi: 'Gelatin Capsule, Eleuthero Root, Magnesium Stearate, Cellulose, Stearic Acid, Maltodextrin, Whole Rice Concentrate, Alfalfa Leaf, Montmorillonite Clay, Rose Hips and Acerola Cherry.', blockers: ['Alfalfa Leaf', 'Montmorillonite Clay', 'Rose Hips', 'Acerola Cherry'] },
  { sku: '076280529586', name: 'Colostrum+', count: 'Unflavored', form: 'powder', url: 'https://www.solaray.com/products/colostrum', oi: 'Acacia Gum and Sea Salt.  Contains: Milk.  Immunell™ is a trademark of Nexira.', blockers: ['Sea Salt. Contains: Milk. Immunell is a trademark of Nexira'] },
  { sku: '076280553871', name: 'QBC Plex Quercetin & Bromelain', count: '90ct / Orange', form: 'gummy', url: 'https://www.solaray.com/products/qbc-plex-quercetin-bromelain', oi: 'Sorbitol, Xylitol, Orange Juice, Cellulose, Natural Orange Flavor with Other Natural Flavors (soy), Silica, Magnesium Stearate, Maltodextrin, Glycine, Stevia Leaf Extract, Citric Acid (from Non-GMO Cassava) and Malic Acid.', blockers: ['Orange Juice'] },
  { sku: '076280558272', name: 'Once Daily Prenatal Multivitamin', count: '90ct', form: '', url: 'https://www.solaray.com/products/once-daily-prenatal-multi-vitamin', oi: 'Vegetable Cellulose Capsule, Cellulose, Sodium Alginate, Pea Starch, Tricalcium Phosphate, Magnesium Stearate, Modified Corn Starch, Magnesium Stearate, Aspartic Acid, Citric Acid, Orotic Acid, and Silica. Contains', blockers: ['Aspartic Acid', 'Orotic Acid', 'Silica. Contains'] },
  { sku: '076280563160', name: 'Immufight Respiratory Support', count: '90ct', form: 'capsule', url: 'https://www.solaray.com/products/immufight-respiratory-support', oi: 'Vegetable Cellulose Capsule, Cellulose, Stearic Acid, Maltodextrin, Silica, Calcium Threonate, Acacia Gum and Tapioca Starch.', blockers: ['Calcium Threonate'] },
  { sku: '076280582505', name: 'Colostrum+', count: 'Peach Mango', form: 'powder', url: 'https://www.solaray.com/products/colostrum', oi: 'Natural Peach and Mango Flavors with Other Natural Flavors, Citric  Acid, Acacia Gum, and Stevia (leaf extract).  Contains: Milk.  Immunell™ is a trademark of Nexira.', blockers: ['Stevia (leaf extract). Contains: Milk. Immunell is a trademark of Nexira'] },
  { sku: '076280595499', name: 'NADH', count: '', form: 'capsule', url: 'https://www.solaray.com/products/nadh', oi: 'Cellulose, Vegetable Cellulose Capsule, Fractionated Palm Oil, Beeswax, Chlorophyllin, Stearic Acid, and Silica. PANMOL?® is a registered trademark of vis vitalis gmbh.', blockers: ['Fractionated Palm Oil', 'Chlorophyllin', 'Silica. PANMOL? is a registered trademark of vis vitalis gmbh'] },
  { sku: '076280598933', name: 'Aged Black Garlic', count: '', form: 'capsule', url: 'https://www.solaray.com/products/aged-black-garlic', oi: 'Vegetable Cellulose Capsule, Acacia Gum, Cellulose, and Silica, Garlzac® is a registered trademark of Olene Life Sciences.', blockers: ['Garlzac is a registered trademark of Olene Life Sciences'] },
  { sku: '076280600438', name: 'Mushroom Herb Complex', count: '90ct', form: 'capsule', url: 'https://www.solaray.com/products/mushroom-complete-8', oi: 'Vegetarian Capsule, Cellulose, Magnesium Stearate and Silica.', blockers: ['Vegetarian Capsule'] },
  { sku: '076280615470', name: 'HMB + Vitamin D3', count: 'Lemon Lime, 30 servings', form: 'powder', url: 'https://www.solaray.com/products/hmb-vitamin-d3', oi: 'Citric Acid, Natural Lemon and Lime Flavor with Other Natural Flavors, Sea Salt, Silica, and Steviol Glycoside. myHMB? is a registered trademark of TSI Group Co., Ltd. US Patent #8,815,280 #9,539,224 #9,707,241', blockers: ['Sea Salt', 'Steviol Glycoside. myHMB? is a registered trademark of TSI Group Co.', 'Ltd. US Patent #8', '815', '280 #9', '539', '224 #9', '707', '241'] },
  { sku: '076280646306', name: 'Super Bio Vitamin C 1000mg', count: '60ct', form: 'capsule', url: 'https://www.solaray.com/products/super-bio-vitamin-c-buffered-two-stage-timed-release', oi: 'Vegetable Cellulose Capsule, Magnesium Stearate, Silica, Stearic Acid and Buffering Base (Calcium Carbonate and Magnesium Oxide).', blockers: ['Buffering Base (Calcium Carbonate and Magnesium Oxide)'] },
  { sku: '076280669671', name: 'Mycrobiome Probiotic Colon Formula, 50bn, 18 Strain Once Daily', count: '30ct', form: 'capsule', url: 'https://www.solaray.com/products/mycrobiome-probiotic-colon-formula-50bn-18-strain-once-daily', oi: 'Non-GMO Potato Starch, Vegetable Cellulose Capsule, Cellulose, Oat Fiber Blend (Oat Fiber, Gum Arabic, Sunflower Lecithin, Sunflower Oil), Silica.', blockers: ['Oat Fiber Blend (Oat Fiber, Gum Arabic, Sunflower Lecithin, Sunflower Oil)'] },
  { sku: '076280675559', name: 'Her Life Stages Postmenopause', count: '60 ct', form: 'capsule', url: 'https://www.solaray.com/products/her-life-stages-postmenopause', oi: 'Maltodextrin (from Non-GMO Corn), Cellulose, Vegetable Capsule, Stearic Acid, Silica.  Chromax® is a registered trademark of Nutrition 21, LLC. Chromax® is patent protected.  Morosil® is a trademark of BIONAP S.r.l.  Veri-te® is a registered trademark of Lallemand Group.  Affron® and Lepticrosalides® are registered trademarks of Pharmactive Biotech Products, $.L.U.', blockers: ['Vegetable Capsule', 'Silica. Chromax is a registered trademark of Nutrition 21', 'LLC. Chromax is patent protected. Morosil is a trademark of BIONAP S.r.l. Veri-te is a registered trademark of Lallemand Group. Affron', 'Lepticrosalides are registered trademarks of Pharmactive Biotech Products', '$.L.U'] },
  { sku: '076280693034', name: 'Mycrobiome Probiotic Weight Formula, 50 Billion, 18 Strain Once Daily', count: '30ct', form: 'capsule', url: 'https://www.solaray.com/products/mycrobiome-probiotic-weight-formula-50-billion-18-strain-once-daily', oi: 'Non-GMO Potato Starch, Vegetable Cellulose Capsule, Cellulose, Oat Fiber Blend (Oat Fiber, Gum Arabic, Sunflower Lecithin, Sunflower Oil), Silica.', blockers: ['Oat Fiber Blend (Oat Fiber, Gum Arabic, Sunflower Lecithin, Sunflower Oil)'] },
  { sku: '076280728507', name: 'Liposomal Glutathione', count: '', form: 'capsule', url: 'https://www.solaray.com/products/liposomal-glutathione', oi: 'Cellulose, Vegetable Cellulose Capsule, Sunflower Phospholipids, Stearic Acid, and Silica.', blockers: ['Sunflower Phospholipids'] },
  { sku: '076280773279', name: 'ProSorb Berberine 9x 550mg', count: '30 ct', form: 'capsule', url: 'https://www.solaray.com/products/prosorb-berberine-9x', oi: 'Cellulose, Pea Protein Isolate, Vegetable Capsule, Sunflower Lecithin, Grape Seed Extract, Stearic Acid, Silica.', blockers: ['Vegetable Capsule', 'Grape Seed Extract'] },
  { sku: '076280788020', name: 'Spermidine', count: '', form: 'capsule', url: 'https://www.solaray.com/products/spermidine', oi: 'Tapioca Dextrin, Cellulose, Vegetable Cellulose Capsule, Citric Acid, and Silica. Miricell™ is a trademark of Nutraland USA, Inc.', blockers: ['Silica. Miricell is a trademark of Nutraland USA', 'Inc'] },
  { sku: '076280814590', name: 'D-Mannose with CranActin', count: '226 G', form: 'powder', url: 'https://www.solaray.com/products/d-mannose-with-cranactin', oi: 'Inulin, Organic Natural Lemon, Cranberry and Berry Flavors with Other Natural Flavors, Silica, Acacia Gum, Citric Acid, Malic Acid, Magnesium Hydroxide, Beet (Beta vulgaris) (root), Stevia (Stevia rebaudiana) (leaf extract), and Guar Gum.', blockers: ['Cranberry'] },
  { sku: '076280824810', name: 'CoQ-10, Ubiquinol 100mg', count: '30ct', form: 'softgel', url: 'https://www.solaray.com/products/coq-10-ubiquinol', oi: 'D-Limonene Oil, Gelatin, Glycerin, Purified Water, Caprylic Acid, Capric Acid, Alpha Lipoic Acid and Caramel Liquid.', blockers: ['D-Limonene Oil', 'Caprylic Acid', 'Capric Acid', 'Alpha Lipoic Acid', 'Caramel Liquid'] },
  { sku: '076280846638', name: 'Reacta-C & Elderberry', count: '120 ct', form: 'capsule', url: 'https://www.solaray.com/products/reacta-c-elderberry', oi: 'Vegetable Cellulose Capsule, Calcium L-Threonate, Maltodextrin, Maanesium Stearate and Silica.', blockers: ['Calcium L-Threonate', 'Maanesium Stearate'] },
  { sku: '076280882896', name: 'Liposomal Multivitamin Men\'s', count: '60ct', form: 'capsule', url: 'https://www.solaray.com/products/liposomal-multivitamin-mens', oi: 'Cellulose, Lipid Blend from Sunflower Oil and Sustainable Palm Oil, Vegetable Cellulose Capsule, Magnesium Stearate, Modified Tapioca Starch, Silica, Sodium Alginate, Pea Starch and Gum rabic.', blockers: ['Lipid Blend from Sunflower Oil', 'Gum rabic'] },
  { sku: '076280884500', name: 'Calcium & Magnesium Citrate W/ Vitamin D-3, 2:1 Ratio', count: '180ct', form: 'capsule', url: 'https://www.solaray.com/products/calcium-magnesium-citrate-w-vitamin-d-3-2-1-ratio', oi: 'Gelatin Capsule, Cellulose, Magnesium Stearate, Parsley Leaf, Alfalfa Leaf, Watercress Leaf and Dandelion Root.', blockers: ['Parsley Leaf', 'Alfalfa Leaf', 'Watercress Leaf', 'Dandelion Root'] },
  { sku: '076280886757', name: 'Opti-5 Magnesium', count: '', form: 'capsule', url: 'https://www.solaray.com/products/opti-5-magnesium', oi: 'Vegetable Cellulose Capsule, Arabic Gum, and Cellulose.  Aquamin® is a registered trademark of Marigot Ltd. of Cork Ireland,  GivoMag™ is a trademark of Isaltis.', blockers: ['Cellulose. Aquamin is a registered trademark of Marigot Ltd. of Cork Ireland', 'GivoMag is a trademark of Isaltis'] },
  { sku: '076280937145', name: 'Nattokinase and Serrapeptase', count: '', form: 'capsule', url: 'https://www.solaray.com/products/solaray-nattokinase-serrapeptase-supplement-3-000-fu-healthy-circulation-blood-flow-support-30-vegcaps', oi: 'Cellulose, Vegetable Cellulose, Silica, Magnesium Stearate, Dextrin and  Enteric Coating.  Contains: Soy', blockers: ['Enteric Coating. Contains: Soy'] },
  { sku: '076280946123', name: 'Her Life Stages PMS & Menstrual', count: '24 ct', form: 'capsule', url: 'https://www.solaray.com/products/her-life-stages-pms-menstrual', oi: 'Cellulose, Vegetable Capsule, Stearic Acid, Silica, Acacia (Gum Arabic), Maltodextrin,  Potato Dextrin.', blockers: ['Vegetable Capsule'] },
  { sku: '076280953794', name: 'Fermented Mushroom Complete 1200mg', count: '60ct', form: 'capsule', url: 'https://www.solaray.com/products/fermented-mushroom-complete', oi: '**Mycelium/Organic Whole Oat Biomass and Vegetable Cellulose Capsule.', blockers: ['**Mycelium/Organic Whole Oat Biomass'] },
  { sku: '076280955781', name: 'Her Life Stages Perimenopause', count: '60 ct', form: 'capsule', url: 'https://www.solaray.com/products/her-life-stages-perimenopause', oi: 'Cellulose, Vegetable Capsule, Dextrin, Stearic Acid, Silica.', blockers: ['Vegetable Capsule'] },
  { sku: '076280975123', name: 'Sugar-Free L-Theanine Chewable, Lemon-Lime Flavor', count: '30 CT', form: 'chewable', url: 'https://www.solaray.com/products/solaray-l-theanine-chewable-supplement-200-mg-30-count', oi: 'Sorbitol, Xylitol, Natural Lemon Lime Flavor and other Natural Flavors (milk, soy), Maltodextrin, Stearic Acid, Citric Acid, Magnesium Stearate, Stevia (leaf extract), Malic Acid and Silica. Contains', blockers: ['Silica. Contains'] },

];

export const BATCH124_LEFTOVER_REAL_TOKENS = [
  "Acerola (fruit juice)",
  "Acerola Cherry",
  "African Cherry (berry)",
  "Alfalfa Aerial",
  "Alfalfa Leaf",
  "Alfalfa leaf",
  "Aloe Vera Gel (200x dry concentrate)",
  "Alpha Galactosidase",
  "Alpha Lipoic Acid",
  "Aspartic Acid",
  "Bilberry (fruit)",
  "Bioflavonoid Concentrate",
  "BioPerine (Black Pepper Extract)",
  "Blueberry (fruit extract)",
  "Brewer's Yeast",
  "Buffering Base (Calcium Carbonate and Magnesium Oxide)",
  "Calcium Ascorbate",
  "Calcium Fluoride 6x",
  "Calcium L-Threonate",
  "Calcium Phosphate 3x",
  "Calcium Threonate",
  "Capric Acid",
  "Caprylic Acid",
  "Caramel (coloring)",
  "Caramel Liquid",
  "Carrageenan",
  "Carrot Juice",
  "Carrot Juice (root)",
  "Cassava Flour",
  "Celery Seed",
  "Chamomile",
  "Chamomile (flowering tops)",
  "Chlorophyllin",
  "Cranberry",
  "D-Limonene Oil",
  "Dandelion Root",
  "Dextrin (from Non-GMO Maca)",
  "DIM (Diindolyimethane)",
  "Dong Quai Root",
  "Fennel Seed",
  "Fenugreek Seeds",
  "Fermented Defatted Chickpea Flour Extract",
  "Food Starch",
  "FOS Blend (Fructooligosaccharides)",
  "FOS Blend (fructooligosaccharides, sprouted mung bean extract)",
  "Fractionated Palm Oil",
  "Gelatin Softgel (Gelatin, Glycerin, Carob)",
  "Ginger (root)",
  "Ginger Root",
  "Ginseng (Panax ginseng) (root extract)",
  "Glucono Delta Lactone",
  "Glutamic Acid",
  "Glutamic Acid HCl",
  "Glycerol Triacetate",
  "Gotu Kola (Centella asiatica) (extract)",
  "Grain Alcohol (45-55% by volume)",
  "Grape Seed Extract",
  "Grapefruit Juice Concentrate",
  "Herb Base (Parsley Leaf, Alfalfa Leaf)",
  "Herb Base (Parsley Leaf, Chamomile, Watercress)",
  "Herb Base (Parsley Leaf, Organic Alfalfa Leaf)",
  "Herbal Base (Parsley, Rice Flour, Yellow Dock Root)",
  "Horsetail",
  "Horsetail Herb",
  "Hydrogenated Soybean Oil",
  "Iron Pyrophosphate",
  "Kelp",
  "L-Alanine",
  "L-Aspartic Acid",
  "L-Glutamic Acid",
  "Licorice (root)",
  "Licorice Root",
  "Lipid Blend from Sunflower Oil",
  "Lipid Blend from Sunflower Oil and Sustainable Palm Oil",
  "Magnesium Carbonate",
  "Magnesium Citrate",
  "Magnesium Oxide",
  "Magnesium Phosphate 3x",
  "Molasses",
  "Montmorillonite Clay",
  "Mycelium/Organic Whole Oat Biomass",
  "Natural Mango",
  "Neem Leaf",
  "Nettle Leaf",
  "Nutritional Yeast",
  "Oat Fiber Blend (Oat Fiber, Gum Arabic, Sunflower Lecithin, Sunflower Oil)",
  "Oat Straw Stem",
  "Orange Juice",
  "Orange Juice Concentrate",
  "Orange Juice Powder",
  "Organic Alfalfa",
  "Orotic Acid",
  "Parsley",
  "Parsley Aerial",
  "Parsley Herb",
  "Parsley Leaf",
  "Peppermint Leaves",
  "Potassium Phosphate 3x",
  "Pumpkin Seed",
  "Pumpkin Seed Oil",
  "Pumpkin Seeds",
  "Pygeum (bark extract)",
  "Pygeum Bark Extract",
  "Resistant Potato Starch",
  "Rice Bran Concentrate",
  "Rose Hips",
  "Rose Hips (fruit)",
  "Saw Palmetto (berry)",
  "Saw Palmetto Berry",
  "Saw Palmetto Berry Extract",
  "Sea Salt",
  "Silica 6x",
  "Sodium Chloride 6x",
  "Softgel (Gelatin)",
  "Softgel (Non-GMO Tapioca Starch, Non-GMO Glycerin and Water)",
  "Soy Protein Isolate",
  "Sunflower Phospholipids",
  "Trace Mineral Complex",
  "Turmeric Root Extract",
  "Vegetable Capsule",
  "Vegetable Fiber",
  "Vegetable Juice",
  "Vegetable Juice Concentrate",
  "Vegetarian Capsule",
  "Watercress",
  "Watercress Leaf",
  "Whole Food Base (Aloe Vera Gel, Whole Rice Concentrate including Bran, Germ, and Polishings)",
  "Whole Food Base (Rose Hips, Acerola Cherry and Bioflavonoid Concentrate)",
  "Whole Food Base (Whole Rice Concentrate and Aloe Vera Gel)",
  "Whole Food Base (Whole Rice Concentrate including Bran, Germ and Polishings)",
  "Whole Food Base (Whole Rice Concentrate including Bran, Germ and Polishings, and Aloe Vera Gel)",
  "Whole Food Base (Whole Rice Concentrate including Kernel, Polishings, Hull and Pure Aloe Vera Gel)",
  "Whole Food Base (Whole Rice Concentrate including the bran, germ and polishings and Aloe Vera Gel)",
  "Whole Food Base (Whole Rice Concentrate including the Bran, Polishings and Germ and Aloe Vera Gel)",
  "Whole Food Base (Whole Rice Concentrate including the Bran, Polishings and Germ)",
  "Whole Food Base (Whole Rice Concentrate including the Bran, Polishings and Germ, Aloe Vera Gel)",
  "Whole Food Base (Whole Rice Concentrate including the Bran, Polishings and Germ, and Aloe Vera Gel)",
  "Whole Food Base (Whole Rice Concentrate including the Bran, Polishings and Germ, and Pure Aloe Vera Gel)",
  "Whole Food Base (Whole Rice Concentrate including the Bran, Polishings and Germ, Pure Aloe Vera Gel)",
  "Whole Food Base (Whole Rice Concentrate including the Kernel, Polishings, and Hull, and Aloe Vera Gel)",
  "Whole Rice Concentrate (Including Bran, Polishings, and Germ, and Aloe Vera Gel)",
  "Yellow Dock Root",
  "Yellowdock Root"
];

const _ROWS = BATCH124_KYR6B_SOLARAY_FAT_CLOSEOUT;
if (_ROWS.length !== 18) throw new Error('batch124 tally drift');
if (_ROWS.filter((r) => r.verdict === 'clean').length !== 6) throw new Error('batch124 Clean tally drift');
if (_ROWS.filter((r) => r.verdict === 'caution').length !== 11) throw new Error('batch124 Caution tally drift');
if (_ROWS.filter((r) => r.verdict === 'avoid').length !== 1) throw new Error('batch124 Avoid tally drift');
if (_ROWS.filter((r) => r.formulaId === r.id).length !== 12) throw new Error('batch124 NEW tally drift');
if (_ROWS.filter((r) => r.formulaId !== r.id).length !== 6) throw new Error('batch124 REUSE tally drift');
if (_ROWS.some((r) => r.recordStatus !== UNVERIFIED)) throw new Error('batch124 recordStatus');
if (_ROWS.some((r) => r.brand !== BRAND)) throw new Error('batch124 brand');
if (_ROWS.some((r) => r.barcode)) throw new Error('batch124 UPC must stay blank');
if (_ROWS.some((r) => r.form === 'liquid')) throw new Error('batch124 must not grade pour bottles');
if (_ROWS.some((r) => !/\(\d/.test(r.productName) && !/oz|g\)/.test(r.productName))) throw new Error('batch124 row missing pack size');
if (BATCH124_SKIPPED_NO_OI.length !== 1) throw new Error('batch124 no_OI');
if (BATCH124_SKIPPED_OUT.length !== 0) throw new Error('batch124 OUT');
if (BATCH124_HUNT_POUR.length !== 0) throw new Error('batch124 hunt');
if (BATCH124_REFUSED.length !== 166) throw new Error('batch124 REFUSED');
if (BATCH124_LEFTOVER_REAL_TOKENS.length !== 143) throw new Error('batch124 leftover');
if (_ROWS.some((r) => r.verdict === 'clean' && r.inactiveIngredients.some((i) => i.riskLevel !== 'cleared'))) throw new Error('batch124 Clean has a flag');
if (_ROWS.some((r) => r.verdict === 'avoid' && !r.inactiveIngredients.some((i) => i.riskLevel === 'high'))) throw new Error('batch124 Avoid without High');
if (_ROWS.some((r) => r.verdict === 'caution' && !r.inactiveIngredients.some((i) => i.riskLevel === 'limited' || i.riskLevel === 'moderate'))) throw new Error('batch124 Caution without Limited');
if (BATCH124_LEFTOVER_REAL_TOKENS.includes('Parsley Leaf') !== true) throw new Error('parsley must stay leftover');
if (BATCH124_LEFTOVER_REAL_TOKENS.includes('Natural Mango') !== true) throw new Error('natural mango stays');
const _DROPPED = ['Soy Oil','Natural Lemon','Natural Peach','Natural Raspberry','Organic Natural Lemon','Soy','Sodium Crosscarmellose','Organic Sunflower Oil & Organic Carnauba Wax'];
if (_DROPPED.some((t) => BATCH124_LEFTOVER_REAL_TOKENS.includes(t))) throw new Error('mapped token still leftover');
