// DRAFT / not verified / batch 129 KYR6-b Solaray OCR + no_OI cleanup.
// OCR misspellings map onto existing MAIN families. They are not new tokens.
// Trademark lines are stripped. Pour bottles stay on the hunt list.
// batch70-batch128 were not edited. UPC stays empty. Liposomal 076280830385 stays no_OI.
//
// TALLY: 53 rows — Clean 11 / Caution 42 / Avoid 0.
// NEW 49 / REUSE 4 / SKIPPED no_OI leftover 1 / SKIPPED OUT 0 / REFUSED 4.

import type {
  CleanAlternative,
  IngredientFlag,
  RatingRecord,
} from '../ratingRecord';

const UNVERIFIED = 'unverified' as const;
const ADULT = 'adult' as const;
const KIDS = 'kids' as const;
const SUPPLEMENT = 'Supplement' as const;
const UNVERIFIED_NOTE = 'draft, not verified';
const BRAND = 'Solaray';
const RETAILERS = ['Amazon', 'solaray.com'] as const;
const LIMITED_STACK =
  'Limited-only stack stays Caution (no 3-pt Avoid). Limited-only never Avoid. Avoid needs High.';
const UPC_BLANK =
  'No GTIN-12 was printed under the bars on the panel opened for Other Ingredients, so UPC is blank. Shopify barcodes that echo the SKU are not UPCs.';

const METH = {
  vegcap: "Methodology \u00a75 Cleared (capsule cellulose / labeled veg cap).",
  mcc: "Methodology \u00a75 Cleared (cellulose / MCC / croscarmellose sodium).",
  stearate: "Methodology \u00a75 Cleared (magnesium stearate / stearic acid). Maanesium Stearate maps here only as that lubricant (Sept 28, 2026).",
  sio2: "Methodology \u00a75 Limited (silica / silicon dioxide). Not Avoid.",
  maltodextrin: "Methodology \u00a75 Limited (maltodextrin).",
  botanical: "Methodology §5 Cleared (named plant-part food botanical). Parsley, Parsley Leaf, Parsley Aerial, and Feverfew (aerial) map here (Sept 28, 2026).",
  licorice: "Methodology \u00a75 Cleared (licorice extract).",
  riceconc: "Methodology \u00a75 Cleared (whole rice concentrate / rice hull concentrate).",
  aloe: "Methodology \u00a75 Caution (aloe as an other ingredient).",
  riceextract: "Methodology \u00a75 Limited (unspecified rice extract).",
  ricebran: "Methodology \u00a75 Cleared (rice bran extract). Rice Bran Concentrate maps here (Sept 28, 2026 family merge).",
  ricepowder: "Methodology \u00a75 Caution (rice flour / rice powder).",
  riceprotein: "Methodology \u00a75 Cleared (rice protein).",
  starch: "Methodology \u00a75 Cleared (named simple starch / bare starch / food starch / resistant potato starch).",
  modstarch: "Methodology \u00a75 Limited (modified starch / modified food starch / modified corn starch / modified tapioca starch).",
  gelatin: "Methodology \u00a75 Cleared (gelatin / gelatin capsule).",
  glycerin: "Methodology \u00a75 Cleared (glycerin).",
  water: "Methodology \u00a75 Cleared (water / purified water).",
  gum: "Methodology \u00a75 Cleared (acacia / gum arabic / guar).",
  alginate: "Methodology \u00a75 Cleared (sodium alginate).",
  citric: "Methodology \u00a75 Cleared (citric acid). Off-gummy parenthetical citric stays Cleared.",
  gummycitric: "Methodology \u00a75 Caution (citric acid from tapioca or cassava on a gummy).",
  malic: "Methodology \u00a75 Cleared (malic acid).",
  ascorbic: "Methodology \u00a75 Cleared (ascorbic acid).",
  citrate: "Methodology \u00a75 Cleared (citrate salts).",
  honey: "Methodology \u00a75 Cleared (honey). Not for under 1.",
  glycine: "Methodology \u00a75 Cleared (glycine / amino-acid filler). L-Glycine maps here.",
  inulin: "Methodology \u00a75 Cleared (inulin). FOS Blend strings do not map here.",
  grapeseed: "Methodology \u00a75 Cleared (grape seed extract).",
  peaprotein: "Methodology \u00a75 Cleared (pea protein isolate).",
  gms: "Methodology \u00a75 Cleared (glycerol monostearate / GMS).",
  mgoh: "Methodology \u00a75 Cleared (magnesium hydroxide as pH adjuster).",
  oilfill: "Methodology \u00a75 Cleared (named oil as non-gummy capsule / softgel fill). Gummy and lozenge seed oils stay High.",
  oilhigh: "Methodology \u00a75 High (gummy / lozenge seed or vegetable oil). Avoid.",
  hvo: "Methodology \u00a75 Caution (hydrogenated vegetable oil as an other ingredient, not a gummy).",
  flavor: "Methodology \u00a75 Caution (named flavor). Bare Natural [fruit] maps here. Exact \u201cNatural flavors\u201d opacity stays Limited.",
  natflavor: "Methodology \u00a75 Limited (exact natural flavors opacity). Not flipped.",
  stevia: "Methodology \u00a75 Caution (stevia extract / stevia leaf extract).",
  sugaralc: "Methodology \u00a75 Limited (sorbitol / xylitol).",
  fructose: "Methodology \u00a75 Limited (fructose). Not High.",
  sucrose: "Methodology \u00a75 Limited (sucrose). Not High. Not flipped.",
  eleuthero: "Methodology \u00a75 Caution (Eleuthero Root on the Other Ingredients line).",
  rosemary: "Methodology \u00a75 Caution (rosemary extract, oral).",
  toco: "Methodology \u00a75 Cleared (mixed tocopherols / ascorbyl palmitate).",
  beeswax: "Methodology \u00a75 Cleared (beeswax / yellow beeswax).",
  lecithin: "Methodology \u00a75 Cleared (lecithin / soy lecithin / sunflower lecithin). Sunflower Phospholipids map here.",
  carob: "Methodology \u00a75 Caution (carob extract).",
  dextrin: "Methodology \u00a75 Caution (bare dextrin). Potato dextrin maps here.",
  tdextrin: "Methodology \u00a75 Limited (tapioca dextrin).",
  peastarch: "Methodology \u00a75 Caution (pea starch).",
  casil: "Methodology \u00a75 Caution (calcium silicate).",
  phosphate: "Methodology \u00a75 Cleared (calcium phosphate / tricalcium phosphate / dicalcium phosphate). Homeopathic 3x salts do not map here.",
  enteric: "Methodology \u00a75 Caution (bare enteric coating).",
  soy: "Methodology \u00a75 Limited (bare soy). Not soy lecithin.",
  mct: "Methodology \u00a75 Limited (unlabeled MCT).",
  carrageenan: "Methodology \u00a75 Limited (carrageenan).",
  caramel: "Methodology \u00a75 High (caramel color, undisclosed class). Caramel Liquid maps here (Sept 28, 2026). Avoid.",
  carotenoid: "Methodology \u00a75 Caution (beta-carotene as color).",
  annatto: "Methodology \u00a75 Caution (annatto).",
  tio2: "Methodology \u00a75 High (titanium dioxide). Avoid.",
  juicecolor: "Methodology \u00a75 Cleared (named juice as color).",
  chlorophyll: "Methodology \u00a75 Cleared (chlorophyll named pigment). Chlorophyllin is not this row.",
  mgo: "Methodology \u00a75 Caution (magnesium oxide as an other ingredient). Sept 28, 2026 founder stamp.",
  trace: "Methodology \u00a75 Caution (trace mineral complex). Sept 28, 2026 founder stamp.",
  buffer: "Methodology \u00a75 Caution (buffering base of calcium carbonate and magnesium oxide). Magnesium oxide is the driver. Sept 28, 2026.",
  threonate: "Methodology \u00a75 Caution (calcium L-threonate / calcium threonate). Sept 28, 2026 founder stamp.",
  capacid: "Methodology \u00a75 Caution (caprylic acid / capric acid as an other ingredient). Sept 28, 2026 founder stamp.",
  limonene: "Methodology \u00a75 Caution (D-limonene oil). Sept 28, 2026 founder stamp.",
  chlorophyllin: "Methodology \u00a75 Caution (chlorophyllin). Not the Cleared chlorophyll pigment row. Sept 28, 2026 founder stamp.",
  alcohol: "Methodology \u00a75 Caution (grain alcohol 45\u201355% by volume). Sept 28, 2026 founder stamp.",
  molasses: "Methodology \u00a75 Caution (molasses). Sept 28, 2026 founder stamp.",
  clay: "Methodology \u00a75 Caution (montmorillonite clay). Sept 28, 2026 founder stamp.",
  ironpyro: "Methodology \u00a75 Caution (iron pyrophosphate). Sept 28, 2026 founder stamp.",
  vegfiber: "Methodology \u00a75 Caution (vegetable fiber). Sept 28, 2026 founder stamp.",
  gdl: "Methodology \u00a75 Cleared (glucono delta lactone / gluconolactone). Sept 28, 2026 founder stamp.",
  triacetate: "Methodology \u00a75 Caution (glycerol triacetate). Not the Cleared triacetin row. Sept 28, 2026 founder stamp.",
  galactosidase: "Methodology \u00a75 Cleared (alpha galactosidase as an other ingredient). Sept 28, 2026 founder stamp.",
  ala: "Methodology \u00a75 Caution (alpha lipoic acid as an other ingredient). Sept 28, 2026 founder stamp.",
  amino: "Methodology \u00a75 Caution (glutamic acid / glutamic acid HCl / L-glutamic acid / aspartic acid / L-aspartic acid / L-alanine). Sept 28, 2026 founder stamp.",
  bioflav: "Methodology \u00a75 Caution (bioflavonoid concentrate). Sept 28, 2026 founder stamp.",
  wholefood: "Methodology \u00a75 Caution (whole food base of rose hips, acerola cherry, and bioflavonoid concentrate). Sept 28, 2026 founder stamp.",
  cranberry: "Methodology \u00a75 Caution (cranberry as an other ingredient). Not Cleared cranberry fruit. Sept 28, 2026 founder stamp.",
  gotu: "Methodology \u00a75 Caution (gotu kola extract as an other ingredient). Sept 28, 2026 founder stamp.",
  bioperine: "Methodology \u00a75 Caution (BioPerine black pepper extract as an other ingredient). Sept 28, 2026 founder stamp.",
  dim: "Methodology \u00a75 Caution (DIM / diindolylmethane as an other ingredient). Sept 28, 2026 founder stamp.",
  orotic: "Methodology \u00a75 Caution (orotic acid). Sept 28, 2026 founder stamp.",
  mycelium: "Methodology \u00a75 Caution (mycelium / organic whole oat biomass). Not Cleared organic myceliated oats. Sept 28, 2026 founder stamp.",
  chickpea: "Methodology \u00a75 Caution (fermented defatted chickpea flour extract). Sept 28, 2026 founder stamp.",
  fos: "Methodology \u00a75 Caution (FOS Blend). Not the Cleared inulin / FOS fiber row. Sept 28, 2026 founder stamp.",
  soyiso: "Methodology \u00a75 Caution (soy protein isolate). Not bare soy Limited and not pea protein isolate. Sept 28, 2026 founder stamp.",
  kelp: "Methodology \u00a75 Caution (kelp as an other ingredient). Sept 28, 2026 founder stamp.",
  turmeric: "Methodology \u00a75 Caution (turmeric root extract as an other ingredient). Sept 28, 2026 founder stamp.",
  salt: "Methodology \u00a75 Cleared (sodium chloride). Sea Salt maps here (Sept 28, 2026 family merge).",
  yeast: "Methodology \u00a75 Cleared (cultured yeast). Brewer\u2019s Yeast and Nutritional Yeast map here (Sept 28, 2026 family merge).",
  cassava: "Methodology \u00a75 Caution (cassava root / cassava dextrin). Cassava Flour maps here. Not Cleared tapioca starch.",
  mgcarb: "Methodology \u00a75 Cleared (calcium carbonate mineral-filler class). Magnesium Carbonate maps here (Sept 28, 2026 family merge).",
  juice: "Methodology \u00a75 Caution (juice as sweetener). Orange, grapefruit, and vegetable juice, concentrate, or powder with no \u201ccolor\u201d map here.",
  palm: "Methodology \u00a75 Cleared (palm oil as capsule / softgel fill). Gummy palm stays High. Fractionated palm oil uses this form split.",

  shell: "Methodology §5 Caution (bare Vegetable Capsule / Vegetarian Capsule). Unnamed shell. Not Vegetable Cellulose Capsule / HPMC.",
  herbbase: "Methodology §5 Cleared (herb base that only adds parsley to already-locked botanicals). Rice flour alone stays Caution.",
  monodig: "Methodology §5 Caution (mono- and diglycerides). Not glycerol monostearate.",
  mctcoco: "Methodology §5 Cleared (MCT oil labeled coconut). Not unlabeled MCT. Not a pour bottle.",

} as const;

function flag(name: string, riskLevel: IngredientFlag['riskLevel'], source: string): IngredientFlag {
  return { name, riskLevel, source };
}
function labelCite(label: string, meth: string): string {
  return `${label}; ${meth}`;
}
function alt(productId: string, rankReason: string): CleanAlternative {
  return { productId, rankReason };
}
function row(opts: Omit<RatingRecord, 'recordStatus'> & { recordStatus?: RatingRecord['recordStatus'] }): RatingRecord {
  return { ...opts, recordStatus: opts.recordStatus ?? UNVERIFIED };
}
type Compact = {
  id: string;
  productName: string;
  formulaId: string;
  form: string;
  barcode?: string;
  audience?: 'adult' | 'kids';
  actives: RatingRecord['activeIngredients'];
  flags: [string, IngredientFlag['riskLevel'], keyof typeof METH][];
  verdict: RatingRecord['verdict'];
  note: string;
  cite: string;
};
function expand(d: Compact): RatingRecord {
  const alts: CleanAlternative[] = [];
  if (d.verdict !== 'clean') {
    alts.push(alt('amazon-elements-vitamin-d3-5000-softgels', 'Independently Clean Amazon Elements Vitamin D3 5000 IU already on main. Form labeled, not a hard filter (§6).'));
  }
  return row({
    id: d.id,
    productName: d.productName,
    brand: BRAND,
    category: 'Vitamins',
    formulaId: d.formulaId,
    ...(d.audience === KIDS ? { audience: KIDS } : { audience: ADULT, minAge: 18 }),
    form: d.form,
    ...(d.barcode ? { barcode: d.barcode } : {}),
    productType: SUPPLEMENT,
    activeIngredients: d.actives,
    inactiveIngredients: d.flags.map(([n, risk, meth]) => flag(n, risk, labelCite(d.cite, METH[meth]))),
    verdict: d.verdict,
    honestNote: `${d.note} ${LIMITED_STACK} Pack sizes share formulaId \`${d.formulaId}\` when this OI list holds. Adults unless the name says kids. No dosing or medical advice. Draft, not verified.`,
    retailers: [...RETAILERS],
    cleanAlternatives: alts.length ? alts : undefined,
    sourcesGeneral: [`${d.cite} — ${UNVERIFIED_NOTE}; no DailyMed drug SPL`],
  });
}

const COMPACT: Compact[] = [
  {
    id: "solaray-b129-076280012101",
    productName: "Solaray Dandelion Root 1040mg (100ct)",
    formulaId: "solaray-b129-076280012101",
    form: "capsule",
    barcode: "076280012101",
    actives: [
      { name: "Dandelion (root)", strength: "1040 mg" },
    ],
    flags: [
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Magnesium Stearate", "cleared", "stearate"],
      ["Rice Extract Blend", "limited", "riceextract"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Rice Extract Blend. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/dandelion-root other-ingredients: Vegetable Cellulose Capsule, Magnesium Stearate, and Rice Extract Blend. Exact pack Solaray Dandelion Root 1040mg (100ct). SKU 076280012101. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280012118",
    productName: "Solaray Dandelion Root 1040mg (180ct)",
    formulaId: "solaray-b129-076280012101",
    form: "capsule",
    barcode: "076280012118",
    actives: [
      { name: "Dandelion (root)", strength: "1040 mg" },
    ],
    flags: [
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Magnesium Stearate", "cleared", "stearate"],
      ["Rice Extract Blend", "limited", "riceextract"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Rice Extract Blend. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/dandelion-root other-ingredients: Vegetable Cellulose Capsule, Magnesium Stearate and Rice Extract Blend. Exact pack Solaray Dandelion Root 1040mg (180ct). SKU 076280012118. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280023305",
    productName: "Solaray Histamine Blend SP-33 (100ct)",
    formulaId: "solaray-b129-076280023305",
    form: "capsule",
    barcode: "076280023305",
    actives: [
      { name: "Histamine Blend", strength: "1 VegCap" },
    ],
    flags: [
      ["Magnesium Stearate", "cleared", "stearate"],
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Organic Rice Extract Blend", "limited", "riceextract"],
      ["Trace Mineral Complex", "limited", "trace"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Organic Rice Extract Blend, Trace Mineral Complex. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/histamine-blend-sp-33 other-ingredients: Magnesium Stearate, Vegetable Cellulose Capsule, Organic Rice Extract Blend, and Trace Mineral Complex. Exact pack Solaray Histamine Blend SP-33 (100ct). SKU 076280023305. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280034202",
    productName: "Solaray Feverfew Leaf Extract 400mg (60ct)",
    formulaId: "solaray-b129-076280034202",
    form: "capsule",
    barcode: "076280034202",
    actives: [
      { name: "Feverfew Leaf Extract", strength: "400 mg" },
    ],
    flags: [
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Maltodextrin (from Non-GMO Corn)", "limited", "maltodextrin"],
      ["Organic Rice Extract Blend", "limited", "riceextract"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Maltodextrin (from Non-GMO Corn), Organic Rice Extract Blend. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/feverfew-leaf-extract other-ingredients: Vegetable Cellulose Capsule, Maltodextrin (from Non-GMO Corn) and Organic Rice Extract Blend. Exact pack Solaray Feverfew Leaf Extract 400mg (60ct). SKU 076280034202. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280045260",
    productName: "Solaray Calcium & Magnesium Citrate with Vitamin D-2, 2:1 Ratio (90ct)",
    formulaId: "solaray-b129-076280045260",
    form: "capsule",
    barcode: "076280045260",
    actives: [
      { name: "Calcium & Magnesium Citrate", strength: "2:1" },
    ],
    flags: [
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Cellulose", "cleared", "mcc"],
      ["Magnesium Stearate", "cleared", "stearate"],
      ["Parsley Leaf", "cleared", "botanical"],
      ["Alfalfa Leaf", "cleared", "botanical"],
      ["Watercress Leaf", "cleared", "botanical"],
      ["Dandelion Root", "cleared", "botanical"],
    ],
    verdict: "clean",
    note: "FOUNDER-LOCK DRAFT: Clean. Every other ingredient on this panel maps to a Cleared family. No Limited or High flag.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/calcium-magnesium-citrate-with-vitamin-d-2-2-1-ratio other-ingredients: Vegetable Cellulose Capsule, Cellulose, Magnesium Stearate, Parsley Leaf, Alfalfa Leaf, Watercress Leaf and Dandelion Root. Exact pack Solaray Calcium & Magnesium Citrate with Vitamin D-2, 2:1 Ratio (90ct). SKU 076280045260. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280047073",
    productName: "Solaray OptiZinc 30mg (60ct)",
    formulaId: "solaray-b129-076280047073",
    form: "capsule",
    barcode: "076280047073",
    actives: [
      { name: "Zinc (OptiZinc)", strength: "30 mg" },
    ],
    flags: [
      ["Whole Rice Concentrate (including bran, polishing and germ)", "cleared", "riceconc"],
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Kelp", "limited", "kelp"],
      ["Magnesium Stearate", "cleared", "stearate"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Kelp. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/optizinc other-ingredients: Whole Rice Concentrate (including bran, polishing and germ), Vegetable Cellulose Capsule, Kelp and Magnesium Stearate. Exact pack Solaray OptiZinc 30mg (60ct). SKU 076280047073. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280047455",
    productName: "Solaray Twice Daily Multi Vitamin (120ct)",
    formulaId: "solaray-b129-076280047455",
    form: "capsule",
    barcode: "076280047455",
    actives: [
      { name: "Multi Vitamin", strength: "2 capsules" },
    ],
    flags: [
      ["Gelatin Capsule", "cleared", "gelatin"],
      ["Eleuthero Root", "limited", "eleuthero"],
      ["Cellulose", "cleared", "mcc"],
      ["Magnesium Stearate", "cleared", "stearate"],
      ["Sodium Alginate", "cleared", "alginate"],
      ["Silica", "limited", "sio2"],
      ["Whole Rice Concentrate (including Bran, Polishings and Germ)", "cleared", "riceconc"],
      ["Carrot Juice Powder", "limited", "juice"],
      ["Soybean Oil", "cleared", "oilfill"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Eleuthero Root, Silica, Carrot Juice Powder. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/twice-daily-multi-vitamin other-ingredients: Gelatin Capsule, Eleuthero Root, Cellulose, Magnesium Stearate, Sodium Alginate, Silica, Whole Rice Concentrate (including Bran, Polishings and Germ), Carrot Juice Powder and Soybean Oil. Exact pack Solaray Twice Daily Multi Vitamin (120ct). SKU 076280047455. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280047967",
    productName: "Solaray Children's Multivitamin (60ct)",
    formulaId: "solaray-b129-076280047967",
    form: "chewable",
    barcode: "076280047967",
    audience: KIDS,
    actives: [
      { name: "Vitamin A (as Beta Carotene)", strength: "1500 mcg" },
      { name: "Vitamin C (as Ascorbic Acid)", strength: "150 mg" },
      { name: "Vitamin D (as Cholecalciferol)", strength: "25 mcg" },
    ],
    flags: [
      ["Sorbitol", "limited", "sugaralc"],
      ["Fructose", "limited", "fructose"],
      ["Natural Cherry Flavor with other Natural Flavors", "limited", "flavor"],
      ["Hydrogenated Soybean Oil", "limited", "hvo"],
      ["Magnesium Stearate", "cleared", "stearate"],
      ["Silica", "limited", "sio2"],
      ["Glucono Delta Lactone", "cleared", "gdl"],
      ["Mono- and Diglycerides", "limited", "monodig"],
      ["Stearic Acid", "cleared", "stearate"],
      ["Rose Hips", "cleared", "botanical"],
      ["Acerola Cherry", "cleared", "botanical"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Sorbitol, Fructose, Natural Cherry Flavor with other Natural Flavors, Hydrogenated Soybean Oil, Silica, Mono- and Diglycerides. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/childrens-multi-vitamin other-ingredients: Sorbitol, Fructose, Natural Cherry Flavor with other Natural Flavors, Hydrogenated Soybean Oil, Magnesium Stearate, Silica, Glucono Delta Lactone, Mono- and Diglycerides, Stearic Acid, Rose Hips, and Acerola Cherry. Exact pack Solaray Children's Multivitamin (60ct). SKU 076280047967. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280082524",
    productName: "Solaray Oil Of Oregano 150mg (60ct)",
    formulaId: "solaray-b129-076280082524",
    form: "softgel",
    barcode: "076280082524",
    actives: [
      { name: "Oil of Oregano", strength: "150 mg" },
    ],
    flags: [
      ["Glycerin", "cleared", "glycerin"],
      ["Water", "cleared", "water"],
      ["Tapioca Starch", "cleared", "starch"],
      ["Olive Oil", "cleared", "oilfill"],
    ],
    verdict: "clean",
    note: "FOUNDER-LOCK DRAFT: Clean. Every other ingredient on this panel maps to a Cleared family. No Limited or High flag.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/oil-of-oregano other-ingredients: Softgel (Non-GMO Tapioca Starch, Non-GMO Glycerin and Water) and Olive Oil. Exact pack Solaray Oil Of Oregano 150mg (60ct). SKU 076280082524. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280083323",
    productName: "Solaray MigraGard 400mg (60ct)",
    formulaId: "solaray-b129-076280083323",
    form: "capsule",
    actives: [
      { name: "MigraGard", strength: "400 mg" },
    ],
    flags: [
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Feverfew (aerial)", "cleared", "botanical"],
      ["Maltodextrin (from Non-GMO Corn)", "limited", "maltodextrin"],
      ["Organic Rice Extract Blend", "limited", "riceextract"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Maltodextrin (from Non-GMO Corn), Organic Rice Extract Blend. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/migragard other-ingredients: Vegetable Cellulose Capsule, Feverfew (Tanacetum parthenium) (aerial), Maltodextrin (from Non-GMO Corn) and Organic Rice Extract Blend. Exact pack Solaray MigraGard 400mg (60ct). SKU 076280083323. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280084269",
    productName: "Solaray Continence with Flowtrol (60ct)",
    formulaId: "solaray-b129-076280084269",
    form: "capsule",
    barcode: "076280084269",
    actives: [
      { name: "Continence with Flowtrol", strength: "1 VegCap" },
    ],
    flags: [
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Maltodextrin", "limited", "maltodextrin"],
      ["Cellulose", "cleared", "mcc"],
      ["Calcium Phosphate", "cleared", "phosphate"],
      ["Magnesium Stearate", "cleared", "stearate"],
      ["Silica", "limited", "sio2"],
      ["Magnesium Hydroxide", "cleared", "mgoh"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Maltodextrin, Silica. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/continence-with-flowtrol other-ingredients: Vegetable Cellulose Capsule, Maltodextrin, Cellulose, Calcium Phosphate, Magnesium Stearate, Silica and Magnesium Hydroxide. Exact pack Solaray Continence with Flowtrol (60ct). SKU 076280084269. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280088618",
    productName: "Solaray Total Calm, Mood Support (30ct)",
    formulaId: "solaray-b129-076280088618",
    form: "capsule",
    barcode: "076280088618",
    actives: [
      { name: "Total Calm", strength: "2 VegCaps" },
    ],
    flags: [
      ["Modified Food Starch", "limited", "modstarch"],
      ["Corn Starch", "cleared", "starch"],
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Cellulose", "cleared", "mcc"],
      ["Silica", "limited", "sio2"],
      ["Magnesium Stearate", "cleared", "stearate"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Modified Food Starch, Silica. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/total-calm-mood-support other-ingredients: Modified Food Starch, Corn Starch, Vegetable Cellulose Capsule, Cellulose, Silica, Magnesium Stearate. Exact pack Solaray Total Calm, Mood Support (30ct). SKU 076280088618. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280223149",
    productName: "Solaray Triple Strength Tart Cherry Fruit Extract (90ct)",
    formulaId: "solaray-b129-076280223149",
    form: "capsule",
    barcode: "076280223149",
    actives: [
      { name: "Tart Cherry Fruit Extract", strength: "1 VegCap" },
    ],
    flags: [
      ["Maltodextrin (from Non-GMO Corn)", "limited", "maltodextrin"],
      ["Cellulose", "cleared", "mcc"],
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Silica", "limited", "sio2"],
      ["Organic Rice Extract Blend", "limited", "riceextract"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Maltodextrin (from Non-GMO Corn), Silica, Organic Rice Extract Blend. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/triple-strength-tart-cherry-fruit-extract other-ingredients: Maltodextrin (from Non-GMO Corn), Cellulose, Vegetable Cellulose Capsule, Silica and Organic Rice Extract Blend. Exact pack Solaray Triple Strength Tart Cherry Fruit Extract (90ct). SKU 076280223149. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280342987",
    productName: "Solaray Methyl B-12 Cherry (60ct)",
    formulaId: "solaray-b129-076280342987",
    form: "lozenge",
    barcode: "076280342987",
    actives: [
      { name: "Methyl B-12", strength: "1 VegCap" },
    ],
    flags: [
      ["Xylitol", "limited", "sugaralc"],
      ["Organic Inulin", "cleared", "inulin"],
      ["Citric Acid (from Non-GMO Tapioca)", "cleared", "citric"],
      ["Silica", "limited", "sio2"],
      ["Natural Cherry Flavor with other Natural Flavors", "limited", "flavor"],
      ["Stearic Acid", "cleared", "stearate"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Xylitol, Silica, Natural Cherry Flavor with other Natural Flavors. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/methyl-b-14 other-ingredients: Xylitol, Organic Inulin, Citric Acid (from Non-GMO Tapioca), Silica, Natural Cherry Flavor with other Natural Flavors and Stearic Acid. Exact pack Solaray Methyl B-12 Cherry (60ct). SKU 076280342987. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280361537",
    productName: "Solaray Vitamin K-2, MK-7 50mcg (30ct)",
    formulaId: "solaray-b129-076280361537",
    form: "capsule",
    barcode: "076280361537",
    actives: [
      { name: "Vitamin K-2 (MK-7)", strength: "50 mcg" },
    ],
    flags: [
      ["Cellulose", "cleared", "mcc"],
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Glycerol Monostearate", "cleared", "gms"],
      ["Magnesium Stearate", "cleared", "stearate"],
      ["Fermented Defatted Chickpea Flour Extract", "limited", "chickpea"],
      ["Organic Rice Extract Blend", "limited", "riceextract"],
      ["Silica", "limited", "sio2"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Fermented Defatted Chickpea Flour Extract, Organic Rice Extract Blend, Silica. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/vitamin-k-2-mk-7 other-ingredients: Cellulose, Vegetable Cellulose Capsule, Glycerol Monostearate, Magnesium Stearate, Fermented Defatted Chickpea Flour Extract, Organic Rice Extract Blend and Silica. Exact pack Solaray Vitamin K-2, MK-7 50mcg (30ct). SKU 076280361537. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280616903",
    productName: "Solaray Liposomal Multivitamin Women (60ct)",
    formulaId: "solaray-b129-076280616903",
    form: "capsule",
    barcode: "076280616903",
    actives: [
      { name: "Liposomal Multivitamin", strength: "2 VegCaps" },
    ],
    flags: [
      ["Cellulose", "cleared", "mcc"],
      ["Lipid Blend from Sunflower Oil", "cleared", "oilfill"],
      ["Sustainable Palm Oil", "cleared", "oilfill"],
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Stearic Acid", "cleared", "stearate"],
      ["Modified Tapioca Starch", "limited", "modstarch"],
      ["Magnesium Stearate", "cleared", "stearate"],
      ["Silica", "limited", "sio2"],
      ["Glycerol Monostearate", "cleared", "gms"],
      ["Sodium Alginate", "cleared", "alginate"],
      ["Pea Starch", "limited", "peastarch"],
      ["Tapioca Starch", "cleared", "starch"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Modified Tapioca Starch, Silica, Pea Starch. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/liposomal-multivitamin-womens-50 other-ingredients: Cellulose, Lipid Blend from Sunflower Oil and Sustainable Palm Oil, Vegetable Cellulose Capsule, Stearic Acid, Modified Tapioca Starch, Magnesium Stearate, Silica, Glycerol Monostearate, Sodium Alginate, Pea Starch, Tapioca Starch. Exact pack Solaray Liposomal Multivitamin Women (60ct). SKU 076280616903. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280882896",
    productName: "Solaray Liposomal Multivitamin Men's (60ct)",
    formulaId: "solaray-b129-076280882896",
    form: "capsule",
    barcode: "076280882896",
    actives: [
      { name: "Liposomal Multivitamin", strength: "2 VegCaps" },
    ],
    flags: [
      ["Cellulose", "cleared", "mcc"],
      ["Lipid Blend from Sunflower Oil", "cleared", "oilfill"],
      ["Sustainable Palm Oil", "cleared", "oilfill"],
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Magnesium Stearate", "cleared", "stearate"],
      ["Modified Tapioca Starch", "limited", "modstarch"],
      ["Silica", "limited", "sio2"],
      ["Sodium Alginate", "cleared", "alginate"],
      ["Pea Starch", "limited", "peastarch"],
      ["Gum Arabic", "cleared", "gum"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Modified Tapioca Starch, Silica, Pea Starch. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/liposomal-multivitamin-mens other-ingredients: Cellulose, Lipid Blend from Sunflower Oil and Sustainable Palm Oil, Vegetable Cellulose Capsule, Magnesium Stearate, Modified Tapioca Starch, Silica, Sodium Alginate, Pea Starch and Gum Arabic. Exact pack Solaray Liposomal Multivitamin Men's (60ct). SKU 076280882896. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280903522",
    productName: "Solaray Curcumin Root Extract 250mg (30ct)",
    formulaId: "solaray-b129-076280903522",
    form: "softgel",
    actives: [
      { name: "Curcumin Root Extract", strength: "250 mg" },
    ],
    flags: [
      ["Medium Chain Triglycerides (coconut)", "cleared", "mctcoco"],
      ["Gelatin", "cleared", "gelatin"],
      ["Glycerin", "cleared", "glycerin"],
      ["Lecithin (soy)", "cleared", "lecithin"],
      ["Yellow Beeswax", "cleared", "beeswax"],
      ["Sunflower Oil", "cleared", "oilfill"],
    ],
    verdict: "clean",
    note: "FOUNDER-LOCK DRAFT: Clean. Every other ingredient on this panel maps to a Cleared family. No Limited or High flag.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/curcumin-root-extract other-ingredients: Medium Chain Triglycerides (coconut), Softgel (Gelatin and Glycerin), Lecithin (soy), Yellow Beeswax and Sunflower Oil. Exact pack Solaray Curcumin Root Extract 250mg (30ct). SKU 076280903522. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280039054",
    productName: "Solaray Valerian Root Extract 300mg (30ct)",
    formulaId: "solaray-b129-076280039054",
    form: "capsule",
    barcode: "076280039054",
    actives: [
      { name: "Valerian (root extract)", strength: "300 mg" },
    ],
    flags: [
      ["Maltodextrin (from Non-GMO Corn)", "limited", "maltodextrin"],
      ["Whole Rice Concentrate", "cleared", "riceconc"],
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Silica", "limited", "sio2"],
      ["Chicory Root Inulin", "cleared", "inulin"],
      ["Organic Rice Extract Blend", "limited", "riceextract"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Maltodextrin (from Non-GMO Corn), Silica, Organic Rice Extract Blend. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/valerian-root-extract-one-daily other-ingredients: Maltodextrin (from Non-GMO Corn), Whole Rice Concentrate, Vegetable Cellulose Capsule, Silica, Chicory Root Inulin and Organic Rice Extract Blend. Exact pack Solaray Valerian Root Extract 300mg (30ct). SKU 076280039054. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280045307",
    productName: "Solaray Calcium & Magnesium, AAC 2:1 (90ct)",
    formulaId: "solaray-b129-076280045307",
    form: "capsule",
    barcode: "076280045307",
    actives: [
      { name: "Calcium & Magnesium AAC", strength: "2:1" },
    ],
    flags: [
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Cellulose", "cleared", "mcc"],
      ["Citric Acid (from Non-GMO Tapioca)", "cleared", "citric"],
      ["L-Aspartic Acid", "limited", "amino"],
      ["Magnesium Stearate", "cleared", "stearate"],
      ["Whole Rice Concentrate", "cleared", "riceconc"],
      ["Rice Protein", "cleared", "riceprotein"],
      ["Alfalfa Aerial", "cleared", "botanical"],
      ["Dandelion Root", "cleared", "botanical"],
      ["Watercress Leaf", "cleared", "botanical"],
      ["Parsley Aerial", "cleared", "botanical"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: L-Aspartic Acid. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/calcium-magnesium-amino-acid-chelate-2-1-ratio other-ingredients: Vegetable Cellulose Capsule, Cellulose, Citric Acid (from Non-GMO Tapioca), L-Aspartic Acid, Magnesium Stearate, Whole Rice Concentrate, Rice Protein, Alfalfa Aerial, Dandelion Root, Watercress Leaf and Parsley Aerial. Exact pack Solaray Calcium & Magnesium, AAC 2:1 (90ct). SKU 076280045307. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280047912",
    productName: "Solaray Hair Nutrients (120ct)",
    formulaId: "solaray-b129-076280047912",
    form: "capsule",
    barcode: "076280047912",
    actives: [
      { name: "Hair Nutrients", strength: "2 VegCaps" },
    ],
    flags: [
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Cellulose", "cleared", "mcc"],
      ["Rice Flour", "limited", "ricepowder"],
      ["Magnesium Stearate", "cleared", "stearate"],
      ["Silica", "limited", "sio2"],
      ["Alfalfa Leaf", "cleared", "botanical"],
      ["Parsley Leaf", "cleared", "botanical"],
      ["Watercress Leaf", "cleared", "botanical"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Rice Flour, Silica. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/hair-nutrients other-ingredients: Vegetable Cellulose Capsule, Cellulose, Rice Flour, Magnesium Stearate, Silica, Alfalfa Leaf, Parsley Leaf and Watercress Leaf. Exact pack Solaray Hair Nutrients (120ct). SKU 076280047912. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280644753",
    productName: "Solaray Super Forskohlii Root Extract 400mg (60ct)",
    formulaId: "solaray-b129-076280644753",
    form: "capsule",
    barcode: "076280644753",
    actives: [
      { name: "Forskohlii (root extract)", strength: "400 mg" },
    ],
    flags: [
      ["Vegetarian Capsule", "limited", "shell"],
      ["Rice Flour", "limited", "ricepowder"],
      ["Organic Rice Extract Blend", "limited", "riceextract"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Vegetarian Capsule, Rice Flour, Organic Rice Extract Blend. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/super-forskohlii-root-exract other-ingredients: Vegetarian Capsule, Rice Flour and Organic Rice Extract Blend. Exact pack Solaray Super Forskohlii Root Extract 400mg (60ct). SKU 076280644753. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280648843",
    productName: "Solaray Cal-Mag Citrate with D-3 & K-2, 2:1 Ratio (180ct)",
    formulaId: "solaray-b129-076280648843",
    form: "capsule",
    barcode: "076280648843",
    actives: [
      { name: "Cal-Mag Citrate", strength: "6 capsules" },
    ],
    flags: [
      ["Gelatin Capsule", "cleared", "gelatin"],
      ["Magnesium Stearate", "cleared", "stearate"],
      ["Alfalfa Leaf", "cleared", "botanical"],
      ["Watercress Leaf", "cleared", "botanical"],
      ["Dandelion Root", "cleared", "botanical"],
    ],
    verdict: "clean",
    note: "FOUNDER-LOCK DRAFT: Clean. Every other ingredient on this panel maps to a Cleared family. No Limited or High flag.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/cal-mag-citrate-w-d-3-k-2 other-ingredients: Gelatin Capsule, Magnesium Stearate, Alfalfa Leaf, Watercress Leaf and Dandelion Root. Exact pack Solaray Cal-Mag Citrate with D-3 & K-2, 2:1 Ratio (180ct). SKU 076280648843. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280043525",
    productName: "Solaray Folic Acid (Vitamin B-9) (100ct)",
    formulaId: "solaray-b129-076280043525",
    form: "capsule",
    barcode: "076280043525",
    actives: [
      { name: "Folate", strength: "800 mcg DFE" },
    ],
    flags: [
      ["Whole Rice Concentrate", "cleared", "riceconc"],
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Aloe Vera Gel (200x dry concentrate)", "limited", "aloe"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Aloe Vera Gel (200x dry concentrate). No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/folic-acid-vitamin-b-9 other-ingredients: Whole Rice Concentrate, Vegetable Cellulose Capsule and Aloe Vera Gel (200x dry concentrate). Exact pack Solaray Folic Acid (Vitamin B-9) (100ct). SKU 076280043525. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280043594",
    productName: "Solaray Niacin 100mg (100ct)",
    formulaId: "solaray-b129-076280043594",
    form: "capsule",
    barcode: "076280043594",
    actives: [
      { name: "Niacin", strength: "100 mg" },
    ],
    flags: [
      ["Whole Rice Concentrate (Including Bran, Polishings, and Germ)", "cleared", "riceconc"],
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Aloe Vera Gel", "limited", "aloe"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Aloe Vera Gel. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/niacin other-ingredients: Whole Rice Concentrate (Including Bran, Polishings, and Germ), Vegetable Cellulose Capsule and Aloe Vera Gel. Exact pack Solaray Niacin 100mg (100ct). SKU 076280043594. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280043709",
    productName: "Solaray Pantothenic Acid 250mg (100ct)",
    formulaId: "solaray-b129-076280043709",
    form: "capsule",
    barcode: "076280043709",
    actives: [
      { name: "Pantothenic Acid", strength: "250 mg" },
    ],
    flags: [
      ["Gelatin Capsule", "cleared", "gelatin"],
      ["Whole Food Base (Whole Rice Concentrate including the Kernel, Polishings, and Hull, and Aloe Vera Gel)", "cleared", "riceconc"],
      ["Aloe Vera Gel", "limited", "aloe"],
      ["Magnesium Stearate", "cleared", "stearate"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Aloe Vera Gel. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/pantothenic-acid-1 other-ingredients: Gelatin Capsule, Whole Food Base (Whole Rice Concentrate including the Kernel, Polishings, and Hull, and Aloe Vera Gel) and Magnesium Stearate. Exact pack Solaray Pantothenic Acid 250mg (100ct). SKU 076280043709. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280110098",
    productName: "Solaray HMB + Vitamin D3 Vanilla (30 servings)",
    formulaId: "solaray-b129-076280110098",
    form: "powder",
    actives: [
      { name: "HMB + Vitamin D3", strength: "1 scoop" },
    ],
    flags: [
      ["Natural Vanilla Flavor with Other Natural Flavors", "limited", "flavor"],
      ["Sea Salt", "cleared", "salt"],
      ["Steviol Glycoside", "limited", "stevia"],
      ["Silica", "limited", "sio2"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Natural Vanilla Flavor with Other Natural Flavors, Steviol Glycoside, Silica. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/hmb-vitamin-d3 other-ingredients: Natural Vanilla Flavor with Other Natural Flavors, Sea Salt, Steviol Glycoside, and Silica. Exact pack Solaray HMB + Vitamin D3 Vanilla (30 servings). SKU 076280110098. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280149074",
    productName: "Solaray Vegan Collagen Booster (25 servings)",
    formulaId: "solaray-b129-076280149074",
    form: "powder",
    actives: [
      { name: "Vegan Collagen Booster", strength: "1 scoop" },
    ],
    flags: [
      ["Natural Vanilla Flavor with Other Natural Flavors", "limited", "flavor"],
      ["Sea Salt", "cleared", "salt"],
      ["Gotu Kola (Centella asiatica) (extract)", "limited", "gotu"],
      ["Steviol Glycoside", "limited", "stevia"],
      ["Silica", "limited", "sio2"],
      ["Ginseng (Panax ginseng) (root extract)", "cleared", "botanical"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Natural Vanilla Flavor with Other Natural Flavors, Gotu Kola (Centella asiatica) (extract), Steviol Glycoside, Silica. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/vegan-collagen-booster other-ingredients: Natural Vanilla Flavor with Other Natural Flavors, Sea Salt, Gotu Kola (Centella asiatica) (extract), Steviol Glycoside, Silica, Ginseng (Panax ginseng) (root extract). Exact pack Solaray Vegan Collagen Booster (25 servings). SKU 076280149074. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280329568",
    productName: "Solaray Plant Melatonin (30ct)",
    formulaId: "solaray-b129-076280329568",
    form: "capsule",
    barcode: "076280329568",
    actives: [
      { name: "Plant Melatonin", strength: "1 VegCap" },
    ],
    flags: [
      ["Cellulose", "cleared", "mcc"],
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Tapioca Dextrin", "limited", "tdextrin"],
      ["Stearic Acid", "cleared", "stearate"],
      ["Silica", "limited", "sio2"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Tapioca Dextrin, Silica. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/plant-melatonin other-ingredients: Cellulose, Vegetable Cellulose Capsule, Tapioca Dextrin, Stearic Acid, and Silica. Exact pack Solaray Plant Melatonin (30ct). SKU 076280329568. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280529586",
    productName: "Solaray Colostrum+ Unflavored (30 servings)",
    formulaId: "solaray-b129-076280529586",
    form: "powder",
    actives: [
      { name: "Colostrum", strength: "1 scoop" },
    ],
    flags: [
      ["Acacia Gum", "cleared", "gum"],
      ["Sea Salt", "cleared", "salt"],
    ],
    verdict: "clean",
    note: "FOUNDER-LOCK DRAFT: Clean. Every other ingredient on this panel maps to a Cleared family. No Limited or High flag.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/colostrum other-ingredients: Acacia Gum and Sea Salt. Exact pack Solaray Colostrum+ Unflavored (30 servings). SKU 076280529586. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280582505",
    productName: "Solaray Colostrum+ Peach Mango (30 servings)",
    formulaId: "solaray-b129-076280582505",
    form: "powder",
    actives: [
      { name: "Colostrum", strength: "1 scoop" },
    ],
    flags: [
      ["Natural Peach", "limited", "flavor"],
      ["Mango Flavors with Other Natural Flavors", "limited", "flavor"],
      ["Citric Acid", "cleared", "citric"],
      ["Acacia Gum", "cleared", "gum"],
      ["Stevia (leaf extract)", "limited", "stevia"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Natural Peach, Mango Flavors with Other Natural Flavors, Stevia (leaf extract). No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/colostrum other-ingredients: Natural Peach and Mango Flavors with Other Natural Flavors, Citric Acid, Acacia Gum, and Stevia (leaf extract). Exact pack Solaray Colostrum+ Peach Mango (30 servings). SKU 076280582505. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280595499",
    productName: "Solaray NADH (30ct)",
    formulaId: "solaray-b129-076280595499",
    form: "capsule",
    barcode: "076280595499",
    actives: [
      { name: "NADH", strength: "1 VegCap" },
    ],
    flags: [
      ["Cellulose", "cleared", "mcc"],
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Fractionated Palm Oil", "cleared", "oilfill"],
      ["Beeswax", "cleared", "beeswax"],
      ["Chlorophyllin", "limited", "chlorophyllin"],
      ["Stearic Acid", "cleared", "stearate"],
      ["Silica", "limited", "sio2"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Chlorophyllin, Silica. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/nadh other-ingredients: Cellulose, Vegetable Cellulose Capsule, Fractionated Palm Oil, Beeswax, Chlorophyllin, Stearic Acid, and Silica. Exact pack Solaray NADH (30ct). SKU 076280595499. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280598933",
    productName: "Solaray Aged Black Garlic (30ct)",
    formulaId: "solaray-b129-076280598933",
    form: "capsule",
    barcode: "076280598933",
    actives: [
      { name: "Aged Black Garlic", strength: "1 VegCap" },
    ],
    flags: [
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Acacia Gum", "cleared", "gum"],
      ["Cellulose", "cleared", "mcc"],
      ["Silica", "limited", "sio2"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Silica. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/aged-black-garlic other-ingredients: Vegetable Cellulose Capsule, Acacia Gum, Cellulose, and Silica. Exact pack Solaray Aged Black Garlic (30ct). SKU 076280598933. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280728507",
    productName: "Solaray Liposomal Glutathione (60ct)",
    formulaId: "solaray-b129-076280728507",
    form: "capsule",
    barcode: "076280728507",
    actives: [
      { name: "Liposomal Glutathione", strength: "2 VegCaps" },
    ],
    flags: [
      ["Cellulose", "cleared", "mcc"],
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Sunflower Phospholipids", "cleared", "lecithin"],
      ["Stearic Acid", "cleared", "stearate"],
      ["Silica", "limited", "sio2"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Silica. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/liposomal-glutathione other-ingredients: Cellulose, Vegetable Cellulose Capsule, Sunflower Phospholipids, Stearic Acid, and Silica. Exact pack Solaray Liposomal Glutathione (60ct). SKU 076280728507. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280788020",
    productName: "Solaray Spermidine (60ct)",
    formulaId: "solaray-b129-076280788020",
    form: "capsule",
    barcode: "076280788020",
    actives: [
      { name: "Spermidine", strength: "1 VegCap" },
    ],
    flags: [
      ["Tapioca Dextrin", "limited", "tdextrin"],
      ["Cellulose", "cleared", "mcc"],
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Citric Acid", "cleared", "citric"],
      ["Silica", "limited", "sio2"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Tapioca Dextrin, Silica. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/spermidine other-ingredients: Tapioca Dextrin, Cellulose, Vegetable Cellulose Capsule, Citric Acid, and Silica. Exact pack Solaray Spermidine (60ct). SKU 076280788020. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280886757",
    productName: "Solaray Opti-5 Magnesium (60ct)",
    formulaId: "solaray-b129-076280886757",
    form: "capsule",
    barcode: "076280886757",
    actives: [
      { name: "Magnesium", strength: "2 VegCaps" },
    ],
    flags: [
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Arabic Gum", "cleared", "gum"],
      ["Cellulose", "cleared", "mcc"],
    ],
    verdict: "clean",
    note: "FOUNDER-LOCK DRAFT: Clean. Every other ingredient on this panel maps to a Cleared family. No Limited or High flag.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/opti-5-magnesium other-ingredients: Vegetable Cellulose Capsule, Arabic Gum, and Cellulose. Exact pack Solaray Opti-5 Magnesium (60ct). SKU 076280886757. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280937145",
    productName: "Solaray Nattokinase and Serrapeptase (30ct)",
    formulaId: "solaray-b129-076280937145",
    form: "capsule",
    barcode: "076280937145",
    actives: [
      { name: "Nattokinase", strength: "150 mg" },
      { name: "Serrapeptase", strength: "30 mg" },
    ],
    flags: [
      ["Cellulose", "cleared", "mcc"],
      ["Vegetable Cellulose", "cleared", "mcc"],
      ["Silica", "limited", "sio2"],
      ["Magnesium Stearate", "cleared", "stearate"],
      ["Dextrin", "limited", "dextrin"],
      ["Enteric Coating", "limited", "enteric"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Silica, Dextrin, Enteric Coating. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/solaray-nattokinase-serrapeptase-supplement-3-000-fu-healthy-circulation-blood-flow-sup other-ingredients: Cellulose, Vegetable Cellulose, Silica, Magnesium Stearate, Dextrin and Enteric Coating. Exact pack Solaray Nattokinase and Serrapeptase (30ct). SKU 076280937145. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280968682",
    productName: "Solaray Liposomal Multivitamin Prenatal (60ct)",
    formulaId: "solaray-b129-076280968682",
    form: "capsule",
    barcode: "076280968682",
    actives: [
      { name: "Liposomal Prenatal", strength: "2 VegCaps" },
    ],
    flags: [
      ["Lipid Blend from Sunflower Oil", "cleared", "oilfill"],
      ["Sustainable Palm Oil", "cleared", "oilfill"],
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Cellulose", "cleared", "mcc"],
      ["Magnesium Stearate", "cleared", "stearate"],
      ["Modified Tapioca Starch", "limited", "modstarch"],
      ["Silica", "limited", "sio2"],
      ["Sodium Alginate", "cleared", "alginate"],
      ["Pea Starch", "limited", "peastarch"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Modified Tapioca Starch, Silica, Pea Starch. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/liposomal-prenatal other-ingredients: Lipid Blend from Sunflower Oil and Sustainable Palm Oil, Vegetable Cellulose Capsule, Cellulose, Magnesium Stearate, Modified Tapioca Starch, Silica, Sodium Alginate, and Pea Starch. Exact pack Solaray Liposomal Multivitamin Prenatal (60ct). SKU 076280968682. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280021301",
    productName: "Solaray Liver Blend SP-13 (100ct)",
    formulaId: "solaray-b129-076280021301",
    form: "capsule",
    barcode: "076280021301",
    actives: [
      { name: "Proprietary Blend", strength: "475 mg" },
    ],
    flags: [
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Trace Mineral Complex", "limited", "trace"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Trace Mineral Complex. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/liver-blend-sp-13 other-ingredients: Vegetable Cellulose Capsule and Trace Mineral Complex. Exact pack Solaray Liver Blend SP-13 (100ct). SKU 076280021301. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280045772",
    productName: "Solaray Boron Citrate 3mg (60ct)",
    formulaId: "solaray-b129-076280045772",
    form: "capsule",
    actives: [
      { name: "Boron (as Boron Citrate)", strength: "3 mg" },
    ],
    flags: [
      ["Rice Flour", "limited", "ricepowder"],
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Organic Alfalfa", "cleared", "botanical"],
      ["Cellulose", "cleared", "mcc"],
      ["Parsley Leaf", "cleared", "botanical"],
      ["Kelp", "limited", "kelp"],
      ["Rice Bran Extract", "cleared", "ricebran"],
      ["Silica", "limited", "sio2"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Rice Flour, Kelp, Silica. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/boron-citrate other-ingredients: Rice Flour, Vegetable Cellulose Capsule, Organic Alfalfa, Cellulose, Parsley Leaf, Kelp, Rice Bran Extract and Silica. Exact pack Solaray Boron Citrate 3mg (60ct). SKU 076280045772. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280130645",
    productName: "Solaray Acetyl L-Carnitine 500mg (30ct)",
    formulaId: "solaray-b129-076280130645",
    form: "capsule",
    barcode: "076280130645",
    actives: [
      { name: "Acetyl L-Carnitine", strength: "500 mg" },
    ],
    flags: [
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Cellulose", "cleared", "mcc"],
      ["Silica", "limited", "sio2"],
      ["Rice Hull Concentrate", "cleared", "riceconc"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Silica. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/acetyl-l-carnitine other-ingredients: Vegetable Cellulose Capsule, Cellulose, Silica and Rice Hull Concentrate. Exact pack Solaray Acetyl L-Carnitine 500mg (30ct). SKU 076280130645. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280036008",
    productName: "Solaray Ginkgo Biloba Leaf Extract 60mg (60ct)",
    formulaId: "solaray-b129-076280036008",
    form: "capsule",
    barcode: "076280036008",
    actives: [
      { name: "Ginkgo (leaf extract)", strength: "60 mg" },
    ],
    flags: [
      ["Whole Rice Concentrate", "cleared", "riceconc"],
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Organic Agave Inulin", "cleared", "inulin"],
      ["Rice Hull Concentrate", "cleared", "riceconc"],
    ],
    verdict: "clean",
    note: "FOUNDER-LOCK DRAFT: Clean. Every other ingredient on this panel maps to a Cleared family. No Limited or High flag.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/ginkgo-biloba-leaf-extract other-ingredients: Whole Rice Concentrate, Vegetable Cellulose Capsule, Organic Agave Inulin and Rice Hull Concentrate. Exact pack Solaray Ginkgo Biloba Leaf Extract 60mg (60ct). SKU 076280036008. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280036039",
    productName: "Solaray Ginkgo Biloba Extract, One Daily 120mg (30ct)",
    formulaId: "solaray-b129-076280036039",
    form: "capsule",
    actives: [
      { name: "Ginkgo (leaf extract)", strength: "120 mg" },
      { name: "Gotu Kola (aerial)", strength: "180 mg" },
    ],
    flags: [
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Organic Agave Inulin", "cleared", "inulin"],
      ["Rice Bran Extract", "cleared", "ricebran"],
    ],
    verdict: "clean",
    note: "FOUNDER-LOCK DRAFT: Clean. Every other ingredient on this panel maps to a Cleared family. No Limited or High flag.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/ginkgo-biloba-extract-one-daily other-ingredients: Vegetable Cellulose Capsule, Organic Agave Inulin and Rice Bran Extract. Exact pack Solaray Ginkgo Biloba Extract, One Daily 120mg (30ct). SKU 076280036039. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280037661",
    productName: "Solaray Saw Palmetto & Pygeum with Zinc & Vitamin E (30ct)",
    formulaId: "solaray-b129-076280037661",
    form: "softgel",
    actives: [
      { name: "Saw Palmetto (berry oil)", strength: "320 mg" },
      { name: "Pygeum (bark extract)", strength: "100 mg" },
    ],
    flags: [
      ["Gelatin", "cleared", "gelatin"],
      ["Glycerin", "cleared", "glycerin"],
      ["Pumpkin Seed Oil", "cleared", "oilfill"],
      ["Nettle Leaf", "cleared", "botanical"],
      ["Lecithin (soy)", "cleared", "lecithin"],
      ["Beeswax", "cleared", "beeswax"],
      ["L-Alanine", "limited", "amino"],
      ["Glutamic Acid", "limited", "amino"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: L-Alanine, Glutamic Acid. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/pygeum-bark-saw-palmetto-ext other-ingredients: Gelatin, Glycerin, Pumpkin Seed Oil, Nettle Leaf, Lecithin (soy), Beeswax, L-Alanine, and Glutamic Acid. Exact pack Solaray Saw Palmetto & Pygeum with Zinc & Vitamin E (30ct). SKU 076280037661. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280042702",
    productName: "Solaray Vitamin B-Complex 50mg (50ct)",
    formulaId: "solaray-b129-076280042702",
    form: "capsule",
    barcode: "076280042702",
    actives: [
      { name: "Vitamin B-Complex", strength: "50 mg" },
    ],
    flags: [
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Whole Food Base (Whole Rice Concentrate and Aloe Vera Gel)", "cleared", "riceconc"],
      ["Aloe Vera Gel", "limited", "aloe"],
      ["Magnesium Stearate", "cleared", "stearate"],
      ["Silica", "limited", "sio2"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Aloe Vera Gel, Silica. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/vitamin-b-complex-50 other-ingredients: Vegetable Cellulose Capsule, Whole Food Base (Whole Rice Concentrate and Aloe Vera Gel), Magnesium Stearate and Silica. Exact pack Solaray Vitamin B-Complex 50mg (50ct). SKU 076280042702. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280042726",
    productName: "Solaray Vitamin B-Complex 50mg (250ct)",
    formulaId: "solaray-b129-076280042702",
    form: "capsule",
    barcode: "076280042726",
    actives: [
      { name: "Vitamin B-Complex", strength: "50 mg" },
    ],
    flags: [
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Whole Food Base (Whole Rice Concentrate and Aloe Vera Gel)", "cleared", "riceconc"],
      ["Aloe Vera Gel", "limited", "aloe"],
      ["Magnesium Stearate", "cleared", "stearate"],
      ["Silica", "limited", "sio2"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Aloe Vera Gel, Silica. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/vitamin-b-complex-50 other-ingredients: Vegetable Cellulose Capsule, Whole Food Base (Whole Rice Concentrate and Aloe Vera Gel), Magnesium Stearate and Silica. Exact pack Solaray Vitamin B-Complex 50mg (250ct). SKU 076280042726. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280043013",
    productName: "Solaray Vitamin B-Complex 100 (100ct)",
    formulaId: "solaray-b129-076280043013",
    form: "capsule",
    barcode: "076280043013",
    actives: [
      { name: "Vitamin B-Complex", strength: "100 mg" },
    ],
    flags: [
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Silica", "limited", "sio2"],
      ["Magnesium Stearate", "cleared", "stearate"],
      ["Whole Food Base (Whole Rice Concentrate including Bran, Germ and Polishings, and Aloe Vera Gel)", "cleared", "riceconc"],
      ["Aloe Vera Gel", "limited", "aloe"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Silica, Aloe Vera Gel. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/vitamin-b-complex-100 other-ingredients: Vegetable Cellulose Capsule, Silica, Magnesium Stearate and Whole Food Base (Whole Rice Concentrate including Bran, Germ and Polishings, and Aloe Vera Gel). Exact pack Solaray Vitamin B-Complex 100 (100ct). SKU 076280043013. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280043006",
    productName: "Solaray Vitamin B-Complex 100 (50ct)",
    formulaId: "solaray-b129-076280043013",
    form: "capsule",
    barcode: "076280043006",
    actives: [
      { name: "Vitamin B-Complex", strength: "100 mg" },
    ],
    flags: [
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Silica", "limited", "sio2"],
      ["Magnesium Stearate", "cleared", "stearate"],
      ["Whole Food Base (Whole Rice Concentrate including Bran, Germ and Polishings, and Aloe Vera Gel)", "cleared", "riceconc"],
      ["Aloe Vera Gel", "limited", "aloe"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Silica, Aloe Vera Gel. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/vitamin-b-complex-100 other-ingredients: Vegetable Cellulose Capsule, Silica, Magnesium Stearate and Whole Food Base (Whole Rice Concentrate including Bran, Germ and Polishings, and Aloe Vera Gel). Exact pack Solaray Vitamin B-Complex 100 (50ct). SKU 076280043006. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280374025",
    productName: "Solaray Magnesium Citrate 400mg (180ct)",
    formulaId: "solaray-b129-076280374025",
    form: "capsule",
    barcode: "076280374025",
    actives: [
      { name: "Magnesium (from Magnesium Citrate)", strength: "400 mg" },
    ],
    flags: [
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Cellulose", "cleared", "mcc"],
      ["Magnesium Stearate", "cleared", "stearate"],
      ["Watercress Leaf", "cleared", "botanical"],
      ["Dandelion Root", "cleared", "botanical"],
      ["Alfalfa Leaf", "cleared", "botanical"],
      ["Parsley Leaf", "cleared", "botanical"],
    ],
    verdict: "clean",
    note: "FOUNDER-LOCK DRAFT: Clean. Every other ingredient on this panel maps to a Cleared family. No Limited or High flag.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/magnesium-citrate other-ingredients: Vegetable Cellulose Capsule, Cellulose, Magnesium Stearate, Watercress Leaf, Dandelion Root, Alfalfa Leaf and Parsley Leaf. Exact pack Solaray Magnesium Citrate 400mg (180ct). SKU 076280374025. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280045918",
    productName: "Solaray GTF Chromium 200mcg (200ct)",
    formulaId: "solaray-b126-076280045901",
    form: "capsule",
    barcode: "076280045918",
    actives: [
      { name: "Chromium (from GTF Chromium Yeast)", strength: "200 mcg" },
    ],
    flags: [
      ["Brewer's Yeast", "cleared", "yeast"],
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Magnesium Stearate", "cleared", "stearate"],
    ],
    verdict: "clean",
    note: "FOUNDER-LOCK DRAFT: Clean. Every other ingredient on this panel maps to a Cleared family. No Limited or High flag.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/gtf-chromium other-ingredients: Brewer's Yeast, Vegetable Cellulose Capsule and Magnesium Stearate. Exact pack Solaray GTF Chromium 200mcg (200ct). SKU 076280045918. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280046717",
    productName: "Solaray Potassium 99mg (200ct)",
    formulaId: "solaray-b129-076280046717",
    form: "capsule",
    barcode: "076280046717",
    actives: [
      { name: "Potassium (from Potassium Amino Acid Complex)", strength: "99 mg" },
    ],
    flags: [
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Rice Flour", "limited", "ricepowder"],
      ["Magnesium Stearate", "cleared", "stearate"],
      ["Citric Acid", "cleared", "citric"],
      ["Parsley", "cleared", "botanical"],
      ["Chamomile", "cleared", "botanical"],
      ["Watercress", "cleared", "botanical"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Rice Flour. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/potassium-99 other-ingredients: Vegetable Cellulose Capsule, Rice Flour, Magnesium Stearate, Citric Acid, Parsley, Chamomile and Watercress. Exact pack Solaray Potassium 99mg (200ct). SKU 076280046717. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280127430",
    productName: "Solaray Vitamin B-6, Timed-Release 100mg (120ct)",
    formulaId: "solaray-b129-076280127430",
    form: "capsule",
    barcode: "076280127430",
    actives: [
      { name: "Vitamin B-6 (as Pyridoxine HCl)", strength: "100 mg" },
    ],
    flags: [
      ["Whole Food Base (Whole Rice Concentrate including the Bran, Polishings and Germ, and Aloe Vera Gel)", "cleared", "riceconc"],
      ["Aloe Vera Gel", "limited", "aloe"],
      ["Vegetable Cellulose Capsule", "cleared", "vegcap"],
      ["Cellulose", "cleared", "mcc"],
      ["Stearic Acid", "cleared", "stearate"],
    ],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver families: Aloe Vera Gel. No High.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/vitamin-b-6-timed-release other-ingredients: Whole Food Base (Whole Rice Concentrate including the Bran, Polishings and Germ, and Aloe Vera Gel), Vegetable Cellulose Capsule, Cellulose and Stearic Acid. Exact pack Solaray Vitamin B-6, Timed-Release 100mg (120ct). SKU 076280127430. " + UPC_BLANK,
  },
  {
    id: "solaray-b129-076280046618",
    productName: "Solaray Potassium Asporotate 99mg (200ct)",
    formulaId: "solaray-b129-076280046618",
    form: "capsule",
    barcode: "076280046618",
    actives: [
      { name: "Potassium (from Potassium Asporotate)", strength: "99 mg" },
    ],
    flags: [
      ["Gelatin Capsule", "cleared", "gelatin"],
      ["Herb Base (Parsley Leaf, Chamomile, Watercress)", "cleared", "herbbase"],
      ["Magnesium Stearate", "cleared", "stearate"],
    ],
    verdict: "clean",
    note: "FOUNDER-LOCK DRAFT: Clean. Every other ingredient on this panel maps to a Cleared family. No Limited or High flag.",
    cite: "solaray.com / opened US listing https://www.solaray.com/products/potassium-asporotate other-ingredients: Gelatin Capsule, Herb Base (Parsley Leaf, Chamomile, Watercress) and Magnesium Stearate. Exact pack Solaray Potassium Asporotate 99mg (200ct). SKU 076280046618. " + UPC_BLANK,
  },
];

export const BATCH129_KYR6B_SOLARAY_OCR_NO_OI: RatingRecord[] = COMPACT.map(expand);

export const BATCH129_SKIPPED_NO_OI: { sku: string; name: string; count: string; why: string }[] = [
  {
    sku: "076280830385",
    name: "Liposomal Multivitamin Universal",
    count: "60ct",
    why: "solaray.com images for this variant are named 076280640168, including the facts tile. That sibling panel was not copied. No opened US page printed this pack's Other Ingredients.",
  },
];

export const BATCH129_SKIPPED_OUT: { sku: string; name: string; why: string }[] = [];

export const BATCH129_LEFTOVER_REAL_TOKENS: string[] = [];

