// DRAFT / not verified / batch 83 KYR6 NatureWise leftover-token backfill.
// Methodology v1.6 + MAIN §5 after the Sept 23, 2026 NatureWise token stamp
// (b1cf3a7). Harm-first. No invented grades. No invented OI. No invented UPCs.
// Founder owns final Avoid vs Caution vs Clean.
//
// ONE write. NatureWise only. Unlocks batch82 REFUSED rows whose blocking
// tokens are now stamped on MAIN, or that use an existing oil form split.
// naturewise.com supplement-facts images are the pin. Amazon US was a 503
// in this environment, so no row is pinned from an Amazon carousel.
// OCR-garbage panels stay refused. HTML bullets were not treated as a panel.
// batch82 no_OI 28 was not hunted. OUT 15 was not reopened.
// recordStatus is 'unverified' on every row.
// Internal keys only: clean | caution | avoid. Pack sizes of the same
// OI+form share formulaId. Search wiring only. Not wired into Clean Picks UI.
//
// Do NOT edit batch70–batch82. No WELMATE. No A+Health / HealthA2Z /
// TIME-Cap / GoodSense. No toothpaste. No house Amazon. No Sprouts.
// No graded oil pour bottles. Leftover Amazon 3P stays N=5.
//
// TALLY (unverified drafts in THIS file): 54 rows —
// Clean 0 / Caution 54 / Avoid 0.
// NEW 35 / REUSE-formula 19 / SKIPPED 2 (no_OI 0 / OUT 0 / other 2 —
// Magnesium Glycinate 625 mg count tabs have no supplement-facts image) /
// REFUSED 6.
// Search grade: Clean 0 / Caution 54 / Avoid 0.
// TALLY is asserted at the bottom.

import type {
  CleanAlternative,
  IngredientFlag,
  RatingRecord,
} from '../ratingRecord';

const UNVERIFIED = 'unverified' as const;
const ADULT = 'adult' as const;
const SUPPLEMENT = 'Supplement' as const;
const UNVERIFIED_NOTE = 'draft, not verified';

const BRAND = 'NatureWise';
const AMAZON = ['Amazon', 'naturewise.com'] as const;

const LIMITED_STACK =
  'Limited-only stack stays Caution (no 3-pt Avoid). Limited-only never Avoid. Avoid needs High.';

const METH = {
  annatto: "Methodology §5 Caution (annatto / annatto (color)). Not Avoid.",
  bamboo: "Methodology §5 Limited-risk (bamboo extract / bambusa vulgaris shoot — mapped to organic bamboo extract; Caution; extract; not a named-color pass; locked Sept 22, 2026, bare string mapped Sept 23, 2026). Not Avoid.",
  bareStarch: "Methodology §5 Limited-risk (unspecified starch — exact token when the label prints bare starch; Caution; distinct from Limited modified starch and from Cleared named corn / potato / tapioca starch; locked Sept 22, 2026). Not Avoid.",
  beetColor: "Methodology §5 Cleared (beet root (color) / beet root powder (for color) — named plant color; locked Sept 22, 2026).",
  caCarb: "Methodology §5 Cleared (calcium carbonate as Other Ingredient filler — distinct from calcium as a labeled active).",
  carrageenan: "Methodology §5 Limited-risk (carrageenan). Not Avoid.",
  chlorophyllin: "Methodology §5 Caution (sodium copper chlorophyllin — copper-complex color; not raw chlorophyll; locked Sept 14, 2026). Not Avoid.",
  citric: "Methodology §5 Cleared (citric acid).",
  coconut: "Methodology §5 Cleared (organic extra virgin coconut oil as softgel fill). Not gummy seed-oil High. Not an oil-bottle grade.",
  cornFill: "Methodology §5 Cleared as non-gummy fill (corn oil on a capsule or softgel — not the gummy seed-oil High rule; locked Sept 23, 2026). Gummy corn oil stays Avoid. Same oil form split as soybean oil. Not an oil-bottle grade.",
  croscarmellose: "Methodology §5 Cleared (croscarmellose sodium).",
  ethylAcrylate: "Methodology §5 Limited-risk (ethyl acrylate copolymer — exact token; Caution; distinct from Caution methyl acrylate; locked Sept 23, 2026). Not Avoid.",
  ethylVanillin: "Methodology §5 Limited-risk (ethyl vanillin — exact token; Caution; flavor; not a named-color pass; locked Sept 23, 2026). Not Avoid.",
  ethylcellulose: "Methodology §5 Cleared (ethylcellulose — cellulose coating family; locked Sept 15, 2026).",
  flavors: "Methodology §5 Limited-risk (natural flavors / named simple flavors — undisclosed or named flavor mixtures).",
  gelatin: "Methodology §5 Cleared (gelatin / halal gelatin / gelatin capsule).",
  gellan: "Methodology §5 Cleared (gellan gum — xanthan / guar / pectin family).",
  glycerin: "Methodology §5 Cleared (glycerin / vegetable glycerin / organic vegetable glycerin).",
  gms: "Methodology §5 Cleared (glycerol monostearate / glyceryl monostearate — locked Sept 16, 2026).",
  hpmc: "Methodology §5 Cleared (hypromellose / HPMC / cellulose capsule).",
  ipa: "Methodology §5 Limited-risk (isopropyl alcohol — alcohol vehicle family; locked Sept 15, 2026). Not Avoid.",
  isomalt: "Methodology §5 Limited-risk (isomalt — oral sugar alcohol; locked Sept 15, 2026).",
  lecithin: "Methodology §5 Cleared (sunflower lecithin). Not an allergen flag.",
  leucine: "Methodology §5 Cleared (L-leucine / L-leucine powder).",
  maltodextrin: "Methodology §5 Limited-risk (maltodextrin, organic or not).",
  mcc: "Methodology §5 Cleared (microcrystalline cellulose / cellulose / capsule cellulose).",
  mctUnlabeled: "Methodology §5 Limited-risk (unlabeled MCT — organic MCT oil or medium chain triglycerides when the token does not name coconut or palm kernel). Not an oil-bottle grade. Not gummy High.",
  methacrylic: "Methodology §5 Limited-risk (methacrylic acid — exact token; Caution; distinct from Caution methacrylic acid copolymer; locked Sept 23, 2026). Not Avoid.",
  modStarch: "Methodology §5 Limited-risk (modified tapioca starch — Limited modified-starch row). Not Caution modified tapioca starchgel. Do not flip this Limited row.",
  monk: "Methodology §5 Cleared (monk fruit / monk fruit extract).",
  oatFiber: "Methodology §5 Cleared (oat fiber). Distinct from Caution organic oat fiber.",
  oleoresinTurmeric: "Methodology §5 Caution (oleoresin turmeric / turmeric oleoresin). Distinct from Cleared turmeric-as-color. Not Avoid.",
  oliveFill: "Methodology §5 Cleared (extra virgin olive oil as fill — locked Sept 22, 2026). Not an oil-bottle grade.",
  organicRiceBran: "Methodology §5 Limited-risk (organic rice bran — unspecified bran; Caution; distinct from Cleared organic rice bran extract and from Cleared rice bran oil as fill; locked Sept 23, 2026). Not Avoid.",
  peg: "Methodology §5 Moderate-risk (polyethylene glycol, oral).",
  pg: "Methodology §5 Moderate-risk (propylene glycol, oral).",
  polyol: "Methodology §5 Limited-risk (oral sugar alcohols — xylitol).",
  polysorbate: "Methodology §5 Moderate-risk (polysorbate unspecified — same family as polysorbate 80 / 20 / 60; locked Sept 15, 2026).",
  potassiumAcetate: "Methodology §5 Cleared (potassium acetate — exact token; locked Sept 23, 2026). Do not re-grade.",
  povidone: "Methodology §5 Cleared (crospovidone).",
  psyllium: "Methodology §5 Cleared (psyllium husk).",
  rebA: "Methodology §5 Cleared (rebaudioside A — high-purity steviol glycoside). Not Caution bare stevia extract. Not whole-leaf stevia.",
  riceBranOil: "Methodology §5 Cleared (rice bran oil as capsule / softgel fill — locked Sept 14, 2026). Not rice bran wax.",
  riceBranWax: "Methodology §5 Limited-risk (rice bran wax — exact token; Caution; distinct from Cleared carnauba wax, from Cleared organic rice bran extract, and from Cleared rice bran oil as fill; locked Sept 23, 2026). Not Avoid.",
  riceFlour: "Methodology §5 Caution (rice flour — exact token). Distinct from Cleared rice hull / rice bran.",
  riceHull: "Methodology §5 Cleared (rice hull concentrate / organic rice hull concentrate). Distinct from Caution rice flour.",
  rosemary: "Methodology §5 Caution (rosemary extract as an oral inactive preservative — locked Sept 16, 2026). Panel string rosemary liquid extract sits on this row. Not Avoid.",
  sls: "Methodology §5 Caution (sodium lauryl sulfate — population/irritant; standalone Caution, not additive-scored, not Avoid).",
  starch: "Methodology §5 Cleared (named corn starch / potato starch / tapioca starch). Not Limited modified starch. Not Caution unspecified starch.",
  starchgel: "Methodology §5 Limited-risk (modified tapioca starchgel / cassava root — maps to Caution cassava dextrin and Caution unspecified starch; locked Sept 23, 2026). Limited modified tapioca starch stays Limited. Not Avoid.",
  stearate: "Methodology §5 Cleared (magnesium stearate / stearic acid).",
  tocopherol: "Methodology §5 Cleared (ascorbyl palmitate as an antioxidant). Not tocopheryl acetate.",
  triethyl: "Methodology §5 Cleared (triethyl citrate — locked Sept 15, 2026; confirmed Sept 23, 2026). Do not re-add. Do not flip.",
  turmericColor: "Methodology §5 Cleared (turmeric [color] / turmeric as color). Distinct from Caution oleoresin turmeric.",
  water: "Methodology §5 Cleared (purified water).",
  wax: "Methodology §5 Cleared (yellow beeswax / beeswax).",
} as const;

function flag(
  name: string,
  riskLevel: IngredientFlag['riskLevel'],
  source: string,
): IngredientFlag {
  return { name, riskLevel, source };
}

function labelCite(label: string, meth: string): string {
  return `${label}; ${meth}`;
}

function alt(productId: string, rankReason: string): CleanAlternative {
  return { productId, rankReason };
}

function row(
  opts: Omit<RatingRecord, 'recordStatus'> & {
    recordStatus?: RatingRecord['recordStatus'];
  },
): RatingRecord {
  return { ...opts, recordStatus: opts.recordStatus ?? UNVERIFIED };
}

type Compact = {
  id: string;
  productName: string;
  category: string;
  barcode?: string;
  formulaId: string;
  audience: typeof ADULT;
  minAge: number;
  form: string;
  productType: typeof SUPPLEMENT;
  actives: RatingRecord['activeIngredients'];
  flags: [string, IngredientFlag['riskLevel'], keyof typeof METH][];
  verdict: RatingRecord['verdict'];
  note: string;
  cite: string;
};

function expand(d: Compact): RatingRecord {
  const alts: CleanAlternative[] = [];
  if (d.verdict !== 'clean') {
    const main = {
      Vitamins: ["amazon-elements-vitamin-d3-5000-softgels", "Independently Clean Amazon Elements Vitamin D3 5000 IU already on main. Form labeled, not a hard filter (§6)."],
      Digestive: ["megafood-magnesium-300-capsules", "Independently Clean MegaFood Magnesium 300 already on main. Form labeled, not a hard filter (§6)."],
      "Immune Support": ["natures-way-alive-max6", "Independently Clean Nature's Way Alive! Max6 already on main. Form labeled, not a hard filter (§6)."],
    } as const;
    const pair = main[d.category as keyof typeof main];
    if (pair) alts.push(alt(pair[0], pair[1]));
  }
  return row({
    id: d.id,
    productName: d.productName,
    brand: BRAND,
    category: d.category,
    barcode: d.barcode,
    formulaId: d.formulaId,
    audience: d.audience,
    minAge: d.minAge,
    form: d.form,
    productType: d.productType,
    activeIngredients: d.actives,
    inactiveIngredients: d.flags.map(([n, risk, meth]) =>
      flag(n, risk, labelCite(d.cite, METH[meth])),
    ),
    verdict: d.verdict,
    honestNote: `${d.note} ${LIMITED_STACK} Pack sizes share formulaId \`${d.formulaId}\` when this OI list holds. Adults unless the name says kids. No dosing or medical advice. Draft, not verified.`,
    retailers: [...AMAZON],
    cleanAlternatives: alts.length ? alts : undefined,
    sourcesGeneral: [`${d.cite} — ${UNVERIFIED_NOTE}; no DailyMed drug SPL`],
  });
}

const COMPACT: Compact[] = [
  {
    id: "naturewise-b83-selenium",
    productName: "NatureWise Selenium (250 Count)",
    barcode: "810157853288",
    category: "Vitamins",
    formulaId: "naturewise-b83-selenium",
    audience: ADULT,
    minAge: 18,
    form: "softgel",
    productType: SUPPLEMENT,
    actives: [{ name: "Selenium", strength: "250 Count" }],
    flags: [["Organic extra virgin coconut oil", "cleared", "coconut"], ["Modified tapioca starch", "limited", "modStarch"], ["Purified water", "cleared", "water"], ["Vegetable glycerin", "cleared", "glycerin"], ["Annatto (color)", "limited", "annatto"], ["Rice bran wax", "limited", "riceBranWax"], ["Sunflower lecithin", "cleared", "lecithin"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Modified tapioca starch; Annatto (color); Rice bran wax. Cleared capsule, softgel, and fill tokens do not raise Avoid. Modified tapioca starch on this softgel stays the Limited modified-starch row. It is not modified tapioca starchgel.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/selenium; image https://www.naturewise.com/cdn/shop/files/NW_-_Selenium_-_1b_-_Right_Side.jpg?width=1200) other-ingredients: Organic extra virgin coconut oil, softgel (modified tapioca starch, purified water, vegetable glycerin, annatto (color)), rice bran wax, sunflower lecithin. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157853288 is the GTIN-12 on this offer (250 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-magnesium-ashwagandha",
    productName: "NatureWise Magnesium with Ashwagandha (120 Count)",
    barcode: "810157852526",
    category: "Vitamins",
    formulaId: "naturewise-b83-magnesium-ashwagandha",
    audience: ADULT,
    minAge: 18,
    form: "tablet",
    productType: SUPPLEMENT,
    actives: [{ name: "Magnesium with Ashwagandha", strength: "120 Count" }],
    flags: [["Microcrystalline cellulose", "cleared", "mcc"], ["Stearic acid", "cleared", "stearate"], ["Croscarmellose sodium", "cleared", "croscarmellose"], ["Bamboo extract", "limited", "bamboo"], ["L-leucine", "cleared", "leucine"], ["Hypromellose", "cleared", "hpmc"], ["Vegetable glycerin", "cleared", "glycerin"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Bamboo extract. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/magnesium-ashwagandha; image https://www.naturewise.com/cdn/shop/files/NW-MagnesiumwithAshwagandha-5-Supplement.jpg?width=1200) other-ingredients: Microcrystalline cellulose, stearic acid, croscarmellose sodium, bamboo extract, L-leucine, coating (hypromellose, vegetable glycerin). Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157852526 is the GTIN-12 on this offer (120 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-ashwagandha-softgels",
    productName: "NatureWise Ashwagandha (60 Count)",
    barcode: "810157852472",
    category: "Vitamins",
    formulaId: "naturewise-b83-ashwagandha-softgels",
    audience: ADULT,
    minAge: 18,
    form: "softgel",
    productType: SUPPLEMENT,
    actives: [{ name: "Ashwagandha", strength: "60 Count" }],
    flags: [["Modified tapioca starch", "limited", "modStarch"], ["Organic vegetable glycerin", "cleared", "glycerin"], ["Purified water", "cleared", "water"], ["Sodium copper chlorophyllin", "limited", "chlorophyllin"], ["Organic MCT oil", "limited", "mctUnlabeled"], ["Rice bran wax", "limited", "riceBranWax"], ["Sunflower lecithin", "cleared", "lecithin"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Modified tapioca starch; Sodium copper chlorophyllin; Organic MCT oil; Rice bran wax. Cleared capsule, softgel, and fill tokens do not raise Avoid. Modified tapioca starch on this softgel stays the Limited modified-starch row. It is not modified tapioca starchgel. Organic MCT oil does not name coconut or palm kernel, so it stays Limited unlabeled MCT. Not an oil-bottle grade.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/ashwagandha; image https://www.naturewise.com/cdn/shop/files/NW-AshwagandhaSoftgels-5-Supplement.jpg?width=1200) other-ingredients: Softgel (modified tapioca starch, organic vegetable glycerin, purified water, sodium copper chlorophyllin [color]), organic mct oil, rice bran wax, sunflower lecithin. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157852472 is the GTIN-12 on this offer (60 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-algae-calcium",
    productName: "NatureWise Algae Calcium (120 Count)",
    barcode: "810157852229",
    category: "Vitamins",
    formulaId: "naturewise-b83-algae-calcium",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Algae Calcium", strength: "120 Count" }],
    flags: [["Hypromellose (cellulose) capsule", "cleared", "hpmc"], ["Bamboo extract", "limited", "bamboo"], ["Rice bran wax", "limited", "riceBranWax"], ["Rice flour", "limited", "riceFlour"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Bamboo extract; Rice bran wax; Rice flour. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/algae-calcium; image https://www.naturewise.com/cdn/shop/files/NW_-_Algae-Calcium_Plus_-_5_-_Supplement.jpg?width=1200) other-ingredients: Capsule (hypromellose), bamboo extract, rice bran wax, rice flour. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157852229 is the GTIN-12 on this offer (120 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-elderberry-plus",
    productName: "NatureWise Elderberry Plus (120 Count)",
    barcode: "810157852243",
    category: "Immune Support",
    formulaId: "naturewise-b83-elderberry-plus",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Elderberry Plus", strength: "120 Count" }],
    flags: [["Hypromellose (cellulose) capsule", "cleared", "hpmc"], ["Rice bran wax", "limited", "riceBranWax"], ["Stearic acid", "cleared", "stearate"], ["Bamboo extract", "limited", "bamboo"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Rice bran wax; Bamboo extract. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/elderberry-plus; image https://www.naturewise.com/cdn/shop/files/NW-Elderberry-5-Supplement.jpg?width=1200) other-ingredients: Capsule (hypromellose), rice bran wax, stearic acid, bamboo extract. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157852243 is the GTIN-12 on this offer (120 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-magnesium-citrate-complex",
    productName: "NatureWise Magnesium Citrate Complex (120 Count)",
    barcode: "810157852403",
    category: "Vitamins",
    formulaId: "naturewise-b83-magnesium-citrate-complex",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Magnesium Citrate Complex", strength: "120 Count" }],
    flags: [["Hypromellose (cellulose) capsule", "cleared", "hpmc"], ["Bamboo extract", "limited", "bamboo"], ["L-leucine", "cleared", "leucine"], ["Microcrystalline cellulose", "cleared", "mcc"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Bamboo extract. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/magnesium-citrate-complex; image https://www.naturewise.com/cdn/shop/files/NW_-_Magnesium_Citrate_Complex_-_5_-_Supplement.jpg?width=1200) other-ingredients: Capsule (hypromellose), bamboo extract, L-leucine, microcrystalline cellulose. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157852403 is the GTIN-12 on this offer (120 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-iron-bisglycinate",
    productName: "NatureWise Iron Bisglycinate (90 Count)",
    barcode: "810157852786",
    category: "Vitamins",
    formulaId: "naturewise-b83-magnesium-citrate-complex",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Iron Bisglycinate", strength: "90 Count" }],
    flags: [["Microcrystalline cellulose", "cleared", "mcc"], ["Hypromellose (cellulose) capsule", "cleared", "hpmc"], ["L-leucine", "cleared", "leucine"], ["Bamboo extract", "limited", "bamboo"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Bamboo extract. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/iron-bisglycinate-1; image https://www.naturewise.com/cdn/shop/files/NW-IronBisglycinate-5-Supplement.jpg?width=1200) other-ingredients: Microcrystalline cellulose, capsule (hypromellose), L-leucine, bamboo extract. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157852786 is the GTIN-12 on this offer (90 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-l-theanine-200",
    productName: "NatureWise L-Theanine (200 mg / 120 Count)",
    barcode: "810157851932",
    category: "Vitamins",
    formulaId: "naturewise-b83-algae-calcium",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "L-Theanine", strength: "200 mg / 120 Count" }],
    flags: [["Hypromellose (cellulose) capsule", "cleared", "hpmc"], ["Rice flour", "limited", "riceFlour"], ["Bamboo extract", "limited", "bamboo"], ["Rice bran wax", "limited", "riceBranWax"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Rice flour; Bamboo extract; Rice bran wax. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/l-theanine; image https://www.naturewise.com/cdn/shop/files/NW-L-Theanine-5-Supplement_85e871b4-cf11-4de0-a7e2-5ca90a056ae7.jpg?width=1200) other-ingredients: Capsule (hypromellose), rice flour, bamboo extract, rice bran wax. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157851932 is the GTIN-12 on this offer (200 mg / 120 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-l-theanine-400",
    productName: "NatureWise L-Theanine (400 mg / 120 Count)",
    barcode: "810157853080",
    category: "Vitamins",
    formulaId: "naturewise-b83-algae-calcium",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "L-Theanine", strength: "400 mg / 120 Count" }],
    flags: [["Hypromellose (cellulose) capsule", "cleared", "hpmc"], ["Rice flour", "limited", "riceFlour"], ["Bamboo extract", "limited", "bamboo"], ["Rice bran wax", "limited", "riceBranWax"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Rice flour; Bamboo extract; Rice bran wax. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/l-theanine; image https://www.naturewise.com/cdn/shop/files/NW-L-Theanine400mg-1b-RightSide.jpg?width=1200) other-ingredients: Capsule (hypromellose), rice flour, bamboo extract, rice bran wax. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157853080 is the GTIN-12 on this offer (400 mg / 120 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-super-k",
    productName: "NatureWise Super K Complex (90 Count)",
    barcode: "810157852366",
    category: "Vitamins",
    formulaId: "naturewise-b83-super-k",
    audience: ADULT,
    minAge: 18,
    form: "softgel",
    productType: SUPPLEMENT,
    actives: [{ name: "Super K Complex", strength: "90 Count" }],
    flags: [["Organic extra virgin olive oil", "cleared", "oliveFill"], ["Modified tapioca starch", "limited", "modStarch"], ["Vegetable glycerin", "cleared", "glycerin"], ["Purified water", "cleared", "water"], ["Turmeric (color)", "cleared", "turmericColor"], ["Rice bran wax", "limited", "riceBranWax"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Modified tapioca starch; Rice bran wax. Cleared capsule, softgel, and fill tokens do not raise Avoid. Modified tapioca starch on this softgel stays the Limited modified-starch row. It is not modified tapioca starchgel.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/super-k; image https://www.naturewise.com/cdn/shop/files/NW-SuperKComplex-5-Supplement.jpg?width=1200) other-ingredients: Organic extra virgin olive oil, softgel (modified tapioca starch, vegetable glycerin, purified water, turmeric [color]), rice bran wax. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157852366 is the GTIN-12 on this offer (90 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-fast-dissolve-vitamin-d3",
    productName: "NatureWise Fast Dissolve Vitamin D3 (90 Count / 5000 IU)",
    barcode: "810157852175",
    category: "Vitamins",
    formulaId: "naturewise-b83-fast-dissolve-vitamin-d3",
    audience: ADULT,
    minAge: 18,
    form: "tablet",
    productType: SUPPLEMENT,
    actives: [{ name: "Fast Dissolve Vitamin D3", strength: "90 Count / 5000 IU" }],
    flags: [["Xylitol", "limited", "polyol"], ["Crospovidone", "cleared", "povidone"], ["Mixed berry flavor", "limited", "flavors"], ["Corn starch", "cleared", "starch"], ["Bamboo extract", "limited", "bamboo"], ["Beet root (color)", "cleared", "beetColor"], ["Monk fruit extract", "cleared", "monk"], ["Citric acid", "cleared", "citric"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Xylitol; Mixed berry flavor; Bamboo extract. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/fast-dissolve-vitamin-d3; image https://www.naturewise.com/cdn/shop/files/NW-VitaminD3FastDissolve-5-Supplement.jpg?width=1200) other-ingredients: Xylitol, crospovidone, mixed berry flavor, corn starch, bamboo extract, beet root (color), monk fruit extract, citric acid. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157852175 is the GTIN-12 on this offer (90 Count / 5000 IU). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-krill-oil-d3",
    productName: "NatureWise Krill Oil + D3 (60 Count)",
    barcode: "810157852045",
    category: "Vitamins",
    formulaId: "naturewise-b83-krill-oil-d3",
    audience: ADULT,
    minAge: 18,
    form: "softgel",
    productType: SUPPLEMENT,
    actives: [{ name: "Krill Oil + D3", strength: "60 Count" }],
    flags: [["Gelatin", "cleared", "gelatin"], ["Vegetable glycerin", "cleared", "glycerin"], ["Ethyl vanillin", "limited", "ethylVanillin"], ["Purified water", "cleared", "water"], ["Corn oil", "cleared", "cornFill"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Ethyl vanillin. Cleared capsule, softgel, and fill tokens do not raise Avoid. Corn oil in this softgel is named-fill Cleared. Gummy print of corn oil stays Avoid. Same oil form split as soybean oil. Not an oil-bottle grade. Contains shellfish (krill).",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/krill-oil-d3; image https://www.naturewise.com/cdn/shop/files/NW-KrillOil1_000mg-5-Supplement.jpg?width=1200) other-ingredients: Softgel (gelatin, vegetable glycerin, ethyl vanillin, purified water), corn oil. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157852045 is the GTIN-12 on this offer (60 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-zinc-d3-k2",
    productName: "NatureWise Zinc + D3 & K2 (30 Count)",
    barcode: "810157851772",
    category: "Vitamins",
    formulaId: "naturewise-b83-zinc-d3-k2",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Zinc + D3 & K2", strength: "30 Count" }],
    flags: [["Microcrystalline cellulose", "cleared", "mcc"], ["Hypromellose (cellulose) capsule", "cleared", "hpmc"], ["Bamboo extract", "limited", "bamboo"], ["Rice hull concentrate", "cleared", "riceHull"], ["Maltodextrin", "limited", "maltodextrin"], ["Starch", "limited", "bareStarch"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Bamboo extract; Maltodextrin; Starch. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row. Bare starch is the Caution unspecified-starch row. Not Limited modified starch.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/zinc-d3-k2; image https://www.naturewise.com/cdn/shop/files/NW-ZincPicolinate-6-Supplement30.jpg?width=1200) other-ingredients: Microcrystalline cellulose, capsule (hypromellose), bamboo extract, rice hull concentrate, maltodextrin, starch. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157851772 is the GTIN-12 on this offer (30 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-zinc-d3-k2-60",
    productName: "NatureWise Zinc + D3 & K2 (60 Count)",
    barcode: "810157851789",
    category: "Vitamins",
    formulaId: "naturewise-b83-zinc-d3-k2",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Zinc + D3 & K2", strength: "60 Count" }],
    flags: [["Microcrystalline cellulose", "cleared", "mcc"], ["Hypromellose (cellulose) capsule", "cleared", "hpmc"], ["Bamboo extract", "limited", "bamboo"], ["Rice hull concentrate", "cleared", "riceHull"], ["Maltodextrin", "limited", "maltodextrin"], ["Starch", "limited", "bareStarch"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Bamboo extract; Maltodextrin; Starch. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row. Bare starch is the Caution unspecified-starch row. Not Limited modified starch.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/zinc-d3-k2; image https://www.naturewise.com/cdn/shop/files/NW-ZincPicolinate-6-Supplement60.jpg?width=1200) other-ingredients: Microcrystalline cellulose, capsule (hypromellose), bamboo extract, rice hull concentrate, maltodextrin, starch. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157851789 is the GTIN-12 on this offer (60 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-turmeric-saffron",
    productName: "NatureWise Turmeric Saffron + Cinnamon & Cardamom (60 Count)",
    barcode: "810157851697",
    category: "Vitamins",
    formulaId: "naturewise-b83-turmeric-saffron",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Turmeric Saffron + Cinnamon & Cardamom", strength: "60 Count" }],
    flags: [["Hypromellose (cellulose) capsule", "cleared", "hpmc"], ["Rice flour", "limited", "riceFlour"], ["Rice hull concentrate", "cleared", "riceHull"], ["Rice bran wax", "limited", "riceBranWax"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Rice flour; Rice bran wax. Cleared capsule, softgel, and fill tokens do not raise Avoid.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/turmeric-saffron; image https://www.naturewise.com/cdn/shop/files/NW-TurmericSaffron-5-Supplement.jpg?width=1200) other-ingredients: Capsule (hypromellose), rice flour, rice hull concentrate, rice bran wax. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157851697 is the GTIN-12 on this offer (60 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-turmeric-boswellia",
    productName: "NatureWise Turmeric Boswellia (60 Count)",
    barcode: "810157851581",
    category: "Vitamins",
    formulaId: "naturewise-b83-turmeric-boswellia",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Turmeric Boswellia", strength: "60 Count" }],
    flags: [["Vegetable capsule (hypromellose)", "cleared", "hpmc"], ["Rice bran wax", "limited", "riceBranWax"], ["Rice hull concentrate", "cleared", "riceHull"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Rice bran wax. Cleared capsule, softgel, and fill tokens do not raise Avoid.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/turmeric-boswellia; image https://www.naturewise.com/cdn/shop/files/NW-TurmericBoswellia-5-Supplement.jpg?width=1200) other-ingredients: Vegetable capsule (hypromellose), rice bran wax, rice hull concentrate. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157851581 is the GTIN-12 on this offer (60 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-vegan-biotin",
    productName: "NatureWise Vegan Biotin (120 Count)",
    barcode: "810157851918",
    category: "Vitamins",
    formulaId: "naturewise-b83-vegan-biotin",
    audience: ADULT,
    minAge: 18,
    form: "softgel",
    productType: SUPPLEMENT,
    actives: [{ name: "Vegan Biotin", strength: "120 Count" }],
    flags: [["Modified tapioca starch", "limited", "modStarch"], ["Vegetable glycerin", "cleared", "glycerin"], ["Purified water", "cleared", "water"], ["Organic extra virgin coconut oil", "cleared", "coconut"], ["Rice bran wax", "limited", "riceBranWax"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Modified tapioca starch; Rice bran wax. Cleared capsule, softgel, and fill tokens do not raise Avoid. Modified tapioca starch on this softgel stays the Limited modified-starch row. It is not modified tapioca starchgel. Contains tree nuts (coconut).",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/vegan-biotin; image https://www.naturewise.com/cdn/shop/files/NW-VeganBiotin-5-Supplement.jpg?width=1200) other-ingredients: Softgel (modified tapioca starch, vegetable glycerin, purified water), organic extra virgin coconut oil, rice bran wax. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157851918 is the GTIN-12 on this offer (120 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-l-methylfolate",
    productName: "NatureWise L-Methylfolate 5-MTHF + B12 (60 Count)",
    barcode: "810157851710",
    category: "Vitamins",
    formulaId: "naturewise-b83-l-methylfolate",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "L-Methylfolate 5-MTHF + B12", strength: "60 Count" }],
    flags: [["Rice hull concentrate", "cleared", "riceHull"], ["Hypromellose (cellulose) capsule", "cleared", "hpmc"], ["Rice bran wax", "limited", "riceBranWax"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Rice bran wax. Cleared capsule, softgel, and fill tokens do not raise Avoid.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/5-mthf-b12; image https://www.naturewise.com/cdn/shop/files/NW-L-Methylfolate-5-Supplement.jpg?width=1200) other-ingredients: Rice hull concentrate, capsule (hypromellose), rice bran wax. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157851710 is the GTIN-12 on this offer (60 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-mushroom-complex",
    productName: "NatureWise Mushroom Complex (90 Count)",
    barcode: "810157851468",
    category: "Vitamins",
    formulaId: "naturewise-b83-mushroom-complex",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Mushroom Complex", strength: "90 Count" }],
    flags: [["Hypromellose (cellulose) capsule", "cleared", "hpmc"], ["Bamboo extract", "limited", "bamboo"], ["Rice bran wax", "limited", "riceBranWax"], ["Ascorbyl palmitate", "cleared", "tocopherol"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Bamboo extract; Rice bran wax. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/mushroom-complex; image https://www.naturewise.com/cdn/shop/files/NW-MushroomComplex-6-Supplement.jpg?width=1200) other-ingredients: Capsule (hypromellose), bamboo extract, rice bran wax, ascorbyl palmitate. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157851468 is the GTIN-12 on this offer (90 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-biotin-5000",
    productName: "NatureWise Biotin (5000 mcg / 150 Count)",
    barcode: "810157851673",
    category: "Vitamins",
    formulaId: "naturewise-b83-biotin-5000",
    audience: ADULT,
    minAge: 18,
    form: "softgel",
    productType: SUPPLEMENT,
    actives: [{ name: "Biotin", strength: "5000 mcg / 150 Count" }],
    flags: [["Organic extra virgin coconut oil", "cleared", "coconut"], ["Halal gelatin", "cleared", "gelatin"], ["Glycerin", "cleared", "glycerin"], ["Purified water", "cleared", "water"], ["Annatto", "limited", "annatto"], ["Sunflower lecithin", "cleared", "lecithin"], ["Yellow beeswax", "cleared", "wax"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Annatto. Cleared capsule, softgel, and fill tokens do not raise Avoid. Contains tree nuts (coconut). This count does not print rice bran wax.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/biotin; image https://www.naturewise.com/cdn/shop/files/NW-Biotin5_000mcg-5-Supplement.jpg?width=1200) other-ingredients: Organic extra virgin coconut oil, softgel (halal gelatin, glycerin, purified water, annatto), sunflower lecithin, yellow beeswax. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157851673 is the GTIN-12 on this offer (5000 mcg / 150 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-biotin-10000",
    productName: "NatureWise Biotin (10000 mcg / 120 Count)",
    barcode: "810157851727",
    category: "Vitamins",
    formulaId: "naturewise-b83-biotin-10000",
    audience: ADULT,
    minAge: 18,
    form: "softgel",
    productType: SUPPLEMENT,
    actives: [{ name: "Biotin", strength: "10000 mcg / 120 Count" }],
    flags: [["Organic extra virgin coconut oil", "cleared", "coconut"], ["Halal gelatin", "cleared", "gelatin"], ["Glycerin", "cleared", "glycerin"], ["Purified water", "cleared", "water"], ["Rice bran wax", "limited", "riceBranWax"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Rice bran wax. Cleared capsule, softgel, and fill tokens do not raise Avoid. Contains tree nuts (coconut).",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/biotin; image https://www.naturewise.com/cdn/shop/files/NW-Biotin10_000mcg-5-Supplement.jpg?width=1200) other-ingredients: Organic extra virgin coconut oil, softgel (halal gelatin, glycerin, purified water), rice bran wax. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157851727 is the GTIN-12 on this offer (10000 mcg / 120 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-nad-complex",
    productName: "NatureWise NAD+ Support Complex (60 Count)",
    barcode: "810157851420",
    category: "Vitamins",
    formulaId: "naturewise-b83-nad-complex",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "NAD+ Support Complex", strength: "60 Count" }],
    flags: [["Veggie capsule (hypromellose)", "cleared", "hpmc"], ["Rice flour", "limited", "riceFlour"], ["Microcrystalline cellulose", "cleared", "mcc"], ["Bamboo extract", "limited", "bamboo"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Rice flour; Bamboo extract. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/nad-complex; image https://www.naturewise.com/cdn/shop/files/NW-NAD_-6-Supplement_7a9749eb-c6e7-4e7a-b9f5-39dd92aea782.jpg?width=1200) other-ingredients: Veggie capsule (hypromellose), rice flour, microcrystalline cellulose, bamboo extract. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157851420 is the GTIN-12 on this offer (60 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-berberine",
    productName: "NatureWise Berberine (60 Count)",
    barcode: "810157851444",
    category: "Vitamins",
    formulaId: "naturewise-b83-berberine",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Berberine", strength: "60 Count" }],
    flags: [["Hypromellose (cellulose) capsule", "cleared", "hpmc"], ["Microcrystalline cellulose", "cleared", "mcc"], ["Bamboo extract", "limited", "bamboo"], ["Rice bran wax", "limited", "riceBranWax"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Bamboo extract; Rice bran wax. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/berberine; image https://www.naturewise.com/cdn/shop/files/NW-BerberineComplex-6-Supplement.jpg?width=1200) other-ingredients: Capsule (hypromellose), microcrystalline cellulose, bamboo extract, rice bran wax. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157851444 is the GTIN-12 on this offer (60 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-hydro-soluble-turmeric-1000",
    productName: "NatureWise Hydro-Soluble Turmeric Curcumin (1000 mg / 60 Count)",
    barcode: "810157850935",
    category: "Vitamins",
    formulaId: "naturewise-b83-hydro-soluble-turmeric-1000",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Hydro-Soluble Turmeric Curcumin", strength: "1000 mg / 60 Count" }],
    flags: [["Hypromellose (cellulose) capsule", "cleared", "hpmc"], ["Rice flour", "limited", "riceFlour"], ["Organic rice hull concentrate", "cleared", "riceHull"], ["Bamboo extract", "limited", "bamboo"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Rice flour; Bamboo extract. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/hydro-soluble-turmeric-curcumin; image https://www.naturewise.com/cdn/shop/files/NW-TurmericCurcumin1000mg-7-Supplement.jpg?width=1200) other-ingredients: Capsule (hypromellose), rice flour, organic rice hull concentrate, bamboo extract. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157850935 is the GTIN-12 on this offer (1000 mg / 60 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-hydro-soluble-turmeric-1500",
    productName: "NatureWise Hydro-Soluble Turmeric Curcumin (1500 mg / 90 Count)",
    barcode: "810157852168",
    category: "Vitamins",
    formulaId: "naturewise-b83-hydro-soluble-turmeric-1000",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Hydro-Soluble Turmeric Curcumin", strength: "1500 mg / 90 Count" }],
    flags: [["Hypromellose (cellulose) capsule", "cleared", "hpmc"], ["Rice flour", "limited", "riceFlour"], ["Organic rice hull concentrate", "cleared", "riceHull"], ["Bamboo extract", "limited", "bamboo"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Rice flour; Bamboo extract. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/hydro-soluble-turmeric-curcumin; image https://www.naturewise.com/cdn/shop/files/NW-TurmericCurcumin1_500mg-1b-RightSide.jpg?width=1200) other-ingredients: Capsule (hypromellose), rice flour, organic rice hull concentrate, bamboo extract. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157852168 is the GTIN-12 on this offer (1500 mg / 90 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-vitamin-d3-k2-mct-5000-30",
    productName: "NatureWise Vitamin D3 + K2 with MCT Oil (5000 IU / 30 Count)",
    barcode: "810157851123",
    category: "Vitamins",
    formulaId: "naturewise-b83-vitamin-d3-k2-mct-5000-30",
    audience: ADULT,
    minAge: 18,
    form: "softgel",
    productType: SUPPLEMENT,
    actives: [{ name: "Vitamin D3 + K2 with MCT Oil", strength: "5000 IU / 30 Count" }],
    flags: [["Organic MCT oil", "limited", "mctUnlabeled"], ["Modified tapioca starchgel", "limited", "starchgel"], ["Vegetable glycerin", "cleared", "glycerin"], ["Purified water", "cleared", "water"], ["Turmeric (color)", "cleared", "turmericColor"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Organic MCT oil; Modified tapioca starchgel. Cleared capsule, softgel, and fill tokens do not raise Avoid. Modified tapioca starchgel maps to Caution cassava dextrin / unspecified starch. Limited modified tapioca starch stays Limited and is not this string. Organic MCT oil does not name coconut or palm kernel, so it stays Limited unlabeled MCT. Not an oil-bottle grade. Not gummy High. Contains line names tree nuts (coconut).",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/vitamin-d3-k2-with-mct-oil; image https://www.naturewise.com/cdn/shop/files/NW-VitaminD35_000IU_K2MCT-6-Supplement30.jpg?width=1200) other-ingredients: Organic MCT oil, modified tapioca starchgel, vegetable glycerin, purified water, turmeric [color]. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157851123 is the GTIN-12 on this offer (5000 IU / 30 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-vitamin-d3-k2-mct-5000-90",
    productName: "NatureWise Vitamin D3 + K2 with MCT Oil (5000 IU / 90 Count)",
    barcode: "810157851130",
    category: "Vitamins",
    formulaId: "naturewise-b83-vitamin-d3-k2-mct-5000-30",
    audience: ADULT,
    minAge: 18,
    form: "softgel",
    productType: SUPPLEMENT,
    actives: [{ name: "Vitamin D3 + K2 with MCT Oil", strength: "5000 IU / 90 Count" }],
    flags: [["Organic MCT oil", "limited", "mctUnlabeled"], ["Modified tapioca starchgel", "limited", "starchgel"], ["Vegetable glycerin", "cleared", "glycerin"], ["Purified water", "cleared", "water"], ["Turmeric (color)", "cleared", "turmericColor"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Organic MCT oil; Modified tapioca starchgel. Cleared capsule, softgel, and fill tokens do not raise Avoid. Modified tapioca starchgel maps to Caution cassava dextrin / unspecified starch. Limited modified tapioca starch stays Limited and is not this string. Organic MCT oil does not name coconut or palm kernel, so it stays Limited unlabeled MCT. Not an oil-bottle grade. Not gummy High. Contains line names tree nuts (coconut).",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/vitamin-d3-k2-with-mct-oil; image https://www.naturewise.com/cdn/shop/files/NW-VitaminD35_000IU_K2MCT-6-Supplement30.jpg?width=1200) other-ingredients: Organic MCT oil, modified tapioca starchgel, vegetable glycerin, purified water, turmeric [color]. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157851130 is the GTIN-12 on this offer (5000 IU / 90 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-vitamin-d3-k2-mct-10000-30",
    productName: "NatureWise Vitamin D3 + K2 with MCT Oil (10000 IU / 30 Count)",
    barcode: "810157851161",
    category: "Vitamins",
    formulaId: "naturewise-b83-vitamin-d3-k2-mct-5000-30",
    audience: ADULT,
    minAge: 18,
    form: "softgel",
    productType: SUPPLEMENT,
    actives: [{ name: "Vitamin D3 + K2 with MCT Oil", strength: "10000 IU / 30 Count" }],
    flags: [["Organic MCT oil", "limited", "mctUnlabeled"], ["Modified tapioca starchgel", "limited", "starchgel"], ["Vegetable glycerin", "cleared", "glycerin"], ["Purified water", "cleared", "water"], ["Turmeric (color)", "cleared", "turmericColor"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Organic MCT oil; Modified tapioca starchgel. Cleared capsule, softgel, and fill tokens do not raise Avoid. Modified tapioca starchgel maps to Caution cassava dextrin / unspecified starch. Limited modified tapioca starch stays Limited and is not this string. Organic MCT oil does not name coconut or palm kernel, so it stays Limited unlabeled MCT. Not an oil-bottle grade. Not gummy High. Contains line names tree nuts (coconut).",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/vitamin-d3-k2-with-mct-oil; image https://www.naturewise.com/cdn/shop/files/NW-VitaminD35_000IU_K2MCT-6-Supplement30.jpg?width=1200) other-ingredients: Organic MCT oil, modified tapioca starchgel, vegetable glycerin, purified water, turmeric [color]. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157851161 is the GTIN-12 on this offer (10000 IU / 30 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-vitamin-d3-k2-mct-10000-90",
    productName: "NatureWise Vitamin D3 + K2 with MCT Oil (10000 IU / 90 Count)",
    barcode: "810157851178",
    category: "Vitamins",
    formulaId: "naturewise-b83-vitamin-d3-k2-mct-5000-30",
    audience: ADULT,
    minAge: 18,
    form: "softgel",
    productType: SUPPLEMENT,
    actives: [{ name: "Vitamin D3 + K2 with MCT Oil", strength: "10000 IU / 90 Count" }],
    flags: [["Organic MCT oil", "limited", "mctUnlabeled"], ["Modified tapioca starchgel", "limited", "starchgel"], ["Vegetable glycerin", "cleared", "glycerin"], ["Purified water", "cleared", "water"], ["Turmeric (color)", "cleared", "turmericColor"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Organic MCT oil; Modified tapioca starchgel. Cleared capsule, softgel, and fill tokens do not raise Avoid. Modified tapioca starchgel maps to Caution cassava dextrin / unspecified starch. Limited modified tapioca starch stays Limited and is not this string. Organic MCT oil does not name coconut or palm kernel, so it stays Limited unlabeled MCT. Not an oil-bottle grade. Not gummy High. Contains line names tree nuts (coconut).",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/vitamin-d3-k2-with-mct-oil; image https://www.naturewise.com/cdn/shop/files/NW-VitaminD35_000IU_K2MCT-6-Supplement30.jpg?width=1200) other-ingredients: Organic MCT oil, modified tapioca starchgel, vegetable glycerin, purified water, turmeric [color]. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157851178 is the GTIN-12 on this offer (10000 IU / 90 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-creatine-pills",
    productName: "NatureWise Creatine Monohydrate Pills (60 Count)",
    barcode: "810157851376",
    category: "Vitamins",
    formulaId: "naturewise-b83-creatine-pills",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Creatine Monohydrate Pills", strength: "60 Count" }],
    flags: [["Gelatin capsule", "cleared", "gelatin"], ["Microcrystalline cellulose", "cleared", "mcc"], ["Rice bran wax", "limited", "riceBranWax"], ["Bamboo extract", "limited", "bamboo"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Rice bran wax; Bamboo extract. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row. Label says not intended for people under 18.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/creatine-pills; image https://www.naturewise.com/cdn/shop/files/NW-CreatineCapsules-6-Supplement.jpg?width=1200) other-ingredients: Gelatin capsule, microcrystalline cellulose, rice bran wax, bamboo extract. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157851376 is the GTIN-12 on this offer (60 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-iron-bisglycinate-plus",
    productName: "NatureWise Iron Bisglycinate Plus (30 Count)",
    barcode: "810157851055",
    category: "Vitamins",
    formulaId: "naturewise-b83-iron-bisglycinate-plus",
    audience: ADULT,
    minAge: 18,
    form: "tablet",
    productType: SUPPLEMENT,
    actives: [{ name: "Iron Bisglycinate Plus", strength: "30 Count" }],
    flags: [["Microcrystalline cellulose", "cleared", "mcc"], ["Organic rice bran", "limited", "organicRiceBran"], ["Ethylcellulose", "cleared", "ethylcellulose"], ["Isopropyl alcohol", "limited", "ipa"], ["Hypromellose", "cleared", "hpmc"], ["Polyethylene glycol", "moderate", "peg"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Organic rice bran; Isopropyl alcohol; Polyethylene glycol. Cleared capsule, softgel, and fill tokens do not raise Avoid. Organic rice bran is the unspecified-bran Caution row. Not Cleared organic rice bran extract.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/iron-bisglycinate; image https://www.naturewise.com/cdn/shop/files/NW-Iron-5-Supplement30.jpg?width=1200) other-ingredients: Microcrystalline cellulose, organic rice bran, coating (ethylcellulose, isopropyl alcohol, hypromellose, polyethylene glycol). Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157851055 is the GTIN-12 on this offer (30 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-iron-bisglycinate-plus-90",
    productName: "NatureWise Iron Bisglycinate Plus (90 Count)",
    barcode: "810157851062",
    category: "Vitamins",
    formulaId: "naturewise-b83-iron-bisglycinate-plus",
    audience: ADULT,
    minAge: 18,
    form: "tablet",
    productType: SUPPLEMENT,
    actives: [{ name: "Iron Bisglycinate Plus", strength: "90 Count" }],
    flags: [["Microcrystalline cellulose", "cleared", "mcc"], ["Organic rice bran", "limited", "organicRiceBran"], ["Ethylcellulose", "cleared", "ethylcellulose"], ["Isopropyl alcohol", "limited", "ipa"], ["Hypromellose", "cleared", "hpmc"], ["Polyethylene glycol", "moderate", "peg"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Organic rice bran; Isopropyl alcohol; Polyethylene glycol. Cleared capsule, softgel, and fill tokens do not raise Avoid. Organic rice bran is the unspecified-bran Caution row. Not Cleared organic rice bran extract. Same panel image as the 30 Count.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/iron-bisglycinate; image https://www.naturewise.com/cdn/shop/files/NW-Iron-5-Supplement30.jpg?width=1200) other-ingredients: Microcrystalline cellulose, organic rice bran, coating (ethylcellulose, isopropyl alcohol, hypromellose, polyethylene glycol). Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157851062 is the GTIN-12 on this offer (90 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-magnesium-glycinate-400-90",
    productName: "NatureWise Magnesium Glycinate (400 mg / 90 Count)",
    barcode: "810157852458",
    category: "Vitamins",
    formulaId: "naturewise-b83-magnesium-glycinate-400-90",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Magnesium Glycinate", strength: "400 mg / 90 Count" }],
    flags: [["Rice flour", "limited", "riceFlour"], ["Hypromellose (cellulose) capsule", "cleared", "hpmc"], ["Bamboo extract", "limited", "bamboo"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Rice flour; Bamboo extract. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/magnesium-glycinate; image https://www.naturewise.com/cdn/shop/files/NW-MagnesiumGlycinate400mg-1b-RightSide.jpg?width=1200) other-ingredients: Rice flour, capsule (hypromellose), bamboo extract. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157852458 is the GTIN-12 on this offer (400 mg / 90 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-magnesium-glycinate-400-180",
    productName: "NatureWise Magnesium Glycinate (400 mg / 180 Count)",
    barcode: "810157852465",
    category: "Vitamins",
    formulaId: "naturewise-b83-magnesium-glycinate-400-90",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Magnesium Glycinate", strength: "400 mg / 180 Count" }],
    flags: [["Rice flour", "limited", "riceFlour"], ["Hypromellose (cellulose) capsule", "cleared", "hpmc"], ["Bamboo extract", "limited", "bamboo"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Rice flour; Bamboo extract. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/magnesium-glycinate; image https://www.naturewise.com/cdn/shop/files/NW-MagnesiumGlycinate400mg-1a-RightSide180.jpg?width=1200) other-ingredients: Rice flour, capsule (hypromellose), bamboo extract. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157852465 is the GTIN-12 on this offer (400 mg / 180 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-allicin-garlic",
    productName: "NatureWise Allicin Garlic + (60 Count)",
    barcode: "810157850836",
    category: "Vitamins",
    formulaId: "naturewise-b83-allicin-garlic",
    audience: ADULT,
    minAge: 18,
    form: "tablet",
    productType: SUPPLEMENT,
    actives: [{ name: "Allicin Garlic +", strength: "60 Count" }],
    flags: [["Calcium carbonate", "cleared", "caCarb"], ["Microcrystalline cellulose", "cleared", "mcc"], ["Croscarmellose sodium", "cleared", "croscarmellose"], ["Bamboo extract", "limited", "bamboo"], ["Rice bran wax", "limited", "riceBranWax"], ["Methacrylic acid", "limited", "methacrylic"], ["Ethyl acrylate copolymer", "limited", "ethylAcrylate"], ["Polysorbate", "moderate", "polysorbate"], ["Sodium lauryl sulfate", "limited", "sls"], ["Glycerol monostearate", "cleared", "gms"], ["Triethyl citrate", "cleared", "triethyl"], ["Propylene glycol", "moderate", "pg"], ["Isomalt", "limited", "isomalt"], ["Hypromellose", "cleared", "hpmc"], ["Medium chain triglycerides", "limited", "mctUnlabeled"], ["French vanilla flavor", "limited", "flavors"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Bamboo extract; Rice bran wax; Methacrylic acid; Ethyl acrylate copolymer; Polysorbate; Sodium lauryl sulfate; Propylene glycol; Isomalt; Medium chain triglycerides; French vanilla flavor. Cleared capsule, softgel, and fill tokens do not raise Avoid. Sodium lauryl sulfate is standalone Caution and is not an Avoid driver. Medium chain triglycerides do not name a plant source, so they stay Limited unlabeled MCT. Triethyl citrate stays the locked Cleared row.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/allicin-garlic-plus; image https://www.naturewise.com/cdn/shop/files/NW-Garlic5500mcg-Right.jpg?width=1200) other-ingredients: Calcium carbonate, microcrystalline cellulose, croscarmellose sodium, bamboo extract, rice bran wax, and coating (methacrylic acid, ethyl acrylate copolymer, polysorbate, sodium lauryl sulfate, glycerol monostearate, triethyl citrate, propylene glycol, isomalt, hypromellose, medium chain triglycerides, french vanilla flavor). Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157850836 is the GTIN-12 on this offer (60 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-super-b-complex",
    productName: "NatureWise Super B Complex + Vitamin C (60 Count)",
    barcode: "810157851154",
    category: "Vitamins",
    formulaId: "naturewise-b83-super-b-complex",
    audience: ADULT,
    minAge: 18,
    form: "tablet",
    productType: SUPPLEMENT,
    actives: [{ name: "Super B Complex + Vitamin C", strength: "60 Count" }],
    flags: [["Microcrystalline cellulose", "cleared", "mcc"], ["Croscarmellose sodium", "cleared", "croscarmellose"], ["Bamboo extract", "limited", "bamboo"], ["Rice bran wax", "limited", "riceBranWax"], ["Hypromellose", "cleared", "hpmc"], ["Vegetable glycerin", "cleared", "glycerin"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Bamboo extract; Rice bran wax. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/super-b-complex; image https://www.naturewise.com/cdn/shop/files/SuperB-Complex-4-Supplement.jpg?width=1200) other-ingredients: Microcrystalline cellulose, croscarmellose sodium, bamboo extract, rice bran wax, and coating (hypromellose, glycerin). Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157851154 is the GTIN-12 on this offer (60 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-milk-thistle",
    productName: "NatureWise Milk Thistle (60 Count)",
    barcode: "810157850850",
    category: "Vitamins",
    formulaId: "naturewise-b83-berberine",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Milk Thistle", strength: "60 Count" }],
    flags: [["Microcrystalline cellulose", "cleared", "mcc"], ["Hypromellose (cellulose) capsule", "cleared", "hpmc"], ["Bamboo extract", "limited", "bamboo"], ["Rice bran wax", "limited", "riceBranWax"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Bamboo extract; Rice bran wax. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/milk-thistle; image https://www.naturewise.com/cdn/shop/files/NW-MilkThistle-4-Supplement60.jpg?width=1200) other-ingredients: Microcrystalline cellulose, capsule (hypromellose), bamboo extract, rice bran wax. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157850850 is the GTIN-12 on this offer (60 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-milk-thistle-180",
    productName: "NatureWise Milk Thistle (180 Count)",
    barcode: "810157851086",
    category: "Vitamins",
    formulaId: "naturewise-b83-berberine",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Milk Thistle", strength: "180 Count" }],
    flags: [["Microcrystalline cellulose", "cleared", "mcc"], ["Hypromellose (cellulose) capsule", "cleared", "hpmc"], ["Bamboo extract", "limited", "bamboo"], ["Rice bran wax", "limited", "riceBranWax"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Bamboo extract; Rice bran wax. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row. Same panel image as the 60 Count.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/milk-thistle; image https://www.naturewise.com/cdn/shop/files/NW-MilkThistle-4-Supplement60.jpg?width=1200) other-ingredients: Microcrystalline cellulose, capsule (hypromellose), bamboo extract, rice bran wax. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157851086 is the GTIN-12 on this offer (180 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-multi-collagen",
    productName: "NatureWise Multi Collagen Complex (90 Count)",
    barcode: "810157850904",
    category: "Vitamins",
    formulaId: "naturewise-b83-multi-collagen",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Multi Collagen Complex", strength: "90 Count" }],
    flags: [["Gelatin capsule", "cleared", "gelatin"], ["Rice flour", "limited", "riceFlour"], ["Organic rice hull concentrate", "cleared", "riceHull"], ["Bamboo extract", "limited", "bamboo"], ["L-leucine", "cleared", "leucine"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Rice flour; Bamboo extract. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row. Contains egg and fish (tilapia).",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/multi-collagen-complex; image https://www.naturewise.com/cdn/shop/files/NW-MultiCollagenCapsules_PDP_60CT_RIGHT.jpg?width=1200) other-ingredients: Gelatin capsule, rice flour, organic rice hull concentrate, bamboo extract, L-leucine. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157850904 is the GTIN-12 on this offer (90 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-beet-root",
    productName: "NatureWise Beet Root (120 Count)",
    barcode: "810157850270",
    category: "Vitamins",
    formulaId: "naturewise-b83-beet-root",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Beet Root", strength: "120 Count" }],
    flags: [["Hypromellose (cellulose) capsule", "cleared", "hpmc"], ["Oat fiber", "cleared", "oatFiber"], ["Potato starch", "cleared", "starch"], ["Psyllium husk", "cleared", "psyllium"], ["Rice bran wax", "limited", "riceBranWax"], ["Bamboo extract", "limited", "bamboo"], ["Rice flour", "limited", "riceFlour"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Rice bran wax; Bamboo extract; Rice flour. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row. Oat fiber on this panel is the Cleared oat-fiber row, not Caution organic oat fiber.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/beet-root; image https://www.naturewise.com/cdn/shop/files/NW_-_Beet_Root_Extract_-_5_-_Supplement_120.jpg?width=1200) other-ingredients: Capsule (hypromellose), oat fiber, potato starch, psyllium husk, rice bran wax, bamboo extract, rice flour. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157850270 is the GTIN-12 on this offer (120 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-cranberry-pills",
    productName: "NatureWise Cranberry Pills (60 Count)",
    barcode: "850053810954",
    category: "Vitamins",
    formulaId: "naturewise-b83-cranberry-pills",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Cranberry Pills", strength: "60 Count" }],
    flags: [["Rice flour", "limited", "riceFlour"], ["Calcium carbonate", "cleared", "caCarb"], ["Cellulose", "cleared", "mcc"], ["Rice bran wax", "limited", "riceBranWax"], ["Oat fiber", "cleared", "oatFiber"], ["Potato starch", "cleared", "starch"], ["Psyllium husk", "cleared", "psyllium"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Rice flour; Rice bran wax. Cleared capsule, softgel, and fill tokens do not raise Avoid. Oat fiber on this panel is the Cleared oat-fiber row, not Caution organic oat fiber.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/cranberry-pills; image https://www.naturewise.com/cdn/shop/files/NW-CranberryExtract-5-Supplement60.jpg?width=1200) other-ingredients: Rice flour, capsule (calcium carbonate, cellulose), rice bran wax, oat fiber, potato starch, psyllium husk. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 850053810954 is the GTIN-12 on this offer (60 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-green-tea-60",
    productName: "NatureWise Green Tea Extract (60 Count)",
    barcode: "850053810886",
    category: "Vitamins",
    formulaId: "naturewise-b83-algae-calcium",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Green Tea Extract", strength: "60 Count" }],
    flags: [["Hypromellose", "cleared", "hpmc"], ["Rice flour", "limited", "riceFlour"], ["Rice bran wax", "limited", "riceBranWax"], ["Bamboo extract", "limited", "bamboo"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Rice flour; Rice bran wax; Bamboo extract. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/green-tea-extract; image https://www.naturewise.com/cdn/shop/files/NW_-_Green_Tea_Extract_-_4_-_Supplement_60_NSF_GF.jpg?width=1200) other-ingredients: Hypromellose, rice flour, rice bran wax, bamboo extract. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 850053810886 is the GTIN-12 on this offer (60 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-green-tea-90",
    productName: "NatureWise Green Tea Extract (90 Count)",
    barcode: "850053810893",
    category: "Vitamins",
    formulaId: "naturewise-b83-algae-calcium",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Green Tea Extract", strength: "90 Count" }],
    flags: [["Hypromellose", "cleared", "hpmc"], ["Rice flour", "limited", "riceFlour"], ["Rice bran wax", "limited", "riceBranWax"], ["Bamboo extract", "limited", "bamboo"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Rice flour; Rice bran wax; Bamboo extract. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row. Same panel image as the 60 Count.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/green-tea-extract; image https://www.naturewise.com/cdn/shop/files/NW_-_Green_Tea_Extract_-_4_-_Supplement_60_NSF_GF.jpg?width=1200) other-ingredients: Hypromellose, rice flour, rice bran wax, bamboo extract. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 850053810893 is the GTIN-12 on this offer (90 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-green-tea-120",
    productName: "NatureWise Green Tea Extract (120 Count)",
    barcode: "850053810909",
    category: "Vitamins",
    formulaId: "naturewise-b83-algae-calcium",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Green Tea Extract", strength: "120 Count" }],
    flags: [["Hypromellose", "cleared", "hpmc"], ["Rice flour", "limited", "riceFlour"], ["Rice bran wax", "limited", "riceBranWax"], ["Bamboo extract", "limited", "bamboo"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Rice flour; Rice bran wax; Bamboo extract. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row. Same panel image as the 60 Count.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/green-tea-extract; image https://www.naturewise.com/cdn/shop/files/NW_-_Green_Tea_Extract_-_4_-_Supplement_60_NSF_GF.jpg?width=1200) other-ingredients: Hypromellose, rice flour, rice bran wax, bamboo extract. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 850053810909 is the GTIN-12 on this offer (120 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-probiotics-for-women",
    productName: "NatureWise Probiotics for Women (60 Count)",
    barcode: "858081006301",
    category: "Digestive",
    formulaId: "naturewise-b83-probiotics-for-women",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Probiotics for Women", strength: "60 Count" }],
    flags: [["Microcrystalline cellulose", "cleared", "mcc"], ["Gellan gum", "cleared", "gellan"], ["Hypromellose (cellulose) capsule", "cleared", "hpmc"], ["Bamboo extract", "limited", "bamboo"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Bamboo extract. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/womens-care-probiotics; image https://www.naturewise.com/cdn/shop/files/NW-ProbioticsforWomen-RIGHT.jpg?width=1200) other-ingredients: Microcrystalline cellulose, DRcaps capsule (gellan gum, hypromellose), bamboo extract. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 858081006301 is the GTIN-12 on this offer (60 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-raspberry-ketones",
    productName: "NatureWise Raspberry Ketones Plus+ (120 Count)",
    barcode: "858081006172",
    category: "Vitamins",
    formulaId: "naturewise-b83-raspberry-ketones",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Raspberry Ketones Plus+", strength: "120 Count" }],
    flags: [["Hypromellose (cellulose) capsule", "cleared", "hpmc"], ["Purified water", "cleared", "water"], ["Carrageenan", "limited", "carrageenan"], ["Potassium acetate", "cleared", "potassiumAcetate"], ["Rice hull concentrate", "cleared", "riceHull"], ["Rice flour", "limited", "riceFlour"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Carrageenan; Rice flour. Cleared capsule, softgel, and fill tokens do not raise Avoid. The capsule parenthetical names hypromellose, water, carrageenan, and potassium acetate. Potassium acetate stays the locked Cleared row.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/raspberry-ketones-plus; image https://www.naturewise.com/cdn/shop/files/NW-RaspberryKetones-5-Supplement.jpg?width=1200) other-ingredients: Vegetable capsule (hypromellose, purified water, carrageenan, potassium acetate), rice hull concentrate, rice flour. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 858081006172 is the GTIN-12 on this offer (120 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-liver-balance",
    productName: "NatureWise Liver Balance Complete (60 Count)",
    barcode: "855724007404",
    category: "Vitamins",
    formulaId: "naturewise-b83-liver-balance",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Liver Balance Complete", strength: "60 Count" }],
    flags: [["Cellulose capsule", "cleared", "mcc"], ["Bamboo extract", "limited", "bamboo"], ["Ascorbyl palmitate", "cleared", "tocopherol"], ["Rice flour", "limited", "riceFlour"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Bamboo extract; Rice flour. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/liver-balance-complete; image https://www.naturewise.com/cdn/shop/files/NW-LiverBalance-5-Supplement60.jpg?width=1200) other-ingredients: Cellulose capsule, bamboo extract, ascorbyl palmitate, rice flour. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 855724007404 is the GTIN-12 on this offer (60 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-liver-balance-120",
    productName: "NatureWise Liver Balance Complete (120 Count)",
    barcode: "858081006813",
    category: "Vitamins",
    formulaId: "naturewise-b83-liver-balance",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Liver Balance Complete", strength: "120 Count" }],
    flags: [["Cellulose capsule", "cleared", "mcc"], ["Bamboo extract", "limited", "bamboo"], ["Ascorbyl palmitate", "cleared", "tocopherol"], ["Rice flour", "limited", "riceFlour"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Bamboo extract; Rice flour. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row. Same panel image as the 60 Count.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/liver-balance-complete; image https://www.naturewise.com/cdn/shop/files/NW-LiverBalance-5-Supplement60.jpg?width=1200) other-ingredients: Cellulose capsule, bamboo extract, ascorbyl palmitate, rice flour. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 858081006813 is the GTIN-12 on this offer (120 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-max-care-probiotics-30",
    productName: "NatureWise Max Care Probiotics (30 Count)",
    barcode: "810157850881",
    category: "Digestive",
    formulaId: "naturewise-b83-probiotics-for-women",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Max Care Probiotics", strength: "30 Count" }],
    flags: [["Microcrystalline cellulose", "cleared", "mcc"], ["Gellan gum", "cleared", "gellan"], ["Hypromellose (cellulose) capsule", "cleared", "hpmc"], ["Bamboo extract", "limited", "bamboo"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Bamboo extract. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/max-care-probiotics; image https://www.naturewise.com/cdn/shop/files/NW_-_Probiotics_30B_CFU_-_5_-_Supplement.jpg?width=1200) other-ingredients: Microcrystalline cellulose, DRcaps capsule (gellan gum, hypromellose), bamboo extract. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 810157850881 is the GTIN-12 on this offer (30 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-max-care-probiotics-60",
    productName: "NatureWise Max Care Probiotics (60 Count)",
    barcode: "858081006271",
    category: "Digestive",
    formulaId: "naturewise-b83-probiotics-for-women",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Max Care Probiotics", strength: "60 Count" }],
    flags: [["Microcrystalline cellulose", "cleared", "mcc"], ["Gellan gum", "cleared", "gellan"], ["Hypromellose (cellulose) capsule", "cleared", "hpmc"], ["Bamboo extract", "limited", "bamboo"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Bamboo extract. Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract maps to the locked organic bamboo extract Caution row. Same panel image as the 30 Count.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/max-care-probiotics; image https://www.naturewise.com/cdn/shop/files/NW_-_Probiotics_30B_CFU_-_5_-_Supplement.jpg?width=1200) other-ingredients: Microcrystalline cellulose, DRcaps capsule (gellan gum, hypromellose), bamboo extract. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 858081006271 is the GTIN-12 on this offer (60 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-ashwagandha-for-stress",
    productName: "NatureWise Ashwagandha for Stress (60 Count)",
    barcode: "858081006776",
    category: "Vitamins",
    formulaId: "naturewise-b83-ashwagandha-for-stress",
    audience: ADULT,
    minAge: 18,
    form: "capsule",
    productType: SUPPLEMENT,
    actives: [{ name: "Ashwagandha for Stress", strength: "60 Count" }],
    flags: [["Cellulose capsule", "cleared", "mcc"], ["L-leucine powder", "cleared", "leucine"], ["Rice hull concentrate", "cleared", "riceHull"], ["Bamboo extract (Bambusa vulgaris, shoot)", "limited", "bamboo"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Bamboo extract (Bambusa vulgaris, shoot). Cleared capsule, softgel, and fill tokens do not raise Avoid. Bamboo extract (Bambusa vulgaris, shoot) maps to the locked organic bamboo extract Caution row.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/ashwagandha-for-stress; image https://www.naturewise.com/cdn/shop/files/NW-AshwagandhaCapsules-5-Supplement.jpg?width=1200) other-ingredients: Cellulose capsule, L-leucine powder, rice hull concentrate, bamboo extract (Bambusa vulgaris, shoot). Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 858081006776 is the GTIN-12 on this offer (60 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-vitamin-c-chewables",
    productName: "NatureWise Vitamin C Chewables (90 Count)",
    barcode: "850053810046",
    category: "Vitamins",
    formulaId: "naturewise-b83-vitamin-c-chewables",
    audience: ADULT,
    minAge: 18,
    form: "chewable",
    productType: SUPPLEMENT,
    actives: [{ name: "Vitamin C Chewables", strength: "90 Count" }],
    flags: [["Isomalt", "limited", "isomalt"], ["Maltodextrin", "limited", "maltodextrin"], ["Turmeric oleoresin", "limited", "oleoresinTurmeric"], ["Rice bran wax", "limited", "riceBranWax"], ["Orange flavor", "limited", "flavors"], ["Rebaudioside A", "cleared", "rebA"], ["Bamboo extract", "limited", "bamboo"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Isomalt; Maltodextrin; Turmeric oleoresin; Rice bran wax; Orange flavor; Bamboo extract. Cleared capsule, softgel, and fill tokens do not raise Avoid. Turmeric oleoresin sits on the locked oleoresin turmeric Caution row, not Cleared turmeric-as-color. Rebaudioside A is the high-purity steviol glycoside row, not bare stevia extract. This chewable is not a gummy.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/vitamin-c-chewables; image https://www.naturewise.com/cdn/shop/files/NW-VitaminC90RIGHT.jpg?width=1200) other-ingredients: Isomalt, yellow pigment (maltodextrin, turmeric oleoresin), rice bran wax, orange flavor, rebaudioside A (from stevia leaf), bamboo extract. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 850053810046 is the GTIN-12 on this offer (90 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-coq10",
    productName: "NatureWise CoQ10 (200 mg / 30 Count)",
    barcode: "850053810527",
    category: "Vitamins",
    formulaId: "naturewise-b83-coq10",
    audience: ADULT,
    minAge: 18,
    form: "softgel",
    productType: SUPPLEMENT,
    actives: [{ name: "CoQ10", strength: "200 mg / 30 Count" }],
    flags: [["Rice bran oil", "cleared", "riceBranOil"], ["Tapioca starch", "cleared", "starch"], ["Glycerin", "cleared", "glycerin"], ["Annatto", "limited", "annatto"], ["Purified water", "cleared", "water"], ["Sunflower lecithin", "cleared", "lecithin"], ["Rice bran wax", "limited", "riceBranWax"], ["Rosemary liquid extract", "limited", "rosemary"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Annatto; Rice bran wax; Rosemary liquid extract. Cleared capsule, softgel, and fill tokens do not raise Avoid. Rosemary liquid extract sits on the locked oral rosemary-extract preservative Caution row. Rice bran oil in this softgel is named-fill Cleared, not rice bran wax.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/coq10; image https://www.naturewise.com/cdn/shop/files/NW-CoQ1030CountRIGHT.jpg?width=1200) other-ingredients: Rice bran oil, softgel capsule (tapioca starch, glycerin, annatto, purified water), sunflower lecithin, rice bran wax, rosemary liquid extract. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 850053810527 is the GTIN-12 on this offer (200 mg / 30 Count). No DailyMed drug SPL.",
  },
  {
    id: "naturewise-b83-coq10-90",
    productName: "NatureWise CoQ10 (200 mg / 90 Count)",
    barcode: "850053810534",
    category: "Vitamins",
    formulaId: "naturewise-b83-coq10",
    audience: ADULT,
    minAge: 18,
    form: "softgel",
    productType: SUPPLEMENT,
    actives: [{ name: "CoQ10", strength: "200 mg / 90 Count" }],
    flags: [["Rice bran oil", "cleared", "riceBranOil"], ["Tapioca starch", "cleared", "starch"], ["Glycerin", "cleared", "glycerin"], ["Annatto", "limited", "annatto"], ["Purified water", "cleared", "water"], ["Sunflower lecithin", "cleared", "lecithin"], ["Rice bran wax", "limited", "riceBranWax"], ["Rosemary liquid extract", "limited", "rosemary"]],
    verdict: "caution",
    note: "FOUNDER-LOCK DRAFT: Caution. Driver is Annatto; Rice bran wax; Rosemary liquid extract. Cleared capsule, softgel, and fill tokens do not raise Avoid. Rosemary liquid extract sits on the locked oral rosemary-extract preservative Caution row. Rice bran oil in this softgel is named-fill Cleared, not rice bran wax.",
    cite: "Current naturewise.com supplement-facts panel (https://www.naturewise.com/products/coq10; image https://www.naturewise.com/cdn/shop/files/NW-CoQ1090CountRIGHT.jpg?width=1200) other-ingredients: Rice bran oil, softgel capsule (tapioca starch, glycerin, annatto, purified water), sunflower lecithin, rice bran wax, rosemary liquid extract. Brand-site supplement-facts image is the pin for this NatureWise name. Live Amazon US exact pack when this name is listed. UPC-A 850053810534 is the GTIN-12 on this offer (200 mg / 90 Count). No DailyMed drug SPL.",
  },
];

export const BATCH83_KYR6_NATUREWISE_TOKEN_BACKFILL: RatingRecord[] = COMPACT.map(expand);

export const BATCH83_SKIPPED: { sku: string; reason: string }[] = [
  {
    sku: "Magnesium Glycinate (625 mg / 30 Count)",
    reason: "SKIPPED other. The 625 mg count tab has no supplement-facts image on naturewise.com. The right-side panels on this PDP are the 400 mg bottles. Not a no_OI hunt and not an OUT category. OI not invented.",
  },
  {
    sku: "Magnesium Glycinate (625 mg / 90 Count)",
    reason: "SKIPPED other. The 625 mg count tab has no supplement-facts image on naturewise.com. The right-side panels on this PDP are the 400 mg bottles. Not a no_OI hunt and not an OUT category. OI not invented.",
  },
];

export const BATCH83_REFUSED: { sku: string; reason: string }[] = [
  {
    sku: "Advanced Joint Care",
    reason: "REFUSED exact panel string(s) `bamboo extract`, `rice bran wax` were the batch82 blockers and are now stamped, but the current naturewise.com gallery has no complete Other Ingredients panel to re-read. OI not invented. NO Search row. SKU: Advanced Joint Care.",
  },
  {
    sku: "Liquid Multivitamin",
    reason: "REFUSED exact panel string(s) `cranberry fruit`, `organic raspberry`. Those strings are not the locked cranberry / raspberry juice or fruit-powder rows. `concentrace mineral complex`, `grapefruit extract`, and `organic aloe vera` are stamped and do not clear this row. NO Search row. SKU: Liquid Multivitamin.",
  },
  {
    sku: "Liquid Multivitamin + Hair Growth",
    reason: "REFUSED exact panel string(s) `organic raspberry powder`. Not the locked raspberry fruit powder row. `cranberry fruit powder` and `organic aloe vera powder` are stamped and do not clear this row. NO Search row. SKU: Liquid Multivitamin + Hair Growth.",
  },
  {
    sku: "Multivitamin for Men",
    reason: "REFUSED OCR junk on the bottle panel. Readable strings `bamboo extract` and `rice bran wax` are now stamped, but the rest of the Other Ingredients line did not read cleanly. OCR junk stays refuse. NO Search row. SKU: Multivitamin for Men.",
  },
  {
    sku: "Vegan Vitamin K2 Softgels",
    reason: "REFUSED exact panel string(s) `modified tapioca starchgel (cassava root)` is now stamped, but the current naturewise.com gallery has no complete Other Ingredients panel (front and marketing tiles only). OI not invented. NO Search row. SKU: Vegan Vitamin K2 Softgels.",
  },
  {
    sku: "Liquid Collagen",
    reason: "REFUSED exact panel string(s) `blueberry juice concentrate`, `non-silicone foam control agent`. Blueberry juice concentrate is not the locked blueberry juice row. Non-silicone foam control agent is unmapped. `carrot` is the bare-carrot Caution row and does not clear this row. Mango tubes print the same foam-control string. NO Search row. SKU: Liquid Collagen.",
  },
];

const _ROWS = BATCH83_KYR6_NATUREWISE_TOKEN_BACKFILL;
if (_ROWS.length !== 54) throw new Error('batch83 tally drift: expected 54 rows');
if (_ROWS.filter((r) => r.verdict === 'clean').length !== 0) throw new Error('batch83 Clean tally drift');
if (_ROWS.filter((r) => r.verdict === 'caution').length !== 54) throw new Error('batch83 Caution tally drift');
if (_ROWS.filter((r) => r.verdict === 'avoid').length !== 0) throw new Error('batch83 Avoid tally drift');
if (_ROWS.some((r) => r.recordStatus !== UNVERIFIED)) throw new Error('batch83 recordStatus must stay unverified');
if (_ROWS.some((r) => !r.formulaId)) throw new Error('batch83 every row needs formulaId');
const _ids = new Set(_ROWS.map((r) => r.id));
if (_ids.size !== _ROWS.length) throw new Error('batch83 duplicate ids');
if (_ROWS.some((r) => r.brand !== BRAND)) throw new Error('batch83 writes NatureWise only');
if (_ROWS.some((r) => r.barcode && !/^\d{12}$/.test(r.barcode))) {
  throw new Error('batch83 barcode must be a 12-digit UPC-A');
}
if (_ROWS.some((r) => {
  if (!r.barcode) return false;
  let sum = 0;
  for (let i = 0; i < 11; i++) sum += Number(r.barcode[i]) * (i % 2 === 0 ? 3 : 1);
  return (10 - (sum % 10)) % 10 !== Number(r.barcode[11]);
})) {
  throw new Error('batch83 barcode failed UPC-A check digit');
}
if (_ROWS.filter((r) => r.formulaId !== r.id).length !== 19) {
  throw new Error('batch83 REUSE-formula tally drift');
}
if (_ROWS.filter((r) => r.formulaId === r.id).length !== 35) {
  throw new Error('batch83 NEW formula drift');
}
const _formulas = new Set(_ROWS.map((r) => r.formulaId));
if (![..._formulas].every((id) => _ids.has(id!))) throw new Error('batch83 formulaId must point at a row in this file');
if (_ROWS.some((r) => /toothpaste|sprouts|now foods|nutricost|welmate|goodsense|healtha2z|time-cap|a\+health/i.test(r.brand + r.productName))) {
  throw new Error('batch83 leftover 3P / Sprouts / toothpaste / NOW / Nutricost must stay out');
}
if (_ROWS.some((r) => /\boil\b/i.test(r.productName) && !/softgel|capsule|gumm|tablet|chew/i.test(r.productName + (r.form ?? '')))) {
  throw new Error('batch83 must not grade oil pour bottles');
}
for (const record of _ROWS) {
  if (record.verdict === 'avoid' && !record.inactiveIngredients.some((i) => i.riskLevel === 'high')) {
    throw new Error(`batch83 Avoid without High on ${record.id}`);
  }
  if (record.verdict === 'caution' && !record.inactiveIngredients.some((i) => i.riskLevel === 'limited' || i.riskLevel === 'moderate')) {
    throw new Error(`batch83 Caution without Limited or Moderate on ${record.id}`);
  }
  if (record.verdict === 'clean' && record.inactiveIngredients.some((i) => i.riskLevel !== 'cleared')) {
    throw new Error(`batch83 Clean row has a non-cleared flag on ${record.id}`);
  }
  if (record.form === 'gummy') throw new Error(`batch83 has no gummy rows: ${record.id}`);
  const corn = record.inactiveIngredients.find((i) => i.name === 'Corn oil');
  if (corn && corn.riskLevel !== 'cleared') {
    throw new Error(`batch83 non-gummy corn oil must stay Cleared fill on ${record.id}`);
  }
}
if (BATCH83_SKIPPED.length !== 2) throw new Error('batch83 skip tally drift');
if (BATCH83_SKIPPED.some((s) => /SKIPPED no_OI/.test(s.reason))) throw new Error('batch83 no_OI must stay 0');
if (BATCH83_SKIPPED.some((s) => /SKIPPED OUT/.test(s.reason))) throw new Error('batch83 OUT must stay 0');
if (!BATCH83_SKIPPED.every((s) => /no supplement-facts image/i.test(s.reason) && /not a no_OI hunt/i.test(s.reason) && /not an OUT/i.test(s.reason))) {
  throw new Error('batch83 skips are the 625 mg missing-image tabs only');
}
if (BATCH83_REFUSED.length !== 6) throw new Error('batch83 refuse tally drift');
if (BATCH83_REFUSED.some((s) => !/`[^`]+`/.test(s.reason))) throw new Error('batch83 REFUSED must quote an exact panel string');
